### PR TITLE
fix styling error and add translation for formErrors

### LINKED ISSUE #13020: Missing translations for form validity errors in import dialog
missing translations for 
- `common:formErrors.fileTooLarge`
- `common:formErrors.invalidExtension`
- `common:formErrors.fileEmpty`
- (notParsable?)
- verify can we override it in way, that we have it in our feature-lib

### LINKED ISSUE #13021: Fix styling for form errors (margin) in import dialog
image

### PR DESCRIPTION
**Pull request by Parthlakhani**
closes #13021 
closes #13020

### CODE REVIEW

File: projects/assets/src/translations/en/common.ts [hunk 1]
```diff
@@ -154,6 +154,9 @@ export const common = {
       pattern: 'Use dateformat yyyy-mm-dd',
       invalid: 'Use a valid date',
     },
+    fileEmpty: 'File should not be empty',
+    invalidExtension: 'File extension is not valid',
+    fileTooLarge: 'File size is too large',
```
Comment (Pucek9) [inline projects/assets/src/translations/en/common.ts]:
```suggestion
    fileEmpty: 'File should not be empty.',
    invalidExtension: 'File extension is not valid.',
    fileTooLarge: 'File size is too large.',
```

Comment (Pucek9) [reply projects/assets/src/translations/en/common.ts]: or
```suggestion
    file: {
      empty: 'File should not be empty',
      invalidExtension: 'File extension is not valid',
      tooLarge: 'File size is too large',
    },
```

File: feature-libs/cart/import-export/components/import-to-cart/import-entries-dialog/import-entries-dialog.component.html [hunk 2]
```diff
@@ -56,8 +56,8 @@
           <p *ngIf="selectedFile?.name">
             {{ selectedFile.name }}
           </p>
-          <cx-form-errors [control]="form.get('file')"></cx-form-errors>
         </div>
+        <cx-form-errors [control]="form.get('file')"></cx-form-errors>
```
Comment (Pucek9) [inline feature-libs/cart/import-export/components/import-to-cart/import-entries-dialog/import-entries-dialog.component.html]:
```suggestion
        <cx-form-errors
          [control]="form.get('file')"
          prefix="formErrors.file"
        ></cx-form-errors>
```

File: projects/assets/src/translations/en/common.ts [hunk 3]
```diff
@@ -154,6 +154,11 @@ export const common = {
       pattern: 'Use dateformat yyyy-mm-dd',
       invalid: 'Use a valid date',
     },
+    file: {
+      empty: 'File should not be empty',
+      invalidExtension: 'File extension is not valid',
+      tooLarge: 'File size is too large',
```
Comment (Pucek9) [inline projects/assets/src/translations/en/common.ts:161]:
```suggestion
      empty: 'File should not be empty.',
      invalidExtension: 'File extension is not valid.',
      tooLarge: 'File size is too large.',
```

**Review by Pucek9 — APPROVED** [review]

**Review by Pucek9 — APPROVED** [review]
