### PR TITLE
GH-8797: remove flag and fix css

### LINKED ISSUE #8797: Update B2b register button
Following #8302 

Remove feature flag since this is in a major. (schematics to be handled in #7509). Also update CSS because it is not currently centered correctly.

### Acceptance

**With the latest sample data from `release/2005/next`**

- B2c register and guest checkout works as before
- B2b no register button and can't visit `/register` page (404)

### PR DESCRIPTION
**Pull request by LTiger14**
closes #8797

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/user/login-register/login-register.component.ts [hunk 1]
```diff
@@ -16,6 +16,7 @@ export class LoginRegisterComponent implements OnInit {
 
   ngOnInit(): void {
     if (this.checkoutConfigService.isGuestCheckout()) {
+      console.log('true');
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/src/cms-components/user/login-register/login-register.component.ts]: remove log

Comment (bgambocjaviniar) [reply projects/storefrontlib/src/cms-components/user/login-register/login-register.component.ts]: line 18 (above)

I don't think we need the flag for this anymore.

I don't remember the context for guest checkout exactly, but since this is cms-driven, I believe we don't need to have that config flag anymore too

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
1- can still visit /login/register 
in the sampledata ContentPage `register` maybe need to add a property active and set it to false for powertools catalog (not sure If i'm right about that)

2 - consent template infinite call (I forgot the reason and how to fix it, but I think it's because we're using the wrong consent template which is suposed to be personalization and not profile. Response shows profile in the template. https://sap.github.io/spartacus-docs/anonymous-consent/#consent-data) ----> not really related to the PR but it was killing my computer (sample-data issue for powertools)

File: projects/storefrontlib/src/cms-components/user/login-register/login-register.component.ts (hunk 1 above)
Comment (LTiger14) [reply projects/storefrontlib/src/cms-components/user/login-register/login-register.component.ts]: We still need the config flag for guest checkout. This part is not fully CMS driven.

Comment (LTiger14) [reply projects/storefrontlib/src/cms-components/user/login-register/login-register.component.ts]: 1. I added a PR to the sample data, changed the page status.

2. I looked into it a lot. This happens on all catalogs on my local. It's not the personalization, I changed it out and nothing happened. All dev servers use the PROFILE consent.

**One thing I noticed is that on dev4 we have the same sample data but not this problem.** It might mean our local has something wrong.

**Review by bgambocjaviniar — APPROVED** [review]
