### PR TITLE
fix: Unexpected info for root unit in subsections

### LINKED ISSUE #11529: Unexpected info for root unit in subsections
replace in UnitDetails
  <cx-org-disable-info
    info
    i18nRoot="orgUnit"
    [displayInfoConfig]="{ disabledDisable: true }"
  >

and set disabledDisable flag as false by default

### PR DESCRIPTION
**Pull request by Pucek9**
Closes #11529

### CODE REVIEW

**Review by Parthlakhani — APPROVED** [review]

File: feature-libs/organization/administration/components/shared/detail/disable-info/disable-info.component.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ export class DisableInfoComponent<T extends BaseItem> implements OnInit {
       disabledCreate: false,
       disabledEdit: true,
       disabledEnable: true,
-      disabledDisable: true,
```
Comment (Zeyber) [inline feature-libs/organization/administration/components/shared/detail/disable-info/disable-info.component.ts:54]: Should use a feature level condition to set this to avoid breaking change.

Should suffice:
```
disabledDisable: this.featureLevelService.isLevel('3.2')
```

File: feature-libs/organization/administration/components/unit/details/unit-details.component.html [hunk 2]
```diff
@@ -14,7 +14,12 @@
     i18nRoot="orgUnit"
   ></cx-org-toggle-status>
 
-  <cx-org-disable-info info i18nRoot="orgUnit"> </cx-org-disable-info>
+  <cx-org-disable-info
+    info
+    i18nRoot="orgUnit"
+    [displayInfoConfig]="{ disabledDisable: true }"
```
Comment (Zeyber) [inline feature-libs/organization/administration/components/unit/details/unit-details.component.html:20]: Also breaking change as it changes template behaviour (ie. root button now being disabled by default). Need feature level flag solution for this like above comment.

**Review by Zeyber — CHANGES_REQUESTED** [review]

File: feature-libs/organization/administration/components/shared/detail/disable-info/disable-info.component.ts (hunk 1 above)
Comment (Pucek9) [reply feature-libs/organization/administration/components/shared/detail/disable-info/disable-info.component.ts:54]: 1 functional changes are allowed without breaking changes support
2 its fix for not released feature yet
@marlass Please confirm

Comment (marlass) [reply feature-libs/organization/administration/components/shared/detail/disable-info/disable-info.component.ts:54]: >2 its fix for not released feature yet

This makes it not a breaking change. Don't need feature flag here

**Review by Zeyber — APPROVED** [review]
