### PR TITLE
fix: avoid sharing i18next instance in between SSR requests (for 2.0.x) 

### LINKED ISSUE #8100: i18next instance is shared in between SSR requests
The i18next instance is shared in between all SSR requests. This could be buggy, i.e. when 2 requests are made at the same time for different acitive langauges. We should create a fresh instance for each SSR request.

### PR DESCRIPTION
**Pull request by Platonn**
The i18next global instance as shared in between all SSR requests. This was buggy, i.e. when 2 requests are made at the same time for different acitive langauges. Now we fix it, by creating a fresh instance for each SSR request (for each app bootstrap).

close #8100

### CODE REVIEW

File: projects/core/src/i18n/i18next/i18next-init.ts [hunk 1]
```diff
@@ -1,18 +1,26 @@
...
   httpClient: HttpClient,
-  serverRequestOrigin: string
+  serverRequestOrigin: string,
+  siteContextI18nextSynchronizer: SiteContextI18nextSynchronizer
 ): () => Promise<any> {
   return () =>
     configInit.getStableConfig('i18n').then((config) => {
+      // SPIKE TODO REMOVE:
+      window['globalI18next'] = globalI18next;
+      window['i18next'] = i18next;
```
Comment (CarlEricLavoie) [inline projects/core/src/i18n/i18next/i18next-init.ts]: @Platonn  - we're very interested in this fix for one of our customer, so if you don't mind i'll add some comments to make sure I understand the fix.

In this particular case, wouldn't this fail in SSR due to window being undefined?

Comment (dunqan) [reply projects/core/src/i18n/i18next/i18next-init.ts]: Hi @CarlEricLavoie, no worries, those lines will be removed before merge as it's work in progress at the moment.

File: projects/core/src/i18n/i18next/i18next-translation.service.ts [hunk 2]
```diff
@@ -1,19 +1,36 @@
...
 
 @Injectable({ providedIn: 'root' })
 export class I18nextTranslationService implements TranslationService {
   private readonly NON_BREAKING_SPACE = String.fromCharCode(160);
   protected readonly NAMESPACE_SEPARATOR = ':';
 
+  /**
+   * @deprecated use instead the constructor variant with `I18NEXT_INSTANCE` token as the 3rd parameter.
+   */
+  constructor(config: I18nConfig, translationChunk: TranslationChunkService);
```
Comment (dunqan) [inline projects/core/src/i18n/i18next/i18next-translation.service.ts]: Please, double check if you are getting the new i18next parameter properly injected in the prod build, if this overload is specified as a first one.

**Review by dunqan — APPROVED** [review]
