### PR TITLE
fix: Fix cart items refreshing for every value change

### LINKED ISSUE #10379: TODO: Cart items refreshing for every value change
Hi everyone.

Is this TODO planned to be solved soon ? We are facing some terrible performance issues within 100+ products baskets. The initial rendering is quite OK, but then, everytime we change a QTY, all the lines are re-renderer so the interaction is very slow.

https://github.com/SAP/spartacus/blob/91db09804fa53c5f2a6d1289c02a3c9fe79f67a5/projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts#L32-L39

Thanks a lot !

### PR DESCRIPTION
**Pull request by Zeyber**
Closes: #10379

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts [hunk 1]
```diff
@@ -78,12 +79,23 @@ export class CartItemListComponent {
         return entry;
       });
     } else {
-      this._items = items;
+      if (this.featureConfigService?.isLevel('3.1')) {
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts:85]: Can we also bump the feature level in app.module.ts to `3.1`, so the new behavior becomes the default (btw. e2e will cover the new behavior)?

File: projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts [hunk 2]
```diff
@@ -55,7 +55,8 @@ export class CartItemListComponent {
 
   constructor(
     protected activeCartService: ActiveCartService,
-    protected selectiveCartService: SelectiveCartService
+    protected selectiveCartService: SelectiveCartService,
+    public featureConfigService?: FeatureConfigService
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts:59]: Would you mind creating a ticket to clean up the feature-level conditions introduced in this PR?

File: projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts [hunk 3]
```diff
@@ -78,12 +79,23 @@ export class CartItemListComponent {
         return entry;
       });
     } else {
-      this._items = items;
+      if (this.featureConfigService?.isLevel('3.1')) {
+        for (let i = 0; i < items.length; i++) {
+          if (JSON.stringify(this._items?.[i]) !== JSON.stringify(items[i])) {
+            this._items[i] = items[i];
+          }
+        }
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts:90]: Although I understand it, the reason of adding this logic is not obvious. Can we add a code comment? For example:
```ts
// We'd like to avoid the unnecessary re-renders of unchanged cart items after the data reload.
// OCC cart entries don't have any unique identifier that we could use in Angular `trackBy`.
// So we update each array element to the new object only when it's any different to the previous one.
```

File: projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts (hunk 2 above)
Comment (Zeyber) [reply projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts:59]: Clean up ticket created: https://github.com/SAP/spartacus/issues/11037

**Review by Platonn — APPROVED** [review]
