### PR TITLE
fix: GH-9103 Use DateTimePickerFormatterService in Replenishment Order

### LINKED ISSUE #9103: Use DatePickerFormatterService in Replenishment Order, and also fix the logic if it applies.
master ticket: GH-8202

* This will be worked on after merging epic/b2b-scheduled-repl into develop

Similarly, replenishment was using `toISOString` to convert the date into date format of ISO 8601.
Therefore, replenishment should start using DatePickerFormatterService services

---
Additionally, the logic for both is not the correct one as it is converting the local date time (your current timezone) into the general UTC+0 date. I noticed sometimes when ordering a replenishment order that the date did not match as the conversion from local date to UTC broke it. --> To verify with any others

### PR DESCRIPTION
**Pull request by saad-mo**
closes #9103

- Moved `DatePickerFormatterService` and `DateTimePickerFormatterService` to the core to make it easier for other features to use these services 
- Used `DateTimePickerFormatterService` in `OccReplenishmentOrderFormSerializer` because we need accurate time in the string. I found that the order was off by a day when the time was being zeroed out (00:00:00). 
- Furthermore, the date picker returns a string with the current time only if the replenishment date is not changed. If the date is changed, the date picker does not return the current time. `OccReplenishmentOrderFormSerializer` has been updated to handle this `getCurrentLocalTime` function. 
- Finally, we are using `toModel` method from `DateTimePickerFormatterService` to append an accurate timezone to the date string. 

OLD PR: https://github.com/SAP/spartacus/pull/9234

### CODE REVIEW

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts [hunk 1]
```diff
@@ -27,10 +30,31 @@ export class OccReplenishmentOrderFormSerializer
...
+   * @Example
+   * Converts 2020-10-15T15:38:05 or 2020-10-15 2020-10-15T15:38:05-05:00
    */
   private convertDate(date: string): string {
-    const dateTime = '00:00:00';
-    return new Date(date).toISOString().split('T')[0] + 'T' + dateTime + 'Z';
+    const index = date.lastIndexOf(':');
+    let modelDate;
+    if (index > 0) {
+      modelDate = date.slice(0, index);
```
Comment (bgambocjaviniar) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]: When index is bigger than 0, then that means a `:` is found. This case covers the issue, where the user did not choose a date from the datepicker. However, this logic is wrong, where you target the last index of a colon because the date string that was provided contains the hours and mins already which is set to UTC, therefore the hours being 4 hours ahead. 

For example, the default value that came contains `2011-10-05T14:48:00.000Z`, but 14:48 is the wrong datetime as the current eastern time would be 10:48, so instead of stripping the string from ':', we would strip the string from `T`.

All in all, I have provided a snippet and potential solution in the following link https://github.com/SAP/spartacus/pull/9457#discussion_r510454392

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts [hunk 2]
```diff
@@ -27,10 +30,31 @@ export class OccReplenishmentOrderFormSerializer
...
+    } else {
+      modelDate = `${date}T${this.getCurrentLocalTime()}`;
```
Comment (bgambocjaviniar) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]: 👍

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts [hunk 3]
```diff
@@ -1,29 +1,55 @@
...
   });
 
   it('should create', () => {
     expect(serializer).toBeTruthy();
   });
 
-  it('should convert the date string of schedule replenishment form to ISO 8601 format', () => {
-    const mockDate = '1994-01-11';
-    const ISODateFormat = mockDate + 'T00:00:00Z';
+  it('should convert the date string with time', () => {
```
Comment (bgambocjaviniar) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts]: add a test for `getCurrentLocalTime` please

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts [hunk 4]
```diff
@@ -1,29 +1,55 @@
...
+    const mockDateWithTime = '1994-01-11:01:02:03.456Z';
```
Comment (bgambocjaviniar) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts]: As mentioned in the component, where I inserted comments, the date by default without choosing a date from the datepicker comes in utc time already, so this mock date with time is wrong as it won't represent the case you're trying to test

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts [hunk 5]
```diff
@@ -27,10 +30,31 @@ export class OccReplenishmentOrderFormSerializer
   }
 
   /**
-   * Converts the date string to the Standard ISO 8601 format
+   * Converts the date string from a Standard ISO 860 format with or without time to valid OCC model format
```
Comment (bgambocjaviniar) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]: I would not change the comment as the ' accepted occ model format' is literally a Standard ISO 8601 format

Comment (bgambocjaviniar) [reply projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]: Moreover, there's a typo, where you mentioned 860 and not 8601

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts (hunk 4 above)
Comment (bgambocjaviniar) [reply projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts]: The format is wrong too, where the mock date has a `T` and not a `:`

I would fix to have some data consistency even if mocked for this special representation.

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts [hunk 6]
```diff
@@ -27,10 +30,31 @@ export class OccReplenishmentOrderFormSerializer
...
-    return new Date(date).toISOString().split('T')[0] + 'T' + dateTime + 'Z';
+    const index = date.lastIndexOf(':');
+    let modelDate;
+    if (index > 0) {
+      modelDate = date.slice(0, index);
+    } else {
+      modelDate = `${date}T${this.getCurrentLocalTime()}`;
+    }
+
+    return this.dateTimePickerFormatterService.toModel(modelDate);
```
Comment (bgambocjaviniar) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]: *Potential solution

I went ahead and look through a fix
Hopefully, my provided snippet will help with your problem.

```
private convertDate(date: string): string {
// native date will always give YYYY-MM-DD whether the default date
// was sent from the replenishment form or from the datepicker
    const nativeDate = this.datePickerFormatterService.toNative(date);

**// potential re-work or added value to the toModel function 
// either pass a param that will set the HH:MM:ss||00 when given,** 
// therefore needing to massage the logic in the toModel function of the DatePickerFormatter service. 
// Verify with Caine if that logic can or should be added to that service. 
//I believe it should as we're working with a datepicker and not a datetime-local. What do you think?
    const modelDate = this.datePickerFormatterService.toModel(
      nativeDate,
      false,
      this.getCurrentLocalTime ?
    );

 // modelDate would contain the value YYYY-MM-DDTHH:MM:SSZ or YYYY-MM-DDTHH:MM:SS+00:00 
 // YYYY-MM-DD = the nativeDate
 // HH:MM:SS can be given from the `getCurrentLocalTime` function which will most likely be moved to datepicker service
    return modelDate;
  }
```

After looking through the snippet above, 

please do the following

1) need to checkup with someone to check out the backend as I believe we don't have to set the offset, and we only needed to set the datetime HH:mm:ss in order to get the proper value back

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
Small quick question: Why was the PR necessary to re-create?

--------

I dug dipper and the fix for this date problem is just to provide the datetime hh:mm:00 with no offset of timezone, but with +00:00

Moreover, from my findings and additional testing, I believe there is no need to pass an offset of a timezone as that does not work well from the given response of a request as it will add/substract to the current time that was originally sent. (from here https://github.com/SAP/spartacus/pull/9234#discussion_r503218703)

What was sent as a request
Screen Shot 2020-10-22 at 5 06 19 PM

What we receive as response
Screen Shot 2020-10-22 at 5 06 30 PM

As you can see, what was being sent is 17:06, but the response that was given due to the offset became 21:06. The offset added additional time to the original current datetime of the date.

I proposed a potential solution with a snippet in https://github.com/SAP/spartacus/pull/9457#discussion_r510454392

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts (hunk 2 above)
Comment (hackergil) [reply projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]: I got rid of this. Service should just get a date with no time

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts (hunk 3 above)
Comment (hackergil) [reply projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts]: I think there's no need anymore.

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts (hunk 4 above)
Comment (hackergil) [reply projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts]: Fixed

File: projects/storefrontlib/src/cms-components/checkout/services/checkout-replenishment-form-service.ts [hunk 7]
```diff
@@ -19,7 +19,7 @@ export class CheckoutReplenishmentFormService {
     numberOfDays: '14',
     numberOfWeeks: '1',
     recurrencePeriod: recurrencePeriod.DAILY,
-    replenishmentStartDate: new Date().toISOString(),
+    replenishmentStartDate: new Date().toISOString().split('T')[0],
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/src/cms-components/checkout/services/checkout-replenishment-form-service.ts:22]: 👍  Better than changing it in the serializer

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
LGTM except the offset, we need to talk about this before approval
Thanks for picking it up Gil.

**Review by bgambocjaviniar — APPROVED** [review]
