### PR TITLE
Feature/gh 15827 fix vc e2e tests

### LINKED ISSUE #15827: Fix Mock VC cypress tests
See TEAM_SERVER_01_CE_B2C_MOCK_CYPRESS_TESTS job
There are 2 failing tests:
image

### PR DESCRIPTION
**Pull request by ChristophHi**

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator-vc.ts [hunk 1]
```diff
@@ -21,6 +21,18 @@ export function goToConfigurationPage(shopName: string, productId: string) {
...
 
+/**
+ * Navigates to the configuration overview  page.
+ * @return {Chainable<Window>} - New configuration window
+ */
+export function navigateToOverviewPage() {  
+  cy.get('.cx-tab-bar').within(() => {
+    cy.get('a')
+      .filter((index) => index === 1)
+      .click();
```
Comment (Larisa-Staroverova) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator-vc.ts]: To be 100% sure that the test is on OP after clicking on the Overview tab you could check whether the OP has been loaded:
```
.then(() => {
        cy.location('pathname').should('contain', '/en/USD/configure-overview/vc/product/entityKey/');
 });
```

**Review by Larisa-Staroverova — DISMISSED** [review]

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator-vc.ts (hunk 1 above)
Comment (ChristophHi) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator-vc.ts]: Agree. fixed that

**Review by Larisa-Staroverova — DISMISSED** [review]

**Review by Larisa-Staroverova — APPROVED** [review]
