### PR TITLE
fix: labels updates for screen reader support GH-11192

### LINKED ISSUE #11192: [Master] Headings and Labels
## What are Headings and Labels 
**In a nutshell:** Provide hierarchically organized and descriptive headings for content. Provide descriptive labels that will help users identify elements or components within the content.

E.g. Headings make it possible to **predict content** for each section. Labels make an element or component's **purpose clear.**

## Overview
- Success Criterion [WCAG 2.1 2.4.6](https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html)  
- **MASTER** Ticket #11672
- [**Github label:**](https://github.com/SAP/spartacus/issues?q=is%3Aissue+is%3Aopen+label%3Aa11y-sr%2Fheadings-and-labels) `a11y-sr/headings-and-labels`

### Headings - Changes are merged to Epic
- [x] #11151
- [x] #11543
- [x] #12731 
- [x] #12888
- [x] #13320
- [x] #13435
- [x] #13436
- [x] #13437
- [x] #13483 
- [x] #13484
- [x] #13371
- [x] #13372
- [x] #13359

### Labels

Done
- [x] Split and Sync up separate Epic branch
- [x] #7122 (#10734) 
- [x] #10887
- [x]  #11204
- [x]  #11194
- [x] #11193
- [x] #12933
- [x] #13429 
- [x] #13433
- [x] #13434
- [x] #13439

### PR DESCRIPTION
**Pull request by saad-mo**
This PR includes Label changes from #11192.

Closes #11192

### CODE REVIEW

File: projects/storefrontlib/src/shared/components/list-navigation/sorting/sorting.component.ts [hunk 1]
```diff
@@ -32,4 +32,11 @@ export class SortingComponent {
   sortList(sortCode: string): void {
     this.sortListEvent.emit(sortCode);
   }
+
+  get selectedLabel() {
```
Comment (hackergil) [inline projects/storefrontlib/src/shared/components/list-navigation/sorting/sorting.component.ts:36]: Please add a unit test for this method

**Review by hackergil — CHANGES_REQUESTED** [review]

File: projects/storefrontlib/src/shared/components/list-navigation/sorting/sorting.component.ts (hunk 1 above)
Comment (saad-mo) [reply projects/storefrontlib/src/shared/components/list-navigation/sorting/sorting.component.ts:36]: @Pucek9

**Review by hackergil — DISMISSED** [review]

**Review by hackergil — DISMISSED** [review]

**Review by hackergil — APPROVED** [review]
