### PR TITLE
inject loading obervable into quantity componet

### LINKED ISSUE #11460: Disabling of quantity picker does not work on product card
ConfiguratorAttributeProductCardComponent has a 'loading$' attribute that apparently should disable quantity input once an action has taken place.
This does not work. To easily see that, turn performance to 'slow 3g' in developer tools. The quantity can be changed when updates are in progress, it seems the qty component is not updated.

### PR DESCRIPTION
**Pull request by Uli-Tiger**
to make the picker enable/disable dynamically we must hand in an observable and subscribe to it.
also fixed strict mode issues in the files i touched., in case it was trivial

### CODE REVIEW

File: feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts [hunk 1]
```diff
@@ -40,22 +40,29 @@ export class ConfiguratorAttributeQuantityComponent
...
+        }
+      }
+    );
+    if (sub) this.managedSubscriptions.add(sub);
 
     const debounceQuantity = this.quantity.valueChanges.pipe(
       debounce(() =>
         timer(this.config?.rulebasedConfigurator?.quantityDebounceTime)
       )
     );
```
Comment (ChristophHi) [inline feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: I guess here a `take(1)` is missing.
Because increasing the quantity multiple times, always being faster than the debounce time, will lead to a huge queue of requests after the debounce time finally passed.
This leads to errors even on slow network
Screen Shot 2021-03-15 at 07 52 18

File: feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts [hunk 2]
```diff
@@ -40,22 +40,29 @@ export class ConfiguratorAttributeQuantityComponent
 
   ngOnInit() {
     this.quantity.setValue(this.quantityOptions?.initialQuantity?.quantity);
-
-    if (this.quantityOptions?.disableQuantityActions) {
-      this.quantity.disable();
-    }
+    const sub = this.quantityOptions.disableQuantityActions?.subscribe(
```
Comment (ChristophHi) [inline feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: Why is the needed? Can't we directly subscribe on quantityOptions.disableQuantityActions in the view?
(via readOnly attribute?)

**Review by ChristophHi — CHANGES_REQUESTED** [review]

File: feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts (hunk 1 above)
Comment (Uli-Tiger) [reply feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: yes there was missing something (forgot to push Friday evening) - actually it seems that the stepper itself is emitting a quantity change event in case it gets enabled, even if quantity itself was not changed at all.
That leads to an endless loop. as the quantity update will disabled/enable the stepper and hence the next quantity change is emitted and so on.
So i now unsubscribe on disable and re-subscribe on enable.  Maybe this could also be handle by a filter, but i had troubles finding one.

File: feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts (hunk 2 above)
Comment (Uli-Tiger) [reply feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: it was already like this - but i quickly tested it. When using the disabled property, the styling is different. Plus and minus buttons just disappear. When disabling/enabling method, plus and minus get greyed out. I guess the later is, what we desire.

Comment (ChristophHi) [reply feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: Ok I see

File: feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts (hunk 1 above)
Comment (ChristophHi) [reply feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: I don't get that, why not simply take(1)?
I tried that, for me it's working fine. Or did you face an issue with it?

**Comment by Uli-Tiger** [comment]
Also diese beiden Tests sollen funktionieren:
A) camera bundle: zweite memory card hinzufügen, dann eine removen. Der Stepper sollte beim click auf remove zu erst auf disabled gehen und dann verschwinden.
B) Attr types  produkt, attribute Choose CB_BND_QA_R, einen value adden und quantity verändern. es sollte nur genau ein PATCH und GET gesendet werden.

Das ist mir bisher nur meit meiner Lösung gelungen, mit take funktioniert immer nur ein fall je nachdem ob ich take(1) oder take(2) verwende

File: feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts [hunk 3]
```diff
@@ -30,32 +30,38 @@ export interface ConfiguratorAttributeQuantityComponentOptions {
 export class ConfiguratorAttributeQuantityComponent
   implements OnDestroy, OnInit {
   quantity = new FormControl(1);
-  protected sub: Subscription;
+  protected qunatitySubscription: Subscription = new Subscription();
```
Comment (ChristophHi) [inline feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: Typo

File: feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts [hunk 4]
```diff
@@ -30,32 +30,38 @@ export interface ConfiguratorAttributeQuantityComponentOptions {
...
       )
-    );
-
-    this.sub = debounceQuantity.subscribe(() => this.onChangeQuantity());
+      .subscribe(() => this.onChangeQuantity());
   }
 
   ngOnDestroy() {
-    this.sub.unsubscribe();
+    // this.managedSubscriptions.unsubscribe();
```
Comment (ChristophHi) [inline feature-libs/product-configurator/rulebased/components/attribute/quantity/configurator-attribute-quantity.component.ts]: Please remove commented line

**Review by ChristophHi — CHANGES_REQUESTED** [review]

**Review by ChristophHi — APPROVED** [review]
