### PR TITLE
fix: Move the delete cart events from saved cart to the general cart event builder

### LINKED ISSUE #15255: Move the delete cart events from saved cart to the general cart event builder
Currently, the CartActions for deleting a cart is registered with the saved cart events builder. Some features would want to 'catch' the delete cart events, but it is currently thrown by the SavedCartEvents, which is semantically wrong.

Thanks to @BenjaminEmiliani to finding the issue

### PR DESCRIPTION
**Pull request by bgambocjaviniar**
closes GH-15255

### CODE REVIEW

File: projects/schematics/src/shared/constants.ts [hunk 1]
```diff
@@ -465,6 +468,12 @@ export const SAVED_CART_DETAILS_OVERVIEW_COMPONENT =
   'SavedCartDetailsOverviewComponent ';
 export const SAVED_CART_DETAILS_SERVICE = 'SavedCartDetailsService';
 export const SAVED_CART_FACADE = 'SavedCartFacade';
+export const SAVED_CART_EVENT_BUILDER = 'SavedCartEventBuilder';
+export const REGISTER_DELETE_SAVED_CART_EVENTS =
+  'registerDeleteSavedCartEvents';
+export const DELETE_SAVED_CART_EVENT = 'DeleteSavedCartEvent';
+export const DELETE_SAVED_CART_SUCCESS_EVENT = 'DeleteSavedCartSuccessEvent';
+export const DELETE_SAVED_CART_FAIL_EVENT = 'DeleteSavedCartFailEvent';
```
Comment (BenjaminEmiliani) [inline projects/schematics/src/shared/constants.ts]: Hey @bgambocjaviniar are these constants being used anywhere?

File: docs/migration/5_0.md [hunk 2]
```diff
@@ -464,4 +464,18 @@ The following keys have been added to `configurator-common.ts`:
 
 #### Translations (i18n) changes
 
-- Added new key `product.productFacetNavigation.ariaLabelItemsAvailable` to improve Screen Readers vocalization.
\ No newline at end of file
+- Added new key `product.productFacetNavigation.ariaLabelItemsAvailable` to improve Screen Readers vocalization.
+
+### Events
```
Comment (BenjaminEmiliani) [inline docs/migration/5_0.md]: Should this maybe be:
`### SavedCartEvent`

**Review by BenjaminEmiliani — APPROVED** [review]
