### PR TITLE
fix: Carousel button labels

### LINKED ISSUE #13429: Carousel buttons need labels
**Describe the bug**

- Automated tests reveal missing labels in the carousel's buttons.
- While navigating with VoiceOver (or any Screen Reader), controls are missing labels and descriptions.
- These are all Top Severity bugs as per screenshots.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**

1. Go to Homepage
2. Open VoiceOver
3. Tab to Carousel
4. Hear the error: vocalizes "button" for each unlabeled instance.

**Expected behavior**

- Labels should be added so automated test passes.
- Labels should be meaningful so they make sense when browser with Screen Readers. E.g. Previous Slide, Current slide, Next Slide. Slide or "Group of products".

**Screenshots**
Screen Shot 2021-08-04 at 7 14 37 PM
Screen Shot 2021-08-04 at 7 11 44 PM
Screen Shot 2021-08-05 at 12 04 47 PM
Screen Shot 2021-08-05 at 12 03 45 PM
Screen Shot 2021-08-05 at 12 03 00 PM
Screen Shot 2021-08-05 at 12 01 47 PM

**Additional context**

- This ticket doesn't aim to solve outstanding issues in the Carousel, such a those outlined in this ticket GH-9481.

**Desktop (please complete the following information):**

- OS: BigSur 11.4
- Browser Chrome Version 92.0.4515.107
- Screen Reader: VoiceOver

### PR DESCRIPTION
**Pull request by bit172**
closes #13429

### CODE REVIEW

File: projects/storefrontlib/shared/components/carousel/carousel.component.ts [hunk 1]
```diff
@@ -90,4 +90,15 @@ export class CarouselComponent implements OnInit {
       .getItemsPerSlide(this.el.nativeElement, this.itemWidth)
       .pipe(tap(() => (this.activeSlide = 0)));
   }
+
+  getIndicatorAriaLabel(size: number, currentIndex: number, length: number) {
```
Comment (saad-mo) [inline projects/storefrontlib/shared/components/carousel/carousel.component.ts]: need a unit test for this function

File: projects/storefrontlib/shared/components/carousel/carousel.component.ts [hunk 2]
```diff
@@ -90,4 +90,15 @@ export class CarouselComponent implements OnInit {
...
+    let normalizedCurrentIndex;
+    if (currentIndex === 0) {
+      normalizedCurrentIndex = 1;
+    } else {
+      normalizedCurrentIndex = currentIndex;
+    }
+    const currentSlide = Math.ceil((size * normalizedCurrentIndex) / length);
+    return `slide ${currentSlide}`;
```
Comment (saad-mo) [inline projects/storefrontlib/shared/components/carousel/carousel.component.ts]: `slide` here is static text. it can be moved to the template and also converted into a translation key.

File: projects/storefrontlib/shared/components/carousel/carousel.component.html [hunk 3]
```diff
@@ -7,6 +7,7 @@ <h2 *ngIf="title">{{ title }}</h2>
       class="previous"
       (click)="activeSlide = activeSlide - size"
       [disabled]="activeSlide === 0"
+      [attr.aria-label]="'common.carousel.previous' | cxTranslate"
```
Comment (BenjaminEmiliani) [inline projects/storefrontlib/shared/components/carousel/carousel.component.html]: I believe you meant [attr.aria-label]="'carousel.previous' | cxTranslate"

**Review by BenjaminEmiliani — CHANGES_REQUESTED** [review]

File: projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts [hunk 4]
```diff
@@ -275,6 +275,17 @@ describe('Carousel Component', () => {
         );
         expect(el.length).toEqual(2);
       });
+
+      it('should have the right indicator labels', () => {
```
Comment (saad-mo) [inline projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts]: duplicate of `it` on line 324

File: projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts [hunk 5]
```diff
@@ -309,6 +320,17 @@ describe('Carousel Component', () => {
         );
         expect(el.length).toEqual(3);
       });
+
+      it('should have the right indicator labels', () => {
```
Comment (saad-mo) [inline projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts]: duplicate of `it` on line 279

File: projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts [hunk 6]
```diff
@@ -375,4 +397,18 @@ describe('Carousel Component', () => {
       });
     });
   });
+
+  describe('getSlideNumber', () => {
+    it('should return the 3rd slide', () => {
+      expect(component.getSlideNumber(1, 2)).toBe(3);
+    });
+
+    it('should return the 1rst slide', () => {
```
Comment (saad-mo) [inline projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts]: should return the `1st` slide

File: projects/assets/src/translations/en/common.ts [hunk 7]
```diff
@@ -147,6 +147,11 @@ export const common = {
       productList: 'Product List',
     },
   },
+  carousel: {
```
Comment (saad-mo) [inline projects/assets/src/translations/en/common.ts:150]: maybe make the key names more specific 

- previousSlide: 'Previous slide',
- nextSlide: 'Next Slide' 
- slideNumber: 'Slide {{currentSlideNumber}}',

**Review by saad-mo — CHANGES_REQUESTED** [review]
some more minor updates needed

File: projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts (hunk 4 above)
Comment (saad-mo) [reply projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts]: instead of using left/right, pls use previous/next indicators to aligns with translation keys

File: projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts (hunk 5 above)
Comment (saad-mo) [reply projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts]: instead of using left/right, pls use previous/next indicators to aligns with translation keys

File: projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts (hunk 4 above)
Comment (bit172) [reply projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts]: The word 'right' here is not implying directions but rather being correct. 
I could change the word if the meaning is too ambiguous.

File: projects/assets/src/translations/en/common.ts (hunk 7 above)
Comment (saad-mo) [reply projects/assets/src/translations/en/common.ts:150]: @bit172 this is marked as resolved, but I don't need the changes. will the change be made or leave it as is?

**Review by saad-mo — APPROVED** [review]

**Review by BenjaminEmiliani — APPROVED** [review]
