### PR TITLE
fix: add custom normalizer support in organization (#9046)

### LINKED ISSUE #9046: MyOrg occ normalizers don't support adding custom ones
Currently some my org occ normalizers have a bug that will apprear when customer starts adding custom normalizers to the mix.

Currently the normalization logic is placed _inside_ `if (target === undefined)`. This condition may not be met when customers provide their own normalizers and target will be defined. Then our normalizers will be simply switched off (which is not intended).
https://github.com/SAP/spartacus/blob/ce4dab57b44f7466679c66e1307852f395aacb0d/feature-libs/my-account/organization/occ/converters/occ-user-list-normalizer.ts#L16-L30

It should be:
```typescript
if (target === undefined) {
  target = { ...(source as any) };
}
target.values = /* ... */
```

Affected files
```
feature-libs/my-account/organization/occ/converters/occ-permission-type-list.normalizer.ts
feature-libs/my-account/organization/occ/converters/occ-permission-list-normalizer.ts
feature-libs/my-account/organization/occ/converters/occ-org-unit-address-list-normalizer.ts
feature-libs/my-account/organization/occ/converters/occ-order-approval-normalizer.ts
feature-libs/my-account/organization/occ/converters/occ-order-approval-list-normalizer.ts
feature-libs/my-account/organization/occ/converters/occ-cost-center-normalizer.ts
....
```
and perhaps few more in `feature-libs/my-account/organization/occ/converters/`

related discussion: https://github.com/SAP/spartacus/pull/9028#discussion_r494608581

### PR DESCRIPTION
**Pull request by Parthlakhani**
closes #9046 

Updated following files:
```
feature-libs/organization/administration/occ/converters/occ-b2b-user-normalizer.ts
feature-libs/organization/administration/occ/converters/occ-budget-list-normalizer.ts
feature-libs/organization/administration/occ/converters/occ-permission-list-normalizer.ts
feature-libs/organization/administration/occ/converters/occ-user-group-list-normalizer.ts 
feature-libs/organization/administration/occ/converters/occ-user-list-normalizer.ts
feature-libs/organization/order-approval/occ/converters/occ-order-approval-list-normalizer.ts
feature-libs/organization/order-approval/occ/converters/occ-order-approval-normalizer.ts

### CODE REVIEW

File: feature-libs/organization/administration/occ/converters/occ-permission-type-list.normalizer.ts [hunk 1]
```diff
@@ -23,10 +23,12 @@ export class OccPermissionTypeListNormalizer
     target?: OrderApprovalPermissionType[]
   ): OrderApprovalPermissionType[] {
     if (target === undefined) {
-      target = source.orderApprovalPermissionTypes.map((permissionType) =>
-        this.converter.convert(permissionType, PERMISSION_TYPE_NORMALIZER)
-      );
+      // target = what should be here??
```
Comment (Pucek9) [inline feature-libs/organization/administration/occ/converters/occ-permission-type-list.normalizer.ts]: @Platonn

Comment (Platonn) [reply feature-libs/organization/administration/occ/converters/occ-permission-type-list.normalizer.ts]:
```ts
      target = { ...(source as any) };
```

Comment (Pucek9) [reply feature-libs/organization/administration/occ/converters/occ-permission-type-list.normalizer.ts]: still I don't see sense, in next line it will be overwritten anyway

Comment (Platonn) [reply feature-libs/organization/administration/occ/converters/occ-permission-type-list.normalizer.ts]: My bad, I didn't take next line into account and that it's conversion into array.

Agreed. Above fallback object initialization doesn't make sense in this case.

**Review by Pucek9 — DISMISSED** [review]

**Review by Pucek9 — DISMISSED** [review]

**Review by Pucek9 — APPROVED** [review]

**Review by Platonn — APPROVED** [review]
