### PR TITLE
test: Fix applied promotions e2e

### LINKED ISSUE #7384: Fix applied promotions e2e test
Lately applied-promotions again started to fail.

### PR DESCRIPTION
**Pull request by marlass**
Closes #7384

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts [hunk 1]
```diff
@@ -48,7 +48,8 @@ export function selectShippingAddress() {
     .should('not.be.empty');
   cy.get('.cx-card-title').should('contain', 'Default Shipping Address');
   cy.get('.card-header').should('contain', 'Selected');
-  cy.visit(`/checkout/delivery-mode`);
+  cy.get('button.btn-primary').click();
+  // TODO: make it more stable when JaloError happens
```
Comment (kacperknapik) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts:52]: what about this TODO?

Comment (marlass) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts:52]: Left for the future, as I don't have yet a fix for that. That's also the reason why I kept this test as a "flaky".

**Review by kacperknapik — APPROVED** [review]
