### PR TITLE
fix: add checkout step to title (#13539)

### LINKED ISSUE #13539: Page title for checkout doesn't change along with checkout steps
**Describe the bug**

- Page title stays short and generic throughout the checkout process.
- Automated test detects this

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Add product to cart
2. Start the checkout process
3. Notice the page title not changing along with checkout steps.

**Expected behavior**
- Page title for each step is meaningful. E.g. Checkout: Choose a payment method

**Screenshots**
Screen Shot 2021-08-05 at 7 13 31 PM

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #13539

### CODE REVIEW

File: projects/storefrontlib/cms-components/navigation/page-header/page-title.component.ts [hunk 1]
```diff
@@ -26,9 +28,14 @@ export class PageTitleComponent implements OnInit {
   }
 
   private setTitle(): void {
-    this.title$ = this.pageMetaService.getMeta().pipe(
-      filter(isNotNullable),
-      map((meta) => (meta.heading || meta.title) ?? '')
+    this.title$ = combineLatest([
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/cms-components/navigation/page-header/page-title.component.ts]: as mentioned, do not couple 'any checkout' logic to this 'generic' page title

File: feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts [hunk 2]
```diff
@@ -46,14 +45,8 @@ export class CheckoutPageMetaResolver
...
    */
-  resolveTitle(): Observable<string> {
-    return this.cart$.pipe(
-      switchMap((c) =>
-        this.translationService.translate('pageMetaResolver.checkout.title', {
-          count: c.totalItems,
-        })
-      )
-    );
+  resolveTitle(): Observable<string | undefined> {
```
Comment (bgambocjaviniar) [inline feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts:51]: from the first hint provided in DM, you can use resolveHeading() to change the breadcrumb title and resolveTitle will change the actual title displayed in the header and web browser

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
^

File: projects/storefrontlib/cms-components/navigation/page-header/page-title.component.ts (hunk 1 above)
Comment (bgambocjaviniar) [reply projects/storefrontlib/cms-components/navigation/page-header/page-title.component.ts]: put it back to what it was and use resolveHeading() in the checkout-page resolver --> I was hinting in our messages that this functionality existed from the hints I provided 😉 
```suggestion
     this.title$ = this.pageMetaService.getMeta().pipe(
      filter(isNotNullable),
      map((meta) => (meta.heading || meta.title) ?? '')
```

File: feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts [hunk 3]
```diff
@@ -41,19 +40,22 @@ export class CheckoutPageMetaResolver
...
    * @override
-   * Resolves the page title from the translation `pageMetaResolver.checkout.title`. The
-   * cart total item `count` is passed to the translation, so it can be used in the title.
+   * Resolves the page title for the Checkout Page to include checkout step.
+   * The page title used by the browser (history, tabs) and crawlers.
    *
    * The title from the page data is ignored for this page title.
    */
-  resolveTitle(): Observable<string> {
-    return this.cart$.pipe(
```
Comment (bgambocjaviniar) [inline feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts:50]: we can safely remove cart$ from this file as it's no longer being used nor it was even being used for a lonnngggg time apparently haha

File: feature-libs/checkout/base/core/services/checkout-page-meta.resolver.spec.ts [hunk 4]
```diff
@@ -58,14 +58,29 @@ describe('CheckoutPageMetaResolver', () => {
...
         result = meta;
       })
       .unsubscribe();
 
-    expect(result).toEqual('pageMetaResolver.checkout.title count:5');
+    expect(result).toEqual('Checkout Delivery Mode');
+  });
+
+  it('should resolve checkout heading', () => {
+    let result!: string;
```
Comment (bgambocjaviniar) [inline feature-libs/checkout/base/core/services/checkout-page-meta.resolver.spec.ts]: instead of saying it will always be a string, let's put the type as  `string | undefined`, similarly to line 59

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]

File: feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts [hunk 5]
```diff
@@ -27,8 +26,6 @@ export class CheckoutPageMetaResolver
   extends PageMetaResolver
   implements PageTitleResolver, PageDescriptionResolver, PageRobotsResolver
```
Comment (bgambocjaviniar) [inline feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts]: I missed this, but for convention on interfaces that helps to 'include' the abstract methods to be implemented, you should implement PageHeadingResolver

File: feature-libs/checkout/base/core/services/checkout-page-meta.resolver.spec.ts [hunk 6]
```diff
@@ -58,14 +58,29 @@ describe('CheckoutPageMetaResolver', () => {
   it(`should resolve page title`, () => {
     let result: string | undefined;
 
+    basePageMetaResolver.resolveTitle = createSpy().and.returnValue(
```
Comment (bgambocjaviniar) [inline feature-libs/checkout/base/core/services/checkout-page-meta.resolver.spec.ts:62]: let's include resolveTitle method under the mock class in line 23

**Review by bgambocjaviniar — APPROVED** [review]

File: feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts [hunk 7]
```diff
@@ -41,19 +43,22 @@ export class CheckoutPageMetaResolver
...
+    return this.basePageMetaResolver.resolveTitle();
+  }
+
+  /**
+   * Resolves the page heading for the Checkout Page.
+   * The page heading is used in the UI (`<h1>`), where as the page
+   * title is used by the browser and crawlers.
+   */
+  resolveHeading(): Observable<string> {
+    return this.translationService.translate('pageMetaResolver.checkout.title');
```
Comment (znikola) [inline feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts:61]: Question: aren't we "loosing" the information about the total items in the current cart (which we had before)?

---------/---------
/reply:
@znikola in terms of the logic yes, but not in terms of the application. What I mean by that is the method previously translated  'pageMetaResolver.checkout.title' and would pass totalItems of the cart as a parameter. But this key in our base application does not handle any parameters:
Screen Shot 2022-02-07 at 9 07 50 AM

And if a customer is using a custom translation key that expects the parameter, then it will be reported to them in the 5.0 md that the method no longer translates this key with a parameter
