### PR TITLE
fix: Unit/User's assignment related to new info #7034

### LINKED ISSUE #7034: Fix for Unit/User's assignment related to new info
1. Approver roles are set per unit / per user
/orgUnits/{orgUnitId}/orgCustomers/{orgCustomerId}/roles
2. Other 3 roles are set per user (not tied per unit)
/orgCustomers/{orgCustomerId}/roles/{roleId}

### PR DESCRIPTION
**Pull request by Pucek9**
Closes #7034

### CODE REVIEW

File: projects/core/src/occ/adapters/organization/default-occ-organization-config.ts [hunk 1]
```diff
@@ -14,10 +14,14 @@ export const defaultOccOrganizationConfig: OccConfig = {
         orgUnit: '/users/${userId}/orgUnits/${orgUnitId}',
         orgUnitUsers:
           '/users/${userId}/orgUnits/${orgUnitId}/availableUsers/${roleId}',
-        orgUnitUserRoles:
+        orgUnitApprovers:
           '/users/${userId}/orgUnits/${orgUnitId}/orgCustomers/${orgCustomerId}/roles',
```
Comment (mszczepaniak) [inline projects/core/src/occ/adapters/organization/default-occ-organization-config.ts:18]: is this a correct url for the approvers?

**Review by mszczepaniak — APPROVED** [review]

File: projects/core/src/occ/adapters/organization/default-occ-organization-config.ts (hunk 1 above)
Comment (Pucek9) [reply projects/core/src/occ/adapters/organization/default-occ-organization-config.ts:18]: yeah, look for issue description
