### PR TITLE
fix missing _target on anchor links

### LINKED ISSUE #9948: Navigation Node CMSLinkComponents do not render style classes
**Describe the bug**
When adding a style class within the CMSLinkComponent of a navigation node, the class does not get rendered.

**Tell us the version of Spartacus**
3.0.0-next.3

**To Reproduce**
1. Go to smartedit on e.g. the Electronics Spartacus Demo Instance
2. Click on Navigation Management
3. Edit a Category Navigation node of the first level category navigation
4. Edit the Navigation Node Entry
5. Edit the CMSLinkComponent
6. Add a custom Class to the `Style Classes` field
7. Save and sync the catalogue
8. Open the storefront

**Expected behavior**
The link of the respective navigation node contains the custom class

**Screenshots**
CMS Link Component Dialog:
image

Navigation UI Component Template:
image

Component json Request:
image

Link rendered in the Frontend:
image

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
It seems, that the class get sent within the compoent json request but then it is not passed to the generic-link component in the component template markup. By the way, the same (wrong?) behaviour happens for the "Open In External Window" option, which also just get's ignored (not set in the code and not working).

There seems to be a general discrepancy between the CMSLinkComponent and the Generic-Link (which is used on a lot of places) regarding their data model..

### PR DESCRIPTION
**Pull request by tobi-or-not-tobi**
fixes #9948

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/content/link/link.component.ts [hunk 1]
```diff
@@ -9,4 +9,14 @@ import { CmsComponentData } from '../../../cms-structure/page/model/cms-componen
 })
 export class LinkComponent {
   constructor(public component: CmsComponentData<CmsLinkComponent>) {}
+
+  /**
+   * Returns `_blank` to force opening the link in a new window whenever the
+   * `data.target` flag is set to rue.
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/src/cms-components/content/link/link.component.ts]: small typo `rue` instead of `true`

File: projects/storefrontlib/src/cms-components/content/link/link.component.ts [hunk 2]
```diff
@@ -9,4 +9,14 @@ import { CmsComponentData } from '../../../cms-structure/page/model/cms-componen
...
+   */
+  getTarget(data: CmsLinkComponent): string | null {
+    return data.target === 'true' || ((data.target as any) as Boolean) === true
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/src/cms-components/content/link/link.component.ts]: we can drop as any or as Boolean, but not have both. Or, drop both and have it similarly to `navigation.service`, where none of the above was provided

what do you think?

File: projects/storefrontlib/src/cms-components/content/banner/banner.component.html [hunk 3]
```diff
@@ -1,7 +1,7 @@
 <ng-container *ngIf="component.data$ | async as data">
   <cx-generic-link
     [url]="data.urlLink"
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/src/cms-components/content/banner/banner.component.html]: now I'm wondering since banner component supports external, should we include [attr.class]=class to support `styleclasses` from the BannerComponent CMS property? (May be out of scope)

What do you think?

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
small tweaks

File: projects/storefrontlib/src/cms-components/content/link/link.component.ts (hunk 2 above)
Comment (tobi-or-not-tobi) [reply projects/storefrontlib/src/cms-components/content/link/link.component.ts]: much better

File: projects/storefrontlib/src/cms-components/content/banner/banner.component.html (hunk 3 above)
Comment (tobi-or-not-tobi) [reply projects/storefrontlib/src/cms-components/content/banner/banner.component.html]: done ;)

**Comment by bgambocjaviniar** [comment]
works as intended and doesn't break any e2es https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/464/console

**Review by bgambocjaviniar — DISMISSED** [review]
LGTM and works as intended and doesn't break any e2es https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/464/console

**Review by dunqan — DISMISSED** [review]

**Review by dunqan — APPROVED** [review]
