### PR TITLE
fix: b2b checkout cost center not saved when going back

### LINKED ISSUE #9155: b2b checkout cost center not kept when going back
**Describe the bug**
When doing a b2b checkout using an account the selected cost center is not kept if you go back.

**To Reproduce**
1. Start b2b checkout, select account payment
2. Choose a cost center
3. Go to review step
4. Go back to shipping address step, the cost center is now the first one in the list

**Expected behavior**
The selected cost center and shipping address should be the one selected before

### PR DESCRIPTION
**Pull request by LTiger14**
Closes #9155

### CODE REVIEW

File: projects/core/src/occ/adapters/cost-center/default-occ-cost-centers-config.ts [hunk 1]
```diff
@@ -4,7 +4,8 @@ export const defaultOccCostCentersConfig: OccConfig = {
   backend: {
     occ: {
       endpoints: {
-        costCenters: '/costcenters',
+        getActiveCostCenters:
+          '/costcenters?fields=DEFAULT,unit(BASIC,addresses(DEFAULT))',
```
Comment (bgambocjaviniar) [inline projects/core/src/occ/adapters/cost-center/default-occ-cost-centers-config.ts:8]: 🔥

**Review by bgambocjaviniar — APPROVED** [review]
LGTM 👍 

also QA passes
1 -  **b2b - cost center is saved when going back from delivery mode** 
----> with 1 address and 1 cost center
----> with 1 address and many diff cost centers
----> with many addresses and 1 cost center
----> with many addresses and multiple cost centers
2 - b2b (able to checkout) and b2c (able to checkout)
3 - all b2e e2e passes

**Review by znikola — APPROVED** [review]
