### PR TITLE
fix: redisplay first thumbnail of Image Zoom by click (#14119)

### LINKED ISSUE #14119: Image Zoom: Image of first thumbnail is not displayed
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 0.62.192.238

**Steps to Reproduce**
Go to electronics storefront
Go to pdp of this product: 1934793
Click on "Expand Image"
Click on each thumbnail but you need to click on all of them (1st, 2nd, 3rd, 4th). You can also use arrows. 
Click on the 1st thumbnail again.

**Actual Result**
The first thumbnail image is not displayed. You can only display the first thumbnail using the arrows.

Screen Shot 2021-10-26 at 3 01 43 PM

**Expected Result**
Should display the image of the first thumbnail

**Note**
It looks even more obvious with products that have only 2 thumbnails, for eg: 1325806

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes: #14119

### CODE REVIEW

**Review by mszczepaniak — APPROVED** [review]

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-thumbnails/product-image-zoom-thumbnails.component.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export class ProductImageZoomThumbnailsComponent {
 
   openImage(image: ImageGroup): void {
     this.mainMediaContainer.next(image);
-    if (image.zoom?.galleryIndex) {
+    if (typeof image.zoom?.galleryIndex === 'number') {
```
Comment (mszczepaniak) [inline feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-thumbnails/product-image-zoom-thumbnails.component.ts:31]: Good catch @BenjaminEmiliani !
