### PR TITLE
fix: fix store-finder-list-item link to use routerLink instead of href #7304

### LINKED ISSUE #7304: Fix store-finder-list-item link to use routerLink instead of href

### PR DESCRIPTION
**Pull request by Pucek9**
Closes #7304

It's draft because of missing update schematics / migration guide - will be done after acceptance

### CODE REVIEW

**Review by Matejk00 — DISMISSED** [review]

File: projects/schematics/src/migrations/2_0/constructor-deprecations/constructor-deprecation-data.ts [hunk 1]
```diff
@@ -65,6 +65,10 @@ import { USER_ORDER_SERVICE_MIGRATION } from './data/user-order.service.migratio
 import { USER_PAYMENT_SERVICE_MIGRATION } from './data/user-payment.service.migration';
 import { USER_SERVICE_MIGRATION } from './data/user.service.migration';
 import { STORE_FINDER_SEARCH_RESULT_COMPONENT_MIGRATION } from './data/store-finder-search-result.component.migration';
+import { CART_ITEM_COMPONENT_MIGRATIONS } from './data/cart-item.component.migration';
```
Comment (marlass) [inline projects/schematics/src/migrations/2_0/constructor-deprecations/constructor-deprecation-data.ts]: Merge conflict leftover?

**Review by marlass — CHANGES_REQUESTED** [review]

**Review by marlass — APPROVED** [review]
