### PR TITLE
fix opening hours for other languages

### LINKED ISSUE #10302: Store Finder Opening Hours to not correctly work when switching language / being shown for Languages other than English
**Describe the bug**
Switching the language via Language Switch does not change the Store Finder Store Opening Hours. Additionally, Store Finder Hours are not displayed for other languages than English.

**Tell us the version of Spartacus**
- Library version: 3.0.0-rc.1

**To Reproduce**
1. Go to https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/de/USD/store-finder/country/BE/sap-brussels-education-center-office
2. Look at the Opening Hours of the store, they are correctly formatted times in AM / PM format
3. Click on the language selector in the header and Choose "Deutsch" (German) as Language
4. Look again at the opening Hours of the store, which did not change to German Time format after changing the language
5. Do a full page reload
6. Look again at the opening Hours of the store, which are not displayed anymore at all

**Expected behavior**
- Switching the Language via Language Selector updates the values on the page, which are language / locale based without a Page reload (In this case the Opening Hours of the Store) (or if that's not possible, trigger a full reload)
- Visiting the Store Detail Page shows the Opening Hours correctly formatted for other languages than English (Does not work for any other languages than english on the demo instance currently)

**Screenshots**
Store Hours for Language English:
image

Empty Store Hours for Language German (Or any other language than english):
image

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

### PR DESCRIPTION
**Pull request by Parthlakhani**
closes #10302 

Fix opening and closing hours for all languages

### CODE REVIEW

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts [hunk 1]
```diff
@@ -1,16 +1,17 @@
...
-import { StoreFinderService } from '@spartacus/storefinder/core';
+import { combineLatest, Observable, Subscription } from 'rxjs';
+import {
+  FindStoresState,
+  StoreFinderService,
+} from '@spartacus/storefinder/core';
 
 @Component({
   selector: 'cx-store-finder-grid',
   templateUrl: './store-finder-grid.component.html',
```
Comment (tobi-or-not-tobi) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts:9]: while you're at it, could you add the on push change detection?

File: feature-libs/storefinder/core/store/selectors/find-stores.selectors.ts [hunk 2]
```diff
@@ -28,3 +28,10 @@ export const getStoresLoading: MemoizedSelector<
 > = createSelector(getFindStoresState, (state) =>
   StateUtils.loaderLoadingSelector(state)
 );
+
+export const getStoresSucess: MemoizedSelector<
```
Comment (tobi-or-not-tobi) [inline feature-libs/storefinder/core/store/selectors/find-stores.selectors.ts]: typo. 

if you have not already, you might want to use https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

File: feature-libs/storefinder/components/store-finder-store/store-finder-store.component.ts [hunk 3]
```diff
@@ -23,11 +24,19 @@ export class StoreFinderStoreComponent implements OnInit {
     private routingService: RoutingService
   ) {}
 
+  loadData: Subscription = combineLatest([
```
Comment (tobi-or-not-tobi) [inline feature-libs/storefinder/components/store-finder-store/store-finder-store.component.ts]: I'd prefer to keep the component as clean as possible; we like to have the load/reload logic inside the facade layer or even lower if possible. You might want to look at other services where we've done similar things.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts [hunk 4]
```diff
@@ -20,11 +21,24 @@ export class StoreFinderGridComponent implements OnInit, OnDestroy {
     private route: ActivatedRoute
   ) {}
 
+  isLoading$: Observable<boolean> = this.storeFinderService.getStoresLoading();
+  locations$: Observable<
+    FindStoresState
+  > = this.storeFinderService.getFindStoresEntities();
+  isLoaded$: Observable<boolean> = this.storeFinderService.getStoresLoaded();
+  loadData: Subscription = combineLatest([
```
Comment (tobi-or-not-tobi) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts]: See my note regarding clean components at store-finder-store.component.ts

**Review by tobi-or-not-tobi — CHANGES_REQUESTED** [review]

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts (hunk 1 above)
Comment (tobi-or-not-tobi) [reply feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts:9]: I believe this is still missing

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts [hunk 5]
```diff
@@ -19,12 +18,19 @@ export class StoreFinderGridComponent implements OnInit, OnDestroy {
...
-    this.locations$ = this.storeFinderService.getViewAllStoresEntities();
     this.defaultLocation = {};
+    this.isLoading$ = this.storeFinderService.getViewAllStoresLoading();
+    this.locations$ = this.storeFinderService
+      .getFindStoresEntities()
+      .pipe(map((data) => data.findStoresEntities));
+    this.findStores();
+  }
 
+  findStores() {
```
Comment (tobi-or-not-tobi) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts]: can you make this non-public, protected preferred.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 6]
```diff
@@ -28,7 +29,34 @@ export class StoreFinderService {
     protected winRef: WindowRef,
     protected globalMessageService: GlobalMessageService,
     protected routingService: RoutingService
-  ) {}
+  ) {
+    combineLatest([
```
Comment (tobi-or-not-tobi) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: We do not like to implement logic inside the constructor, as it blocks customisations in case one would extend this class. You could move the logic to a protected method, and call it from the constructor. The method can be further customised if needed.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 7]
```diff
@@ -28,7 +29,34 @@ export class StoreFinderService {
...
+      this.getStoresLoading(),
+      this.getStoresLoaded(),
+      this.getFindStoresEntities(),
+      this.routingService.getParams(),
+    ]).subscribe(([loading, loaded, value, params]) => {
```
Comment (tobi-or-not-tobi) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: if a subscribe is needed we must clean up the subscription, this is mainly because of leaking memory in an SSR process. You can implement the onDestroy lifecycle hook in the service. 

Ideally we don't have services that require explicit subscriptions. In this specific example it means that we're subscribing as soon as the service got initialised. That might not be the time that it's actually needed. We rather subscribe when the component explicitly requires this. You might be able to operate on the `getFindStoresEntities` observable that is returned to achieve the same. Tbh i've not looked into the details here.

**Review by tobi-or-not-tobi — DISMISSED** [review]

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 8]
```diff
@@ -186,4 +165,47 @@ export class StoreFinderService {
...
+          )
+        )
+        .subscribe(([value, loading, loaded, params]) => {
+          if (!loading && !loaded) {
+            if (
+              this.isEmpty(value.findStoresEntities) &&
+              params.country &&
+              !params.store
+            ) {
+              this.findStoresAction(
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: You could create a function for this since it's the same as what is in the grid component.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 9]
```diff
@@ -186,4 +165,47 @@ export class StoreFinderService {
...
+          withLatestFrom(
+            this.getStoresLoading(),
+            this.getStoresLoaded(),
+            this.routingService.getParams()
+          )
+        )
+        .subscribe(([value, loading, loaded, params]) => {
+          if (!loading && !loaded) {
+            if (
+              this.isEmpty(value.findStoresEntities) &&
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: Do you need this since you filter at the top?

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 10]
```diff
@@ -186,4 +165,47 @@ export class StoreFinderService {
...
+              this.isEmpty(data.findStoresEntities) &&
+              this.isEmpty(data.findStoreEntitiesById)
+          ),
+          withLatestFrom(
+            this.getStoresLoading(),
+            this.getStoresLoaded(),
+            this.routingService.getParams()
+          )
+        )
+        .subscribe(([value, loading, loaded, params]) => {
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: I'd rename `value` as it's not very descriptive. Maybe also `params`.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 11]
```diff
@@ -186,4 +165,47 @@ export class StoreFinderService {
       !store || (typeof store === 'object' && Object.keys(store).length === 0)
     );
   }
+
+  protected initialize() {
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: I would rename this so it's more descriptive and add a JS-doc comment to describe what the function does.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts [hunk 12]
```diff
@@ -30,7 +31,7 @@ export class StoreFinderGridComponent implements OnInit {
     this.findStores();
   }
 
-  findStores() {
+  protected findStores() {
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts]: While this is good, I wouldn't do it because of the breaking change.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts [hunk 13]
```diff
@@ -62,14 +77,16 @@ describe('StoreFinderGridComponent', () => {
   beforeEach(() => {
     fixture = TestBed.createComponent(StoreFinderGridComponent);
     component = fixture.componentInstance;
+    StoreFinderGridComponent.prototype.ngOnInit = () => {};
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts]: Why are you doing this?

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts [hunk 14]
```diff
@@ -90,4 +107,13 @@ describe('StoreFinderGridComponent', () => {
 
     expect(component).toBeTruthy();
   });
+
+  it('should call findStores on language change', () => {
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts]: This component is not responsible for this any more right?

File: feature-libs/storefinder/components/store-finder-map/store-finder-map.component.ts [hunk 15]
```diff
@@ -25,7 +25,14 @@ export class StoreFinderMapComponent implements OnChanges {
   constructor(private googleMapRendererService: GoogleMapRendererService) {}
 
   ngOnChanges(changes: SimpleChanges): void {
-    if (changes.locations && this.locations) {
+    if (
+      Object.entries(
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-map/store-finder-map.component.ts]: Couldn't you add a validation in the store-data service? I think it would be simpler.

File: feature-libs/storefinder/core/store/reducers/view-all-stores.reducer.ts [hunk 16]
```diff
@@ -5,7 +5,7 @@ export const initialState: ViewAllStoresState = {
   viewAllStoresEntities: {},
 };
 
-export function reducer(
+export function viewAllStoresReducer(
```
Comment (LTiger14) [inline feature-libs/storefinder/core/store/reducers/view-all-stores.reducer.ts:8]: Please update the unit test with this change.

File: feature-libs/storefinder/core/store/reducers/find-stores.reducer.ts [hunk 17]
```diff
@@ -3,19 +3,24 @@ import { FindStoresState } from '../store-finder-state';
 
 export const initialState: FindStoresState = {
   findStoresEntities: {},
+  findStoreEntitiesById: {},
 };
 
-export function reducer(
+export function findStoresReducer(
```
Comment (LTiger14) [inline feature-libs/storefinder/core/store/reducers/find-stores.reducer.ts:8]: Please update the unit test for this reducer.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 18]
```diff
@@ -145,4 +159,53 @@ export class StoreFinderService {
     }
     this.store.dispatch(callbackAction);
   }
+
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts:185]: Please add a test case for these changes. (all of them 😉 )

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 19]
```diff
@@ -16,19 +16,26 @@ import {
...
   private geolocationWatchId: number = null;
+  protected subscription = new Subscription();
 
   constructor(
     protected store: Store<StateWithStoreFinder>,
     protected winRef: WindowRef,
     protected globalMessageService: GlobalMessageService,
-    protected routingService: RoutingService
-  ) {}
+    protected routingService: RoutingService,
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts:53]: You will need to add a constructor deprecation for this.

**Review by LTiger14 — CHANGES_REQUESTED** [review]

File: feature-libs/storefinder/core/facade/store-finder.service.ts (hunk 9 above)
Comment (Parthlakhani) [reply feature-libs/storefinder/core/facade/store-finder.service.ts]: no, I can remove it.

File: feature-libs/storefinder/core/facade/store-finder.service.ts (hunk 10 above)
Comment (Parthlakhani) [reply feature-libs/storefinder/core/facade/store-finder.service.ts]: `Value` is not needed anymore since I removed the condition.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts (hunk 12 above)
Comment (Parthlakhani) [reply feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts]: as discussed, leaving this `protected` as the method is new.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts (hunk 13 above)
Comment (Parthlakhani) [reply feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts]: It was for the test case `should call findStores on language change`, to avoid calling the method on `ngOnInit`
I will remove this.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts (hunk 14 above)
Comment (Parthlakhani) [reply feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts]: yes, I will remove it.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts [hunk 20]
```diff
@@ -1,41 +1,39 @@
...
-    this.locations$ = this.storeFinderService.getViewAllStoresEntities();
+    this.isLoading$ = this.storeFinderService.getStoresLoading();
+    this.locations$ = this.storeFinderService
+      .getFindStoresEntities()
+      .pipe(map((data) => data.findStoresEntities));
     this.defaultLocation = {};
+    this.findStores();
+  }
 
+  protected findStores() {
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts]: Forgot to mention it before. As a general rule always add an explicit return type, even if just `void` like this case.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts [hunk 21]
```diff
@@ -20,16 +20,22 @@ class MockStoreFinderListItemComponent {
...
   snapshot: {
     params: {},
   },
 };
 
 const mockStoreFinderService = {
-  getViewAllStoresEntities: jasmine.createSpy().and.returnValue(of(Observable)),
-  getViewAllStoresLoading: jasmine.createSpy(),
-  findStoresAction: jasmine.createSpy().and.returnValue(of(Observable)),
+  getFindStoresEntities: jasmine.createSpy().and.returnValue(of(Observable)),
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts]: Just to be cleaner you could do `import createSpy = jasmine.createSpy;` and just use `createSpy()`. You can check `user-details.component.spec.ts` to see what I mean.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts [hunk 22]
```diff
@@ -20,16 +20,22 @@ class MockStoreFinderListItemComponent {
   location;
 }
 
+class MockTranslationService {
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts]: Starting recently when creating a mock we want to use `implements Partial<...>` so that it's easier to make the changes when the base class is modified. You can cgeck this to see what I mean https://sap.github.io/spartacus-docs/type-safety-in-spartacus#partial-usage-for-service-or-component-mocks

File: feature-libs/storefinder/components/store-finder-store/store-finder-store.component.spec.ts [hunk 23]
```diff
@@ -8,15 +8,22 @@ import {
...
 import { ActivatedRoute } from '@angular/router';
 import { StoreFinderService } from '@spartacus/storefinder/core';
 
-const mockStoreFinderService = {
-  getStoresLoading: jasmine.createSpy(),
-  getFindStoresEntities: jasmine.createSpy().and.returnValue(of(Observable)),
-  viewStoreById: jasmine.createSpy().and.returnValue(of(Observable)),
-};
+const isLoading$: BehaviorSubject<Boolean> = new BehaviorSubject(true);
+const isLoaded$: BehaviorSubject<Boolean> = new BehaviorSubject(true);
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-store/store-finder-store.component.spec.ts]: If you don't actually do a `isLoaded$.next(...)` to test the behavior with a different value you don't need the `BehaviorSubject` you can just return `of(true)`.

Also in unit tests it's generally better to use `Subject` rather than `BehaviorSubject`. Basically `Subject` don't keep the value unless there is a subscription, this means you eliminate the risk for one test having an impact on the other.

File: feature-libs/storefinder/components/store-finder-store/store-finder-store.component.spec.ts [hunk 24]
```diff
@@ -8,15 +8,22 @@ import {
...
+class MockStoreFinderService {
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-store/store-finder-store.component.spec.ts]: Please use `Partial` (see store-finder-grid)

File: feature-libs/storefinder/components/store-finder-stores-count/store-finder-stores-count.component.spec.ts [hunk 25]
```diff
@@ -4,10 +4,11 @@ import { I18nTestingModule } from '@spartacus/core';
 import { StoreFinderStoresCountComponent } from './store-finder-stores-count.component';
 import { SpinnerModule } from '@spartacus/storefront';
 import { StoreFinderService } from '@spartacus/storefinder/core';
+import { Observable, of } from 'rxjs';
 
 const mockStoreFinderService = {
   viewAllStores: jasmine.createSpy(),
-  getViewAllStoresEntities: jasmine.createSpy(),
+  getViewAllStoresEntities: jasmine.createSpy().and.returnValue(of(Observable)),
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-stores-count/store-finder-stores-count.component.spec.ts]: See `store-finder-grid`

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 26]
```diff
@@ -145,4 +182,56 @@ export class StoreFinderService {
...
+            }
+            if (routeParams.store) {
+              this.viewStoreById(routeParams.store);
+            }
+          }
+        });
+    }
+  }
+
+  callFindStoresAction(routeParams) {
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: Please add type for parameter and return type.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 27]
```diff
@@ -145,4 +182,56 @@ export class StoreFinderService {
...
+  private isEmpty(store: StoreEntities): boolean {
+    return (
+      !store || (typeof store === 'object' && Object.keys(store).length === 0)
+    );
+  }
+
+  /**
+   * Reload store data when store entities are empty because of the context change
+   */
+  protected reloadStoreEntitiesOnContextChange() {
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: Please add return type.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 28]
```diff
@@ -145,4 +182,56 @@ export class StoreFinderService {
...
+    if (isPlatformBrowser(this.platformId)) {
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts]: Since `platformId` is optional a customer extending this service might not have it provided. Could you format the if in a way it's true if -> the platform is browser (funciton return true) or if platformId is null/undefined.

File: feature-libs/storefinder/core/facade/store-finder.service.ts [hunk 29]
```diff
@@ -145,4 +182,56 @@ export class StoreFinderService {
...
+      this.subscription = this.getFindStoresEntities()
+        .pipe(
+          filter(
+            (data) =>
+              this.isEmpty(data.findStoresEntities) &&
+              this.isEmpty(data.findStoreEntitiesById)
+          ),
+          withLatestFrom(
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.ts:200]: This function is starting to look really good 👍 Could we just try this too see if it would work https://sap.github.io/spartacus-docs/events-and-subscriptions/ ? Basically moving the `withLatestFrom` to a `switchMap`.

File: feature-libs/storefinder/core/facade/store-finder.service.spec.ts [hunk 30]
```diff
@@ -13,13 +19,21 @@ import {
...
   WindowRef,
 } from '@spartacus/core';
+import { BehaviorSubject, EMPTY, of } from 'rxjs';
+import { StoreFinderSelectors } from '../store';
+
+const routerParam$: BehaviorSubject<{
+  [key: string]: string;
+}> = new BehaviorSubject({});
 
 class MockRoutingService {
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.spec.ts]: While you are here you can add the partial 😉

File: feature-libs/storefinder/core/facade/store-finder.service.spec.ts [hunk 31]
```diff
@@ -55,12 +70,41 @@ describe('StoreFinderService', () => {
...
+    findStoreEntitiesById: { pointOfServices: [] },
+    findStoresEntities: { pointOfServices: [] },
+  };
+  const storeLoading$: BehaviorSubject<boolean> = new BehaviorSubject(true);
+  const storeLoaded$: BehaviorSubject<boolean> = new BehaviorSubject(true);
+  const storeEntities$: BehaviorSubject<FindStoresState> = new BehaviorSubject(
+    mockStoreEntities
+  );
+
+  const mockSelect = (
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-finder.service.spec.ts:82]: Good stuff 👍

File: feature-libs/storefinder/core/store/actions/view-all-stores.action.spec.ts [hunk 32]
```diff
@@ -40,3 +40,11 @@ describe('View All Stores Actions', () => {
     });
   });
 });
```
Comment (LTiger14) [inline feature-libs/storefinder/core/store/actions/view-all-stores.action.spec.ts]: You can just put in the parent describe

File: feature-libs/storefinder/core/store/selectors/find-stores.selectors.spec.ts [hunk 33]
```diff
@@ -56,4 +55,21 @@ describe('FindStores Selectors', () => {
       expect(result).toEqual(true);
     });
   });
+
+  describe('getStoresSucess', () => {
```
Comment (LTiger14) [inline feature-libs/storefinder/core/store/selectors/find-stores.selectors.spec.ts]: Small typo `getStoresSucess`

**Review by LTiger14 — CHANGES_REQUESTED** [review]

File: feature-libs/storefinder/components/store-finder-store/store-finder-store.component.spec.ts (hunk 23 above)
Comment (Parthlakhani) [reply feature-libs/storefinder/components/store-finder-store/store-finder-store.component.spec.ts]: This was used by the previous test case that I removed, no need to use BehaviourSubject. I will remove it.

File: package.json [hunk 34]
```diff
@@ -41,7 +41,7 @@
     "lint:styles": "stylelint \"{projects,feature-libs}/**/*.scss\"",
     "prettier": "prettier --config ./.prettierrc --list-different \"{projects,feature-libs,core-libs,integration-libs}/**/*{.ts,.js,.json,.scss,.html}\"",
     "prettier:fix": "prettier --config ./.prettierrc --list-different \"{projects,feature-libs,core-libs,integration-libs}/**/*{.ts,.js,.json,.scss,.html}\" --write",
-    "start": "env-cmd -e ci,b2c,$SPA_ENV ng serve",
+    "start": "env-cmd -e ci,b2b,$SPA_ENV ng serve",
```
Comment (LTiger14) [inline package.json]: why did you change this?

Comment (Parthlakhani) [reply package.json]: Sorry, that was by mistake. I was running b2b for another ticket. I will change

File: feature-libs/storefinder/core/store/store-finder-state.ts [hunk 35]
```diff
@@ -15,6 +15,7 @@ export interface StoresState {
 
 export interface FindStoresState {
   findStoresEntities: StoreEntities;
+  findStoreEntitiesById: StoreEntities;
```
Comment (LTiger14) [inline feature-libs/storefinder/core/store/store-finder-state.ts]: Even though this is better but breaking changes let's not to it. Create a ticket to do it for 4.0.

Comment (LTiger14) [reply feature-libs/storefinder/core/store/store-finder-state.ts]: Also remove all uses of it.

File: feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts [hunk 36]
```diff
@@ -1,41 +1,39 @@
...
     private route: ActivatedRoute
   ) {}
 
   ngOnInit() {
-    this.isLoading$ = this.storeFinderService.getViewAllStoresLoading();
-    this.locations$ = this.storeFinderService.getViewAllStoresEntities();
+    this.isLoading$ = this.storeFinderService.getStoresLoading();
+    this.locations$ = this.storeFinderService
+      .getFindStoresEntities()
+      .pipe(map((data) => data.findStoresEntities));
```
Comment (LTiger14) [inline feature-libs/storefinder/components/store-finder-grid/store-finder-grid.component.ts]: I'm adding it here because I can't place it in the service. 

- ALL of the methods that now need a map **should** return **exactly** the same thing that they did before. So add the `map` in there.
- Deprecate those methods for 4.0 -> say they will return the entities rather than data.
- Create new methods that do the same thing but are not called entities since technically they return the data.

**Review by LTiger14 — CHANGES_REQUESTED** [review]

**Review by LTiger14 — DISMISSED** [review]

**Review by LTiger14 — APPROVED** [review]
