### PR TITLE
fix: Input types on DateTimePicker

### LINKED ISSUE #9333: Can't create a budget on Firefox [due to date/time picker?]
**Describe the bug**
On Firefox the date pickers are inputs, inputting any value in these inputs gives many errors in the console and the budget cannot be created.

**To Reproduce**
1. On Firefox
2. Login as Administrator
3. Go to my-company -> budgets
4. Click "Add"
5. Fill form with the console open

**Expected behavior**
I can add a budget on Firefox

**Screenshots**
image
image
Screen Shot 2020-10-14 at 12 36 40 PM

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Firefox 82

### PR DESCRIPTION
**Pull request by Zeyber**
Closes: #9333

### CODE REVIEW

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts [hunk 1]
```diff
@@ -41,6 +44,9 @@ export class OccReplenishmentOrderFormSerializer
       hour12: false,
     });
     const modelDate = `${date}T${localTime}`;
-    return this.dateTimePickerFormatterService.toModel(modelDate);
+    return this.dateTimePickerFormatterService.toModel(
+      modelDate,
+      DATETIME_PICKER_INPUT_TYPE.DATETIME_LOCAL
```
Comment (Platonn) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]: No need to fix it in this PR:

The `core` serializer shouln't know about the `<input>` type that was used in the UI (or even the whole UI-related formatter service). Ideally the UI implementation details stay in the UI (storefront) library.

I'll create a separate ticket for it.

File: projects/storefrontlib/src/shared/components/date-time-picker/date-time-picker.component.ts [hunk 2]
```diff
@@ -39,11 +42,19 @@ export class DateTimePickerComponent
...
   @ViewChild('inputElement', { static: false, read: ElementRef })
   input: ElementRef;
 
+  /**
+   * Type attribute on input element to manipulate datetime-like value.
+   * Defaults to 'datetime-local'.
+   */
+  @Input()
+  inputType?: DATETIME_PICKER_INPUT_TYPE =
+    DATETIME_PICKER_INPUT_TYPE.DATETIME_LOCAL;
```
Comment (Platonn) [inline projects/storefrontlib/src/shared/components/date-time-picker/date-time-picker.component.ts]: According to caniuse.com, input type `datetime-local` is not supported in Firefox. I guess that changing it to `'date'` in the templates was aiming to fix the Firefox issue. 
image

That said, introducing in the `date-time-picker.component` the `inputType` with value `'date'` has several drawbacks:
- Mostly, the user of the datetime picker component should be able to set not only about date, but also time and timezone. How does input type `'date'` could handle them?
- IMO it looks a bit unintuitive that `date-time-picker.component` can have input type `'date'`. It feels like we should use other existing component instead: `date-picker.component`. Looks confusing. That said, if we had only one component, I like to have one component for date and date-time configured by input. But it's not the case now. So let's keep them independent.
- Spartacus supports all evergreen browsers. Since `datetime-local` is not supported by one of them (Firefox), we should not use it. OR we should use it, but (somehow) provide automatic fallback to 2 adjacent inputs: date + time (when datetime-local is not supported). Alternatively, for simplicity, we can just have 2 adjacent inputs date + time by default (for all browsers) - which in case of tight release deadline is a way to go IMO.

Regardless, all the implementation details of the component should be encapsulated in it (or it's counterpart formatter service). Other layers or parent components ideally shouldn't know about any peculiarities
 of the native implementation. They should just get/set the value in a common format.

What are your thoughts?

**Review by Platonn — COMMENTED** [review]
left some comments

File: projects/storefrontlib/src/shared/components/date-time-picker/date-time-picker.component.ts (hunk 2 above)
Comment (Zeyber) [reply projects/storefrontlib/src/shared/components/date-time-picker/date-time-picker.component.ts]: Yup that's correct for the change to 'date' whilst still having the ability to use the original 'datetime-local' type. I believe that keeping all these date/time controls in one component makes sense in that they all accomplish a similar task and use similar parameters (eg. min/max). 

A fallback mechanism would be ideal but given that this will take more time to implement, we should just use the 'date' type with the 'datetime-local' type there as an option and in the future, we can use the better 'datetime-local' by default with the fallback depending on system/browser support.

We should drop the date-picker component completely as we are not using it anywhere. I'm not sure if we even fully tested it in the end. Its obsolete to the date-time-picker.

Given restrictions of the backend (timezone info missing) and minimum requirements outlined by Bill in the issue, we only need to use date in the budget. Having also time was a workaround for not being able to have the timezone but we agreed just to have date in the ui instead and the time offset would be set by the user's local midnight (more user friendly approach as time is not that important).

Comment (Platonn) [reply projects/storefrontlib/src/shared/components/date-time-picker/date-time-picker.component.ts]: As Bill agreed to use only date for the budget, I'm in favour of using simple `<cx-date-picker>` component for it (which inside uses native `<input type="date">`. 

As `datetime-local` is not supported by all evergreen browsers, IMO we should drop usage of it at all (unless we provide automatic fallback). It's My bad, I didn't notice that a couple of weeks ago when I reviewed the initial datetime picker implementation... 🙏 

Therefore we shouldn't release `<cx-date-time-picker>` in it's current state, becuase Spartacus should support all evergreen browsers by default. So I'd suggest hiding this component for now from the public API before 3.0 (and his counterpart formatter service) and add code comment that we should not use this component yet until ticket XXX is done. Then let's create ticket XXX for implementing a stable (working on all browsers) date-time-picker that we could use in other features in future (when needed). That's more complex topic, and not urgent, so ticket implementation can be postponed to 3.x. 

Side note: The occ Scheduled replenishment serializer already uses the `DateTimePickerFormatterService`, but as discussed offline with @bgambocjaviniar , we should drop dependency on the formatter service in the serializer, and rather use only `getLocalTimezoneOffset()` util function.

File: feature-libs/organization/administration/core/connectors/budget/budget.adapter.ts [hunk 3]
```diff
@@ -1,6 +1,5 @@
-import { EntitiesModel, SearchConfig } from '@spartacus/core';
+import { Budget, EntitiesModel, SearchConfig } from '@spartacus/core';
 import { Observable } from 'rxjs';
-import { Budget } from '../../model/budget.model';
```
Comment (Platonn) [inline feature-libs/organization/administration/core/connectors/budget/budget.adapter.ts]: Budget model is already in the organization lib. Why need such change?

What's the reason of adding Budget interface to `augmented-core.model.ts`?

File: feature-libs/organization/administration/occ/adapters/occ-budget.adapter.ts [hunk 4]
```diff
@@ -49,6 +51,7 @@ export class OccBudgetAdapter implements BudgetAdapter {
     budgetCode: string,
     budget: Budget
   ): Observable<Budget> {
+    budget = this.converter.convert(budget, BUDGET_SERIALIZER) as Budget;
```
Comment (Platonn) [inline feature-libs/organization/administration/occ/adapters/occ-budget.adapter.ts]: Why need to cast `as Budget`?

File: projects/core/src/util/time-utils.ts [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+    callback();
+    Date.prototype.toLocaleTimeString = original;
+  }
+
+  static fakeDateTimezoneOffset(offset: number, callback: Function): any {
+    const original = Date.prototype.getTimezoneOffset;
+    Date.prototype.getTimezoneOffset = () => offset;
+    callback();
+    Date.prototype.getTimezoneOffset = original;
+  }
```
Comment (Platonn) [inline projects/core/src/util/time-utils.ts]: It would be good to extract those testing utils to separate place, i.e. `time-testing-utils`. They should not be bundled in the production code, but used only in unit tests.

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts [hunk 6]
```diff
@@ -30,7 +26,10 @@ export class OccReplenishmentOrderFormSerializer
   }
 
   /**
-   * Adds the current timestamp (including timezone offset) to a date string in the format YYYY-mm-dd
+   * Adds time and local timezone offset to a date string in the format YYYY-mm-dd.
+   * @param date date
+   * @param endOfDay when true, `23:59:59` is added the date. Otherwise, `00:00:00` is added.
+   *
```
Comment (Platonn) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]:
```suggestion
   * Adds the current timestamp (including timezone offset) to a date string in the format YYYY-mm-dd    *
```

File: projects/core/src/util/index.ts [hunk 7]
```diff
@@ -6,6 +6,7 @@ export * from './http-params-uri.encoder';
 export * from './normalize-http-error';
 export * from './regex-pattern';
 export * from './withdraw-on';
-export * from './date-picker-formatter.service';
-export * from './date-time-picker-formatter.service';
+// export * from './date-picker-formatter.service';
+// export * from './date-time-picker-formatter.service';
```
Comment (Platonn) [inline projects/core/src/util/index.ts]:
```suggestion
```

File: projects/storefrontlib/src/shared/components/index.ts [hunk 8]
```diff
@@ -2,7 +2,7 @@ export * from './anonymous-consents-dialog/index';
 export * from './card/index';
 export * from './carousel/index';
 export * from './date-picker/index';
-export * from './date-time-picker/index';
+// export * from './date-time-picker/index';
```
Comment (Platonn) [inline projects/storefrontlib/src/shared/components/index.ts]:
```suggestion
```

**Review by Platonn — DISMISSED** [review]

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts [hunk 9]
```diff
@@ -30,7 +26,7 @@ export class OccReplenishmentOrderFormSerializer
   }
 
   /**
-   * Adds the current timestamp (including timezone offset) to a date string in the format YYYY-mm-dd
+   * Adds the current timestamp (including timezone offset) to a date string in the format YYYY-mm-dd    *
```
Comment (Platonn) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts]:
```suggestion
   * Adds the current timestamp (including timezone offset) to a date string in the format YYYY-mm-dd
```

**Review by Platonn — APPROVED** [review]

File: projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts [hunk 10]
```diff
@@ -1,43 +1,24 @@
 import { TestBed, waitForAsync } from '@angular/core/testing';
+import { TimeUtils } from '@spartacus/core';
 import { OccReplenishmentOrderFormSerializer } from './occ-replenishment-order-form-serializer';
-import { DateTimePickerFormatterService } from '../../../../util/date-time-picker-formatter.service';
+import { TestingTimeUtils } from '../../../../../../../projects/core/src/util/testing-time-utils';
```
Comment (Pucek9) [inline projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts:4]: is this path proper?
