### PR TITLE
fix: fix export button align issue

### LINKED ISSUE #14535: Export button not aligned properly on order-confirmation page
When an order is placed, we can see the "export to CSV" button underneath the cart items on the order-confirmation page.
It is styled nicely for desktop resolution, but it appears to be misaligned on lower resolutions (see screen-shot):
Screenshot 2021-12-06 at 11 19 48

### PR DESCRIPTION
**Pull request by kimhw0630**
fix to align export button with other components in order-confirmation page
closes #14535

### CODE REVIEW

File: feature-libs/cart/import-export/components/export-entries/export-order-entries.component.ts [hunk 1]
```diff
@@ -15,6 +15,8 @@ import { ExportOrderEntriesToCsvService } from './export-order-entries-to-csv.se
   changeDetection: ChangeDetectionStrategy.OnPush,
 })
 export class ExportOrderEntriesComponent {
+  @HostBinding('class') styles = 'container';
```
Comment (bit172) [inline feature-libs/cart/import-export/components/export-entries/export-order-entries.component.ts:18]: Is there a reason why you used hostbinding here instead of applying the styles directly?

Comment (kimhw0630) [reply feature-libs/cart/import-export/components/export-entries/export-order-entries.component.ts:18]: @bit172 
I don't think you can add a style class in the template for the host element ...
Do you mean like below in the component property?
image

Thanks

Comment (bit172) [reply feature-libs/cart/import-export/components/export-entries/export-order-entries.component.ts:18]: I meant that it's not really necessary to add a class `.container` if you can apply the style directly to `cx-export-order-entries`, unless there's a reason that I'm not aware of

Comment (kimhw0630) [reply feature-libs/cart/import-export/components/export-entries/export-order-entries.component.ts:18]: @bit172 
I used the existing "container"  class (I think this class coming from bootstrap) because its parent's children containers use this class  (e.g.cx-order-confirmation-items) so it should have the same behavior in different browser sizes.

**Review by bit172 — APPROVED** [review]
