### PR TITLE
fix: Missing translation and text escaping off the button in storefinder list (GH-12422) 

### LINKED ISSUE #12422: Missing translation and text escaping off the button in storefinder list
**Steps to reproduce:**
Open http://localhost:4200/electronics-spa/en/USD/store-finder/find?query=%20 page in mobile mode. Then click for any store

**Results:**
image

**Expected results:**
- [ ] fix missing translation key [ [storeFinder:storeFinder.clickBack] - verify if it could be an empty string or if there has to be some "Back" text for a11y
- [ ] fix (too long) text is escaping out of the button (QA: verify on few screen widths)

### PR DESCRIPTION
**Pull request by bit172**
closes #12422

### CODE REVIEW

File: feature-libs/storefinder/assets/translations/en/store-finder.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@ export const storeFinder = {
   storeFinder: {
     openUntil: 'Open until',
     closed: 'Closed',
+    clickBack: 'Back',
```
Comment (Matejk00) [inline feature-libs/storefinder/assets/translations/en/store-finder.ts]: Can we change this translation key to `back`? I think will be more general and consistent.

**Review by Matejk00 — CHANGES_REQUESTED** [review]
It would be nice to cover all buttons in storefinder if possible with your code. There is another place where text is moving outside button area:
http://localhost:4200/electronics-spa/en/USD/store-finder/country/DE
Screenshot 2021-06-10 at 13 44 45

Are you able to fix it in this PR?

File: feature-libs/storefinder/styles/components/_store-finder-list.scss [hunk 2]
```diff
@@ -104,13 +104,11 @@
...
-    cursor: pointer;
     font-weight: 600;
-
-    &:hover {
-      color: var(--cx-color-primary);
-    }
+    overflow: hidden;
+    white-space: nowrap;
+    text-overflow: ellipsis;
+    max-width: 85vw;
```
Comment (Matejk00) [inline feature-libs/storefinder/styles/components/_store-finder-list.scss]: Not sure if I'm understanding reason for this max-width property. In my opinion we should rely on text size and adapt button width to the text to avoid situation where text is truncated in case super long word in some language.

**Review by Matejk00 — CHANGES_REQUESTED** [review]

File: feature-libs/storefinder/styles/components/_store-finder-list.scss (hunk 2 above)
Comment (bit172) [reply feature-libs/storefinder/styles/components/_store-finder-list.scss]: I used max-width since the button would extend past the page if there was not a limit or fixed width on the button when there was very long text in it.

**Comment by bit172** [comment]
> It would be nice to cover all buttons in storefinder if possible with your code. There is another place where text is moving outside button area:
> http://localhost:4200/electronics-spa/en/USD/store-finder/country/DE
> Screenshot 2021-06-10 at 13 44 45
> 
> Are you able to fix it in this PR?

I'm not sure about this one, but would it be better to switch to the column list for that view width?

**Comment by Matejk00** [comment]
> > It would be nice to cover all buttons in storefinder if possible with your code. There is another place where text is moving outside button area:
> > http://localhost:4200/electronics-spa/en/USD/store-finder/country/DE
> > Screenshot 2021-06-10 at 13 44 45
> > Are you able to fix it in this PR?
> 
> I'm not sure about this one, but would it be better to switch to the column list for that view width?

I think we can switch to the list view for such width, or decrease number of elements per row.

**Review by Matejk00 — APPROVED** [review]
