### PR TITLE
GH-8688: Fix issue

### LINKED ISSUE #8688: When there is one shipping address in a cost center it should be selected by default
When a cost center has only one shipping address is should be selected by default. This is not the case currently.

### Acceptance

When a cost center has only one shipping address is should be selected by default

### PR DESCRIPTION
**Pull request by LTiger14**
Closes #8688

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.ts [hunk 1]
```diff
@@ -107,7 +107,15 @@ export class ShippingAddressComponent implements OnInit {
         .getCostCenter()
         .pipe(take(1))
         .subscribe((selected) => (costCenterId = selected));
-      return this.userCostCenterService.getCostCenterAddresses(costCenterId);
+      return this.userCostCenterService
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.ts]: lets move this logic in `selectDefaultAddress`

**Review by bgambocjaviniar — APPROVED** [review]
