### PR TITLE
fix: JSON translations don't work in SSR in 3.1.0 

### LINKED ISSUE #11665: JSON i18n translations don't work in SSR in 3.1.0
**Describe the bug**
Lazy loaded translations don't work in SSR in 3.1.0. (both from npm and our repo).

Notes:
- Both static and lazy loaded translations work CSR
- Static work in SSR.

**Tell us the version of Spartacus**
- Library version: 3.1.0 form npm OR the repo branch `release/3.1.x`

**To Reproduce**
1. create fresh angular app `$ ng new <appName>`
1. enter the directory `<appName>`
1. install spartacus with ssr v3.1.0 using schematics `$ng add @spartacus/schematics@3.1.0 --ssr`
1. set backend baseUrl in app.module of the fresh app
1. disable ssr optimizations by passing `null` as a second argument of `const ngExpressEngine = NgExpressEngineDecorator.get(engine, null);` in the file `server.ts` of your fresh app
1. if your test backend doesn't have proper SSL cert, please add at the top of the file `server.ts` the line: 
   `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`
1. copy i18n JSON assets to your app:
    `cp ./node_modules/@spartacus/assets/i18n-assets ./src/assets -r`
1. in app.module set `i18n.debug` to `true` and `i18n.backend.loadPath` to `'assets/i18n-assets/{{lng}}/{{ns}}.json',`:
   ```
      i18n: {
        chunks: translationChunksConfig,
        backend: {
          loadPath: 'assets/i18n-assets/{{lng}}/{{ns}}.json',
        },
        debug: true,
      },
   ```
1. disable Javascript in your browser
2. run `$ yarn dev:ssr`
3. open in the browser http://localhost:4200/

**Expected behavior**
The page has all the labels translated

**Screenshots**
Browser:
image

SSR console:
image

### PR DESCRIPTION
**Pull request by dunqan**
Fixes port value when generating `SERVER_REQUEST_ORIGIN`

Closes #11665

### CODE REVIEW

**Review by Platonn — DISMISSED** [review]

File: core-libs/setup/ssr/engine-decorator/ng-express-engine-decorator.ts [hunk 1]
```diff
@@ -108,15 +108,17 @@ function getRequestUrl(req: Request): string {
...
-  if (req.get('X-Forwarded-Host')?.includes(req.hostname)) {
-    let port = ':' + req.get('X-Forwarded-Port');
-    if (
-      (port === ':80' && req.protocol === 'http') ||
-      (port === ':443' && req.protocol === 'https')
-    ) {
-      port = '';
+  const trustProxyFn = req.app.get('trust proxy fn');
+  let forwardedHost = req.get('X-Forwarded-Host');
+  if (forwardedHost && trustProxyFn(req.connection.remoteAddress, 0)) {
```
Comment (Platonn) [inline core-libs/setup/ssr/engine-decorator/ng-express-engine-decorator.ts:113]: I'm having hard time finding express js docs that help me decipher `trustProxyFn(req.connection.remoteAddress, 0)`. Can we add a comment what and why we check here?

Btw. perhaps we might also want to drop a link here to the express js implementation
https://github.com/expressjs/express/blob/b93ffd4bdc09c3af925eed80c28bd37f63bb3cfc/lib/request.js#L427-L431

**Review by Platonn — APPROVED** [review]
