### PR TITLE
fix: Schematics - add ExternalRouting to the feature set

### LINKED ISSUE #12486: ExternalRouting Module does not get added when generating / updating a project
**Describe the bug**
When using schematic to generate / update the project, among others, the file `spartacus-features.module.ts` is generated / updated

Within the spartacus code, this file has the following section:

```
/************************* Opt-in features *************************/

    ExternalRoutesModule.forRoot(), // to opt-in explicitly, is added by default schematics
    JsonLdBuilderModule,

    /************************* External features *************************/
```

After running the schematics, the generated file `spartacus-features.module.ts` in my project does NOT contain the line ` ExternalRoutesModule.forRoot()`

**Tell us the version of Spartacus**
- Library version: 3.3.0

**To Reproduce**
1. Generate a fresh spartacus project
2. Open the file `spartacus-features.module.ts`
3. Notice that the file does not contain the ExternalRoutesModule

**Expected behavior**
According to the comment within the file in the spartacus codebase `// to opt-in explicitly, is added by default schematics` and since the documentation about the feature does not say anything about opting in manually (https://sap.github.io/spartacus-docs/external-routes/), I would expect, that the schematics adds the line according to the spartacus version of the file `spartacus-features.module.ts`.

**Screenshots**
Spartacus Feature Module:
image

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Other Ticket about External Routing**
https://github.com/SAP/spartacus/issues/12292

### PR DESCRIPTION
**Pull request by znikola**
closes #12486

### CODE REVIEW

File: projects/schematics/src/add-spartacus/spartacus-features.ts [hunk 1]
```diff
@@ -320,6 +320,18 @@ function configureSpartacusModules(
         });
       });
 
+      [`ExternalRoutesModule.forRoot(),`].forEach((content) => {
```
Comment (marlass) [inline projects/schematics/src/add-spartacus/spartacus-features.ts]: Can we also add comment before this module to separate it from Event Modules that are added just before it?

**Review by marlass — COMMENTED** [review]
One nitpick added

**Review by marlass — APPROVED** [review]
