### PR TITLE
fix: add regions in PDP (#13518)

### LINKED ISSUE #13518: Add region landmarks to Products Details Page
**Describe the bug**

- Screen Reader users must be able to navigate by landmarks, currently, there aren't many nor labelled, therefore relevant sections on the page should be identified with meaningful landmarks names.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**
1. Open any Screen Reader (VO, NVDA, JAWS).
2. Bring up the Rotor or Element List Menu.
3. Choose Landmarks view.
4. See absence of relevant landmarks.

**Expected behavior**

- Use only predefined landmarks https://wiki.wdf.sap.corp/wiki/display/spar/Landmarks
- `<cx-carousel role="region" aria-label="Carousel, Images of product name">`
- `<cx-tab-paragraph-container role="region" aria-label="Tab group with more product details">`

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #13518

### CODE REVIEW

**Review by developpeurweb — DISMISSED** [review]
Works well with VO, JAWS and NVDA.

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.ts [hunk 1]
```diff
@@ -13,11 +13,22 @@ import {
 export class ProductImageZoomProductImagesComponent extends ProductImagesComponent {
   expandImage = new BehaviorSubject(false);
   selectedIndex: number | undefined;
+  productName: string | undefined;
 
   constructor(protected currentProductService: CurrentProductService) {
     super(currentProductService);
   }
 
+  getProductName(): string | undefined {
```
Comment (Zeyber) [inline feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.ts]: Better to get the entire product for easier extensibility. We should also return an observable and fetch in the template using an `async` pipe.

File: projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts [hunk 2]
```diff
@@ -34,10 +40,13 @@ export class TabParagraphContainerComponent
 
   tabTitleParams: (Observable<any> | null)[] = [];
 
+  tabPanelContainerRegion: string;
+
   // TODO: it is not used any more, so can be removed in 5.0
   subscription: Subscription;
 
   constructor(
+    protected translationService: TranslationService,
```
Comment (Zeyber) [inline projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts]: This is a breaking change. Service should be optional via `?` and added last as a param.

File: projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts [hunk 3]
```diff
@@ -23,6 +24,11 @@ import { BREAKPOINT } from '../../../layout/config/layout-config';
   selector: 'cx-tab-paragraph-container',
   templateUrl: './tab-paragraph-container.component.html',
   changeDetection: ChangeDetectionStrategy.OnPush,
+  host: {
```
Comment (Zeyber) [inline projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts]: This seems like a lot of complexity to have aria attributes. Can we move and clean up this logic in the template?

File: projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts [hunk 4]
```diff
@@ -105,6 +115,15 @@ export class TabParagraphContainerComponent
     }
   }
 
+  getRegionLabel(): void {
```
Comment (Zeyber) [inline projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts]: We can use an async pipe if we can move this to the template somehow which would be a lot cleaner.

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html [hunk 5]
```diff
@@ -9,6 +9,11 @@
 
 <ng-container *ngIf="thumbs$ | async as thumbs">
   <cx-carousel
+    role="region"
+    [attr.aria-label]="
+      'carousel.carouselForProduct' | cxTranslate: { product: getProductName() }
+    "
+    tabindex="-1"
```
Comment (Zeyber) [inline feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html]: The `cx-carousel` itself shouldn't be accessible by tab key. Is there an attribute that makes it accessible?

**Review by Zeyber — CHANGES_REQUESTED** [review]

File: projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts (hunk 3 above)
Comment (BenjaminEmiliani) [reply projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts]: I tried but adding screen reader properties does not seem to work with ng-container

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html (hunk 5 above)
Comment (BenjaminEmiliani) [reply feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html]: Well the `tabindex="-1"` means that the element should be focusable, but should not be reachable via sequential keyboard navigation. The purpose of this attribute is so that focus is kept in the region when user navigates to the region via Landmark Navigation menu 

Does this answer the question?

File: projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts (hunk 4 above)
Comment (BenjaminEmiliani) [reply projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts]: I have not been able to successfully add SR context inside an ng-container due to its nature

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.ts [hunk 6]
```diff
@@ -18,6 +20,10 @@ export class ProductImageZoomProductImagesComponent extends ProductImagesCompone
     super(currentProductService);
   }
 
+  getProduct(): Observable<Product> {
```
Comment (Zeyber) [inline feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.ts]: We don't need this method. `product$` is already exposed thanks to extending `ProductImagesComponent`. We just need to make it public for the template like `product$: Observable<Product> = this.product$;`.

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html [hunk 7]
```diff
@@ -8,14 +8,21 @@
...
-    *ngIf="thumbs.length"
-    class="thumbs"
-    [items]="thumbs"
-    itemWidth="120px"
-    [hideIndicators]="false"
-    [template]="thumb"
-  ></cx-carousel>
+  <ng-container *ngIf="getProduct() | async as product">
+    <cx-carousel
+      role="region"
```
Comment (Zeyber) [inline feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html:13]: This is another instance where aria attributes shouldn't really be on the component element tag but rather within it, like the TabParagraphContainer.

**Review by Zeyber — CHANGES_REQUESTED** [review]

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.ts (hunk 6 above)
Comment (BenjaminEmiliani) [reply feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.ts]: Done

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html (hunk 7 above)
Comment (BenjaminEmiliani) [reply feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html:13]: I see what you mean, however, I don't think we want to make every single `cx-carousel` a region. And the accessibility label is also specific to a product: 'Carousel, Images for {{product}}'

So these a11y attributes would not fit the carousels in homepage for example

**Review by developpeurweb — DISMISSED** [review]
Works well with VO, JAWS and NVDA

File: feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html [hunk 8]
```diff
@@ -8,14 +8,21 @@
...
 <ng-container *ngIf="thumbs$ | async as thumbs">
-  <cx-carousel
-    *ngIf="thumbs.length"
-    class="thumbs"
-    [items]="thumbs"
-    itemWidth="120px"
-    [hideIndicators]="false"
-    [template]="thumb"
-  ></cx-carousel>
+  <ng-container *ngIf="product$ | async as product">
```
Comment (Zeyber) [inline feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-product-images/product-image-zoom-product-images.component.html:11]: Just for safety, could be good to mention the addition of this wrapper and newly exposed `product$` observable.

**Review by Zeyber — CHANGES_REQUESTED** [review]

**Review by Zeyber — APPROVED** [review]
