### PR TITLE
fix:Aria-label dynamically set depending  displayed componentData

### LINKED ISSUE #13770: [small adjustment needed] Order History accordions don't vocalize if they are collapsed or expanded
**Additional context**

- Fix this ticket only after the whole Screen Reader milestone for desktop is completed. 

**Describe the bug**

- Order History tabs are converted into accordions on mobile, but don't provide any hint they are being collapsed or expanded

**To Reproduce: Watch Test Videos**

- Android Talkback test video
https://video.sap.com/media/t/1_1gtfpn6o
min 1:30:00
  
- Iphone VoiceOver test video
https://video.sap.com/media/t/1_qa70rxtl
min 0:42:32

**Expected behavior**
- Screen reader vocalizes the expanded or collapsed state of the accordion.

### LINKED ISSUE #15477: Improve SR a11y of TabParagraphContainer component
**Description**:
Initially, screen reader support for TabParagraphContainer component was made specific to the instance in PDP. The component is generic and also being used in Order History UI to display order related tabs. As seen in the image below, the component instance is exposed to screen reader API as a region, 'Tab group with more product details'.
Screen Shot 2022-03-29 at 1 29 04 PM

**Expected** :
Generic screen reader support for TabParagraphContainer component

### PR DESCRIPTION
**Pull request by FollowTheFlo**
Closes #15477
aria-label is pulled from
AccountOrderHistoryTabContainer.tabPanelContainerRegion
or
TabPanelContainer.tabPanelContainerRegion

### CODE REVIEW

File: projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ import { CmsComponentData } from '../../../cms-structure/page/model/index';
 })
 export class TabParagraphContainerComponent implements AfterViewInit, OnInit {
   activeTabNum = 0;
+  ariaLabel: string | undefined;
```
Comment (Pucek9) [inline projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts]:
```suggestion
  ariaLabel?: string;
```

Comment (FollowTheFlo) [reply projects/storefrontlib/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts]: done in [453d946](https://github.com/SAP/spartacus/pull/15382/commits/453d946217f5a60d11a39951173418abbb377014)

**Review by developpeurweb — APPROVED** [review]
Works well on JAWS/NVDA/VO

**Review by Pucek9 — APPROVED** [review]
