### PR TITLE
fix: Allow to use own icon type

### LINKED ISSUE #13209: Customers can not add own icon types
**Describe the bug**
https://stackoverflow.com/questions/68455999/cx-icon-with-custom-icon-types-gives-an-error-when-stricttemplates-is-set-to

**Tell us the version of Spartacus**
- Library version: 4.0-rc

**To Reproduce**

1. Define own icon type in module (different than defined in `enum ICON_TYPE`)
2. Try use this icon type
3. See error like `Type 'CUSTOM_ICON_TYPE.CUSTOM_ICON' is not assignable to type 'ICON_TYPE'. ngtsc(2322)`

**Expected behavior**
Providing own icons should be possible

**Additional context**
Current workaround:
```<cx-icon [type]="$any(CUSTOM_ICON_TYPE.CUSTOM_ICON)"></cx-icon>```

### PR DESCRIPTION
**Pull request by Pucek9**
Closes #13209

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts [hunk 1]
```diff
@@ -8,7 +8,9 @@ import {
 import { SafeHtml } from '@angular/platform-browser';
 import { DirectionMode } from '../../../layout/direction/config/direction.model';
 import { IconLoaderService } from './icon-loader.service';
-import { ICON_TYPE } from './icon.model';
+import { ICON_TYPE as DEFAULT_ICON_TYPE } from './icon.model';
+
+type ICON_TYPE = DEFAULT_ICON_TYPE | string;
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts:13]: It's a breaking change. Icon type used to be an enum (so you can use its values i.e. `ICON_TYPE.STAR`), but now it becomes only a type.

Comment (Platonn) [reply projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts:13]: We should rather relax the typing in the places that refer to the ICON_TYPE, e.g. in the IconComponent (and perhaps other places - you need to check):
https://github.com/SAP/spartacus/blob/develop/projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts#L42-L52

Comment (Platonn) [reply projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts:13]: My bad! I didn't pay attention it's the component file, I somehow thought it's the  reexport file. Sorry for confusion!

**Review by Platonn — APPROVED** [review]

**Review by marlass — APPROVED** [review]
