### PR TITLE
fix: Missing focus management when on PDP 'Show Reviews' is clicked (#14030)

### LINKED ISSUE #14030: [Not fixed in #11637] Missing focus management and narration on PDP when 'Show Reviews' is clicked
Address after #11637 

**Describe the bug**
For a11y users, there is not focus shift or vocalized feedback when users select 'Show reviews' link on a product display page.

**Tell us the version of Spartacus**
- 4.1

**To Reproduce**
1. Click on any product with reviews
2. Click on 'Show reviews'
4. Observe current focus and lack of context feedback

**Expected behavior**
Focus shifts to 'Reviews' tab. 
vocalized feedback that user is in the Reviews section

### PR DESCRIPTION
**Pull request by pawelfras**
closes #14030

### CODE REVIEW

**Review by developpeurweb — DISMISSED** [review]
Works well on JAWS/NVDA/VO.
Pls make sure an angular dev reviews the code before merging

**Review by FollowTheFlo — DISMISSED** [review]
tested all scenario i could think: switch tabs/accordion view, resize, voice over.
ran unit and e2e tests.
Code looks good to me, no enhancements or grey area i could think.

**Review by szczepaniak-michal — DISMISSED** [review]

File: projects/storefrontlib/cms-components/product/product-intro/product-intro.component.ts [hunk 1]
```diff
@@ -2,59 +2,106 @@ import {
...
-      })
-      .unsubscribe();
+      });
   }
 
-  // NOTE: Does not currently exists as its own component
-  // but part of tabs component. This is likely to change in refactor.
-  private getReviewsComponent(): Element {
-    return this.winRef.document.querySelector('cx-product-reviews');
+  // Create a mutation observer to observe if reviews component has been rendered
```
Comment (Platonn) [inline projects/storefrontlib/cms-components/product/product-intro/product-intro.component.ts:72]: Let's turn it to JS doc comment so customers may benefit from it.

File: projects/storefrontlib/cms-components/product/product-intro/product-intro.component.ts [hunk 2]
```diff
@@ -13,52 +14,84 @@ import { CurrentProductService } from '../current-product.service';
   changeDetection: ChangeDetectionStrategy.OnPush,
 })
 export class ProductIntroComponent implements AfterContentChecked {
-  reviewsTabAvailable = new BehaviorSubject<boolean>(false);
+  product$: Observable<Product | null> =
```
Comment (BenjaminEmiliani) [inline projects/storefrontlib/cms-components/product/product-intro/product-intro.component.ts:22]: Hey @pawelfras I wonder if this should be added to 5.0md? Here from documentation it says functions but I don't see why it would not also apply to public properties
Screen Shot 2022-03-18 at 9 56 55 AM

File: projects/storefrontlib/cms-components/product/product-intro/product-intro.component.spec.ts [hunk 3]
```diff
@@ -34,20 +45,23 @@ describe('ProductIntroComponent in product', () => {
...
+    translationService = TestBed.inject(TranslationService);
+    spyOn(translationService, 'translate').and.returnValue(of(reviewsLabel));
+
     fixture = TestBed.createComponent(ProductIntroComponent);
     productIntroComponent = fixture.componentInstance;
   });
 
-  it('should be created', () => {
-    expect(productIntroComponent).toBeTruthy();
-  });
```
Comment (BenjaminEmiliani) [inline projects/storefrontlib/cms-components/product/product-intro/product-intro.component.spec.ts]: Hey @pawelfras is there a reason why you removed this spec?

File: projects/storefrontlib/cms-components/product/product-intro/product-intro.component.ts [hunk 4]
```diff
@@ -13,52 +13,68 @@ import { CurrentProductService } from '../current-product.service';
...
+        if (reviewsTab) {
           this.clickTabIfInactive(reviewsTab);
-          setTimeout(
-            () => reviewsComponent.scrollIntoView({ behavior: 'smooth' }),
-            0
-          );
+          setTimeout(() => {
+            reviewsTab.scrollIntoView({ behavior: 'smooth' });
+            reviewsTab.focus({ preventScroll: true });
+          }, 0);
```
Comment (BenjaminEmiliani) [inline projects/storefrontlib/cms-components/product/product-intro/product-intro.component.ts]: Very minor note but if timeout is 0, we can omit the parameter

File: docs/migration/5_0.md [hunk 5]
```diff
@@ -498,14 +498,23 @@ The following keys have been added to `configurator-common.ts`:
...
 
 - `subscriptionDialog.notifiedSuffix` changed from `as soons as this product is back in stock.` to `as soon as this product is back in stock.`.
 - `subscriptionDialog.manageChannelsPrefix` changed from `Manage your prefered notification channels at the ` to `Manage your preferred notification channels on the `.
-- `subscriptionDialog.manageSubscriptionsPrefix` changed from `You can manage your subscriptions at ` to `You can manage your subscriptions on `.
\ No newline at end of file
+- `subscriptionDialog.manageSubscriptionsPrefix` changed from `You can manage your subscriptions at ` to `You can manage your subscriptions on `.
+
+### ProductIntroComponent
+
+- Subject `reviewsTabAvailable` has been renamed to "areReviewsAvailable$".
```
Comment (BenjaminEmiliani) [inline docs/migration/5_0.md]: @pawelfras I think this doc note should be:
Property \`reviewsTabAvailable\` has been renamed to \`areReviewsAvailable$\`.

File: projects/storefrontlib/cms-components/product/product-intro/product-intro.component.spec.ts (hunk 3 above)
Comment (pawelfras) [reply projects/storefrontlib/cms-components/product/product-intro/product-intro.component.spec.ts]: I was always wondering about value added of this kind of tests, but this is a discussion for another topic. Test has been reverted to keep consistency.

**Review by developpeurweb — DISMISSED** [review]
Still works well on JAWS/NVDA/VO.

**Review by szczepaniak-michal — DISMISSED** [review]

**Review by szczepaniak-michal — DISMISSED** [review]

**Review by developpeurweb — APPROVED** [review]
Still works well on JAWS/NVDA/VO.
