### PR TITLE
test: E2E Faceting + Checkout

### LINKED ISSUE #12013: Request. E2E Faceting + Checkout
Please write an e2e test that combines faceting and checkout.

There is already a test for faceting here:
spartacus/projects/storefrontapp-e2e-cypress/cypress/integration/regression/product-search/product-search-product-type-flow.e2e-spec.ts

There is also already a test for checkout here:
spartacus/projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout/checkout-flow.e2e-spec.ts

However, there is no test that combines the 2 functionalities.
This is a basic business flow that requires automated verification.
There must be no doubt that product faceting and checkout work together from end-2-end.
(SKUs must be added to cart and complete checkout after being listed as a result of a faceting process)

This requested test may be long, but now, with parallelization this is no longer a concern.

### PR DESCRIPTION
**Pull request by bit172**
closes #12013

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/sample-data/checkout-flow.ts [hunk 1]
```diff
@@ -95,3 +95,27 @@ export const cartWithCheapProduct: SampleCartProduct = {
   total: '$8.20',
   totalAndShipping: '$20.19',
 };
+
+export const carts: SampleCartProduct[] = [
+  {
+    estimatedShipping: '11.99',
```
Comment (KateChuen) [inline projects/storefrontapp-e2e-cypress/cypress/sample-data/checkout-flow.ts]: To make the test more robust, we try to avoid using hardcoded values. If you could instead, after adding the first item to cart, grab all the info you need from the response (product name, product Id or price), and assert against those instead.

File: projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout/checkout-flow.core-e2e-spec.ts [hunk 2]
```diff
@@ -25,5 +31,72 @@ context('Checkout flow', () => {
...
+      const user = getSampleUser();
+      checkout.visitHomePage();
+
+      checkout.clickHamburger();
+
+      checkout.registerUser(false, user);
+      searchResult();
+      filterUsingFacetFiltering();
+
+      cy.intercept(
```
Comment (KateChuen) [inline projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout/checkout-flow.core-e2e-spec.ts]: Looks good now. The only thing I would say is, maybe extract all these into a function in checkout-flow.ts file. Can call it anything, maybe checkoutUsingFacetting() or checkoutFirstDisplayedProduct().
So we keep this spec test file more user readable and short.

**Review by KateChuen — APPROVED** [review]
