### PR TITLE
Handle add to cart errors

### LINKED ISSUE #14762: handle add to cart error
If the "add to cart" has error, we need a better way to handle it. For example, for anonymous user, add one product in cart, then remove the cart from backoffice. Add this product again. Since the active cart is gone, so the "addEntry" is failed. We can see the error message of "cart not found", but the modal is empty with spinner running.
Screen Shot 2022-01-12 at 12 04 55 PM

### PR DESCRIPTION
**Pull request by WeizhengSap**
close #14762

### CODE REVIEW

File: projects/assets/src/translations/en/common.ts [hunk 1]
```diff
@@ -133,6 +133,8 @@ export const common = {
     },
     cartNotFound: 'Cart not found.',
     invalidCodeProvided: 'Invalid code provided.',
+    unknownIdentifier: 'Item not found',
```
Comment (plabadie) [inline projects/assets/src/translations/en/common.ts]: Should the message end with a dot? (most of them seem to have one)

Comment (plabadie) [reply projects/assets/src/translations/en/common.ts]: Item as in "cart item" or as any kind of item not found?

Comment (WeizhengSap) [reply projects/assets/src/translations/en/common.ts]: any kind of item.

File: feature-libs/cart/main/core/http-interceptors/handlers/bad-cart-request.handler.ts [hunk 2]
```diff
@@ -44,6 +45,22 @@ export class BadCartRequestHandler extends HttpErrorHandler {
       });
   }
 
+  protected handleOtherCartErrors(
+    _request: HttpRequest<any>,
+    response: HttpErrorResponse
+  ): void {
+    this.getErrors(response)
+      .filter((e) => e.reason !== 'notFound' || e.subjectType !== 'cart')
```
Comment (plabadie) [inline feature-libs/cart/main/core/http-interceptors/handlers/bad-cart-request.handler.ts:53]: instead of `e.reason !== 'notFound' || e.subjectType !== 'cart')`, could we use ` !isCartNotFoundError(e)`

File: feature-libs/cart/main/components/cart/added-to-cart-dialog/added-to-cart-dialog-event.listener.spec.ts [hunk 3]
```diff
@@ -75,4 +98,14 @@ describe('AddToCartDialogEventListener', () => {
       );
     });
   });
+
+  describe('closeModal', () => {
+    it('Should close the add to cart dialog', () => {
```
Comment (plabadie) [inline feature-libs/cart/main/components/cart/added-to-cart-dialog/added-to-cart-dialog-event.listener.spec.ts:103]: perhaps we can also test what happens when the active modal ref is not equal to the listener modal ref.  It might help the unit test branch coverge %

File: feature-libs/cart/main/core/http-interceptors/handlers/bad-cart-request.handler.ts (hunk 2 above)
Comment (WeizhengSap) [reply feature-libs/cart/main/core/http-interceptors/handlers/bad-cart-request.handler.ts:53]: `isCartNotFoundError(e)` also check `!isSelectiveCart(error.subject)`

**Review by plabadie — APPROVED** [review]
