### PR TITLE
fix: add option for reusing a pending SSR render for subsequent similar requests (instead of fallback to CSR)

### LINKED ISSUE #13623: Don't always fall back to CSR if rendering is in progress
The goal of this ticket is to improve the SSR performance in the following way:

- The `timeout` option is set to 3s
- An initial request for the `/` hits the server and SSR render is triggered. 
- let's say the rendering of the `/` will take 4s. This means that after 3s, the first request will timeout and return CSR to the end user
- the `/` continues to render in the background for one more second, and then it'll finish the render successfully.
- the second request comes in 2s after the first one
- in the current implementation, the second request would immediately fall back to CSR, as we're still rendering the first request.
- this improvement will allow the second request to wait at most 3s before falling back to CSR (honoring the `timeout` option). This is the maximum time the second request will wait, and it's likely the response will come sooner (as we'll see below).
- 2s after the second request arrived, the render for `/` finishes. The second request is responded to with the SSR 2s after it was sent.
- if we scale this up, and say that 1000 new requests hit the server after the initial request, we begin to see how this improvement will lower the rate at which the CSR fallback happens, and how much quicker the responses will be for the subsequent requests.

### PR DESCRIPTION
**Pull request by Platonn**
Before this PR:
When the html for a request was being rendered and in the meantime new requests arrived for the same rendering key (e.g. for the same URL), they were resolved immediately with a CSR fallback.

This PR preserves the previous default behavior, but also adds a new opt-in config that helps avoiding unnecessary CSR fallbacks.

The new opt-in config `reuseCurrentRendering` allows the subsequent requests to wait for the result of the pending render that was triggered by the 1st request. Finally, the all the waiting requests for the same rendering key (e.g. URL) will reuse the result of a single completed render.

Note 1: Same as previously, each request can time out independently (according to the `timeout` config) and then this request is resolved with a CSR fallback. However, with the new config `reuseCurrentRendering` enabled, other requests (which didn't time out yet) can still wait for the result of the render.

Note 2: The existing config `concurency` limits the number of the pending renders. So when config `reuseCurrentRendering` is enabled,  requests for the same rendering key take up just one concurrency slot, because they share just one pending render.

Note 3: Previously the `RenderinStrategy.ALWAYS_SSR` caused triggering of a new render for each request, even if there was a pending render for the same rendering key. This PR preserves the previous default behavior. However, with the new config `reuseCurrentRendering` enabled, the subsequent requests for the same key won't trigger new renders, but will wait for the pending render to complete.

closes #13623

### CODE REVIEW

File: projects/storefrontapp/server.ts [hunk 1]
```diff
@@ -16,13 +17,14 @@ const express = require('express');
 const ssrOptions: SsrOptimizationOptions = {
   concurrency: 20,
   timeout: Number(process.env.SSR_TIMEOUT ?? 3000),
+  reuseCurrentRendering: true,
```
Comment (Platonn) [inline projects/storefrontapp/server.ts:20]: To be removed?

Comment (znikola) [reply projects/storefrontapp/server.ts:20]: I'd rather have it on by default in our own setup

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 2]
```diff
@@ -214,4 +311,90 @@ export class OptimizedSsrEngine {
...
+  }
+
+  /**
+   * Updates the state of the concurrency before starting the render.
+   */
+  private incrementCurrentConcurrency({
+    isFirstRequestForKey,
+  }: {
+    isFirstRequestForKey: boolean;
+  }): void {
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: Since the method is private, we can evolve it freely and have the param as an object (if there's a need). For now, for readability and simplicity sake, I suggest to just pass one param `isFirstRequestForKey: boolean`

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 3]
```diff
@@ -214,4 +311,90 @@ export class OptimizedSsrEngine {
...
+    }
+  }
+
+  /**
+   * Updates the state of the concurrency after the render is considered finished.
+   */
+  private decrementCurrentConcurrency({
+    isFirstRequestForKey,
+  }: {
+    isFirstRequestForKey: boolean;
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: The same as above

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 4]
```diff
@@ -110,92 +174,125 @@ export class OptimizedSsrEngine {
...
     const response: Response = options.res || options.req.res;
 
+    if (this.returnCachedRender(request, callback)) {
+      this.log(`Render from cache (${request?.originalUrl})`);
+      return;
+    }
+    if (!this.shouldRender(request)) {
+      this.fallbackToCsr(response, filePath, callback);
+      return;
+    }
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts:206]: Nicely flattened 👍🏻

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 5]
```diff
@@ -110,92 +174,125 @@ export class OptimizedSsrEngine {
...
+      this.renderingCache.clear(renderingKey);
+      maxRenderTimeout = undefined;
+
+      this.log(
+        `Rendering of ${request?.originalUrl} was not able to complete. This might cause memory leaks!`,
+        false
+      );
+
+      if (this.ssrOptions?.reuseCurrentRendering) {
+        this.renderCallbacks.delete(renderingKey);
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: Nice. Are we covering this in a test?

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 6]
```diff
@@ -47,29 +48,40 @@ class TestEngineRunner {
...
       this.responseParams.push(response);
     });
 
     return this;
   }
 }
 
+const getCurrentConcurrency = (
+  engineRunner: TestEngineRunner
+): { currentConcurrency: number } => {
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts:76]: Do we plan to return more parameters as part of the return type?

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 7]
```diff
@@ -110,92 +174,125 @@ export class OptimizedSsrEngine {
...
+      }, timeout);
     } else {
-      this.log(`Render from cache (${request?.originalUrl})`);
+      // Here we respond with the fallback to CSR, but we don't `return`.
+      // We let the actual rendering task to happen in the background
+      // to eventually store the rendered result in the cache.
+      this.fallbackToCsr(response, filePath, callback);
     }
+
+    // start rendering
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: This comment is a bit misleading because we don't actually start the rendering here, and also because of line 286 where we call the `startRendering()`. I suggest to remove it.

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 8]
```diff
@@ -214,4 +311,90 @@ export class OptimizedSsrEngine {
 
     return doc;
   }
+
+  /**
+   * Delegates the render to the original _Angular Universal express engine_.
+   *
+   * In case when the config `reuseCurrentRendering` is enabled and **if there is already a pending
+   * render task for the same rendering key**, it doesn't delegate a new render to Angular Universal.
+   * Instead, it waits for the current rendering to complete and then reuse the result for all waiting requests.
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts:280]: For clarity, I'd also mention here that it waits until each request's timeout expires.
Maybe something like:

```text
Instead, it waits for the current render to complete (respecting the timer option) and then reuse the result for all waiting requests.
```

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 9]
```diff
@@ -214,4 +311,90 @@ export class OptimizedSsrEngine {
...
+    renderCallback,
+    request,
+    isFirstRequestForKey,
+  }: {
+    filePath: string;
+    options: any;
+    renderCallback: SsrCallbackFn;
+    request: Request;
+    isFirstRequestForKey: boolean;
+  }) {
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: let's explicitly specify the function's return type to `void`

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 10]
```diff
@@ -214,4 +311,90 @@ export class OptimizedSsrEngine {
...
   }
+
+  /**
+   * Delegates the render to the original _Angular Universal express engine_.
+   *
+   * In case when the config `reuseCurrentRendering` is enabled and **if there is already a pending
+   * render task for the same rendering key**, it doesn't delegate a new render to Angular Universal.
+   * Instead, it waits for the current rendering to complete and then reuse the result for all waiting requests.
+   */
+  private startRender({
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: The name is at the same the perfect and confusing:
- perfect because it's short and describes exactly what the method does
- but it's confusing because it starts the rendering only for the first request for key (if the option is enabled ofc), but _not_ for the subsequent requests. I know this is already described in method's jsdoc, but it's still confusing unless you have a bigger picture. Something to consider and discuss. Maybe `manageRendering` could be a candidate.

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 11]
```diff
@@ -214,4 +311,90 @@ export class OptimizedSsrEngine {
...
+    if (!this.renderCallbacks.has(renderingKey)) {
+      this.renderCallbacks.set(renderingKey, []);
+    }
+    this.renderCallbacks.get(renderingKey)?.push(renderCallback);
+
+    if (isFirstRequestForKey) {
+      this.expressEngine(filePath, options, (err, html) => {
+        // Share the result of the render with all awaiting requests for the same key:
+
+        // Note: we access the Map at the moment of the render finished (don't store value it in a local variable),
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: Is there a typo in this comment? In this part: `don't store value it in a local variable`?

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 12]
```diff
@@ -586,4 +619,375 @@ describe('OptimizedSsrEngine', () => {
...
+        );
+        expect(engineRunner.renders).toEqual(['', '']);
+
+        flush();
+      }));
+    });
+
+    describe('when enabled', () => {
+      describe('multiple subsequent requests for the same rendering key should reuse the current render', () => {
+        it('and the first request should timeout', fakeAsync(() => {
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts:671]: The name of the test is not clear.
Are we testing the case when the first request (the one that started the render) times out?

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 13]
```diff
@@ -586,4 +619,375 @@ describe('OptimizedSsrEngine', () => {
...
+          expect(getCurrentConcurrency(engineRunner)).toEqual({
+            currentConcurrency: 1,
+          }); // the render still continues in the background
+
+          tick(100);
+
+          // eventually the render succeeds and 3 remaining requests get the same response:
+          expect(engineRunner.renderCount).toEqual(1);
+          expect(engineRunner.renders).toEqual([
+            '',
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts]: Fallback comment? :)

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 14]
```diff
@@ -586,4 +619,375 @@ describe('OptimizedSsrEngine', () => {
...
+                `SSR rendering exceeded timeout ${timeout}, fallbacking to CSR for ${requestUrl}`
+              ) {
+                renderExceedMessageCount++;
+              }
+            });
+          });
+
+          expect(renderExceedMessageCount).toBe(2);
+          expect(engineRunner.renderCount).toEqual(0);
+          expect(engineRunner.renders).toEqual(['', '']);
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts:732]: Fallback comment? :)

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 15]
```diff
@@ -586,4 +619,375 @@ describe('OptimizedSsrEngine', () => {
...
+
+          tick(100);
+          expect(engineRunner.optimizedSsrEngine['log']).toHaveBeenCalledWith(
+            `SSR rendering exceeded timeout ${timeout}, fallbacking to CSR for ${requestUrl}`,
+            false
+          );
+
+          tick(100);
+          expect(engineRunner.renderCount).toEqual(1);
+          expect(engineRunner.renders).toEqual(['', `${requestUrl}-0`]);
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts:692]: Fallback comment? :)

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 16]
```diff
@@ -586,4 +619,375 @@ describe('OptimizedSsrEngine', () => {
...
+
+        tick(100);
+        expect(engineRunner.optimizedSsrEngine['log']).toHaveBeenCalledWith(
+          `CSR fallback: rendering in progress (${requestUrl})`
+        );
+        expect(engineRunner.optimizedSsrEngine['log']).toHaveBeenCalledWith(
+          `SSR rendering exceeded timeout ${timeout}, fallbacking to CSR for ${requestUrl}`,
+          false
+        );
+        expect(engineRunner.renders).toEqual(['', '']);
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts:663]: Fallback comment? :)

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 17]
```diff
@@ -586,4 +619,375 @@ describe('OptimizedSsrEngine', () => {
...
+          `SSR rendering exceeded timeout ${timeout}, fallbacking to CSR for ${requestUrl}`,
+          false
+        );
+        expect(engineRunner.optimizedSsrEngine['log']).toHaveBeenCalledWith(
+          `SSR rendering exceeded timeout ${timeout}, fallbacking to CSR for ${differentUrl}`,
+          false
+        );
+
+        expect(engineRunner.renderCount).toEqual(1);
+        expect(engineRunner.renders).toEqual(['', '']);
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts:1002]: Fallback comment? :)

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts [hunk 18]
```diff
@@ -586,4 +619,375 @@ describe('OptimizedSsrEngine', () => {
...
+          expect(getCurrentConcurrency(engineRunner)).toEqual({
+            currentConcurrency: 0,
+          });
+          expect(getRenderCallbacksCount(engineRunner, ssrRequest)).toEqual({
+            renderCallbacksCount: 0,
+          });
+        }));
+      });
+
+      it('should NOT queue the subsequent requests for a different rendering key', fakeAsync(() => {
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts]: Let's not use `queue` anymore, as we're using the map internally.

**Review by znikola — CHANGES_REQUESTED** [review]

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts (hunk 5 above)
Comment (Platonn) [reply core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: Yes. Here https://github.com/SAP/spartacus/blob/feature/GH-13623--v2/core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts#L925-L937

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts (hunk 6 above)
Comment (Platonn) [reply core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.spec.ts:76]: Due to a lot of assertions on numbers 0,1,2,3 inside one it() and because we check in turns: currentConcurrency as well as renderCallbacksCount, I deliberately wrapped the expected value in a meaningful object. Thanks to that the failed test doesn't tell "expected 3 to be 0", but expected { currentConcurrency: 3} to equal { currentConcurrency: 0 }

I suspect I'm solving the readability issue in a fancy way, but the real problem might be somewhere else (e.g. I perform too many `expect`s in one `it`)...

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts (hunk 7 above)
Comment (Platonn) [reply core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: Will do

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts (hunk 8 above)
Comment (Platonn) [reply core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts:280]: Hmmm... To be precise, We don't invoke the render callbacks when the timeout passes. We wait until the render finishes and only then we invoke the callbacks. 
And in case we perceive the render as hanging (due to maxRenderTime), we forget those callbacks and never invoke them.

In ideal design, we should remove those callbacks from the collection when they timeout. Now we have to invoke the callback anyway when the render finishes (even after timeout) - because the callback is responsible for storing the result in the cache if the request timed out.

Further refactor seems quite complex, so we should plan it carefully. TBD

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts (hunk 9 above)
Comment (Platonn) [reply core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: Will do

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts (hunk 11 above)
Comment (Platonn) [reply core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts:351]: Thanks. should be: _don't store value ~it~ in a local variable_

Comment (Platonn) [reply core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts]: Thanks, should be
```suggestion
        // Note: we access the Map at the moment of the render finished (don't store value in a local variable),
```

File: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts [hunk 19]
```diff
@@ -8,6 +8,17 @@ import {
   SsrOptimizationOptions,
 } from './ssr-optimization-options';
 
+export type SsrCallbackFn = (
```
Comment (znikola) [inline core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts:11]: Adding this comment to a random place - as agreed, we will re-add a log statement.

**Review by znikola — CHANGES_REQUESTED** [review]

**Review by znikola — DISMISSED** [review]

**Review by znikola — APPROVED** [review]
