### PR TITLE
fix: Date range validation doesn't work properly #10401

### LINKED ISSUE #10401: Date range validation doesn't work properly
Steps to reproduce:
there are a few ways to see that, but for example:
- open budget like http://localhost:4200/powertools-spa/en/USD/organization/budgets/11
- click edit
- click cancel
- open next budget 123(1232) -> edit
- change start date to next day

Result:
- I can see unexpected validation message
image

Hint:
- Refreshing the page allows to fill form form properly, so probably the reason is because it keeps state from previous form 

Expected result: 
- Form/validation state should be independent from previous values.

### PR DESCRIPTION
**Pull request by Pucek9**
Closes #10401

### CODE REVIEW

File: projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts [hunk 1]
```diff
@@ -140,6 +146,53 @@ export class CustomFormValidators {
 
     return !containsSpecialChars ? null : { cxContainsSpecialCharacters: true };
   }
+
+  /**
+   * TODO
```
Comment (tobi-or-not-tobi) [inline projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts]: ?

File: projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts [hunk 2]
```diff
@@ -140,6 +146,53 @@ export class CustomFormValidators {
...
+        !service.isValidFormat(control.value, pattern)
+      ) {
+        errors.pattern = true;
+      }
+      return Object.keys(errors).length === 0 ? null : errors;
+    };
+  }
+
+  /**
+   * TODO
```
Comment (tobi-or-not-tobi) [inline projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts]: ?

File: projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts [hunk 3]
```diff
@@ -140,6 +146,53 @@ export class CustomFormValidators {
 
     return !containsSpecialChars ? null : { cxContainsSpecialCharacters: true };
   }
+
+  /**
+   * TODO
+   */
+  static datePatternValidation(
+    service: DatePickerService,
```
Comment (tobi-or-not-tobi) [inline projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts]: I won't like to put in a complete service in an argument. What about pass in `isValidFormat: boolean` instead?

File: projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts [hunk 4]
```diff
@@ -140,6 +146,53 @@ export class CustomFormValidators {
...
+    pattern?: string
```
Comment (tobi-or-not-tobi) [inline projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts]: and then we can also drop this 2nd argument

File: projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts [hunk 5]
```diff
@@ -140,6 +146,53 @@ export class CustomFormValidators {
...
+    };
+  }
+
+  /**
+   * TODO
+   */
+  static dateRange(
+    startDateKey: string,
+    endDateKey: string,
+    service: DatePickerService
```
Comment (tobi-or-not-tobi) [inline projects/storefrontlib/src/shared/utils/validators/custom-form-validators.ts]: same here, would be nice to not pass in a service

**Review by tobi-or-not-tobi — CHANGES_REQUESTED** [review]

File: feature-libs/organization/administration/components/budget/form/budget-form.component.html [hunk 6]
```diff
@@ -34,15 +34,17 @@
...
       ></cx-date-picker>
     </label>
 
     <label>
       <span class="label-content">{{ 'orgBudget.endDate' | cxTranslate }}</span>
       <cx-date-picker
         [control]="form.get('endDate')"
-        [min]="form.get('startDate')"
+        [min]="form.get('startDate').value"
+        (update)="form.get('startDate').updateValueAndValidity()"
```
Comment (tobi-or-not-tobi) [inline feature-libs/organization/administration/components/budget/form/budget-form.component.html:47]: Why not keeping the `updateValueAndValidity` in the date picker logic? We had this in the directive, and it makes the date picker easier to use. It will be very hard to know for future date pickers that have min/max relation, that you need to trigger this updateValueAndValidity yourself. 

If we pass in the min/max form control, we can manage this automatically.

**Review by tobi-or-not-tobi — DISMISSED** [review]

File: feature-libs/organization/administration/components/budget/form/budget-form.component.html (hunk 6 above)
Comment (Pucek9) [reply feature-libs/organization/administration/components/budget/form/budget-form.component.html:47]: In my case if someone uses 2 datepickers and would like to make them reactive, he must obvoiusly add this co-validation.

> It makes the date picker easier to use.

yes, but only in case when he uses 2 date pickers (for that case we should have something like DateRangeComponent)

But for use only one datepicker with min/max attributes, customer must play with workarounds (fake date fields with value) 😂

Comment (tobi-or-not-tobi) [reply feature-libs/organization/administration/components/budget/form/budget-form.component.html:47]: Agreed, good point actually.

Comment (tobi-or-not-tobi) [reply feature-libs/organization/administration/components/budget/form/budget-form.component.html:47]: let's go with your solution

**Review by hackergil — APPROVED** [review]
