### PR TITLE
fix: add global msg on apply voucher failure (#14986)

### LINKED ISSUE #14986: No message if a valid coupon cannot be redeemed
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Go to electronics storefront
Enable coupon BUYMORE16 to be redeemed only once and publish it. 
Add a product that's more than $300 to cart
Place the order
Add a camera lens to cart
Go to cart page
Apply the coupon code: BUYMORE16
Place order
Add another camera lens to cart
Apply the coupon code: BUYMORE16

**Actual Result**
There's no feedback to the user what's wrong. In the console, you can see it returning 400.
maximumRedemption

**Expected Result**
Should give the user a message saying that the coupon has reached its maximum redemption or something like that.

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #14986

### CODE REVIEW

**Review by WeizhengSap — DISMISSED** [review]

**Review by WeizhengSap — DISMISSED** [review]

File: feature-libs/cart/base/core/utils/utils.ts [hunk 1]
```diff
@@ -38,6 +38,18 @@ export function isCartNotFoundError(error: ErrorModel): boolean {
...
+}
+
+export function voucherInvalidError(error: ErrorModel): boolean {
+  return error.message === 'coupon.invalid.code.provided';
+}
+
+export function isVoucherError(error: ErrorModel): boolean {
+  return error.type === 'VoucherOperationError';
+}
+
```
Comment (WeizhengSap) [inline feature-libs/cart/base/core/utils/utils.ts:52]: Can you add some unit tests for them, otherwise our test coverage will be lower.

File: docs/migration/5_0.md [hunk 2]
```diff
@@ -381,3 +381,7 @@ The following keys have been added to `configurator-common.ts`:
 #### Template changes
 
 - Top element `<div>` has been changed to `<sector>` to make accesibility navigation consistent. 
+
+### BadRequestHandler
+
```
Comment (WeizhengSap) [inline docs/migration/5_0.md:386]: You also need to add it to REMOVED_PUBLIC_API_DATA. Please check "schematics/src/migrations/5.0".

File: feature-libs/cart/base/core/utils/utils.ts (hunk 1 above)
Comment (BenjaminEmiliani) [reply feature-libs/cart/base/core/utils/utils.ts:52]: Yes! will do

File: docs/migration/5_0.md (hunk 2 above)
Comment (BenjaminEmiliani) [reply docs/migration/5_0.md:386]: done

File: docs/migration/5_0.md [hunk 3]
```diff
@@ -381,3 +381,7 @@ The following keys have been added to `configurator-common.ts`:
...
+- Moved `handleVoucherOperationError` method to new handler, `BadVoucherRequestHandler`
```
Comment (WeizhengSap) [inline docs/migration/5_0.md]: Moved `handleVoucherOperationError` method from `core` to the new handler `BadVoucherRequestHandler` in `cart-lib`.

File: projects/schematics/src/migrations/5_0/removed-public-api-deprecations/removed-public-api-deprecations.ts [hunk 4]
```diff
@@ -13,6 +17,12 @@ export const REMOVED_PUBLIC_API_DATA: DeprecatedNode[] = [
     importPath: SPARTACUS_PRODUCT_CONFIGURATOR_RULEBASED,
     comment: `'${CONFIGURATOR_EVENT_LISTENER} has been removed and is no longer part of the public API. Please use 'ConfiguratorRouterListener' instead`,
   },
+  // projects/core/src/global-message/http-interceptors/handlers/bad-request/bad-request.handler.ts
+  {
+    node: BAD_REQUEST_HANDLER,
+    importPath: SPARTACUS_CORE,
+    comment: `'${HANDLE_VOUCHER_OPERATION_ERROR} has been removed and is no longer part of the public API. Please use new methods in ${BAD_VOUCHER_REQUEST_HANDLER}`,
```
Comment (WeizhengSap) [inline projects/schematics/src/migrations/5_0/removed-public-api-deprecations/removed-public-api-deprecations.ts:24]: '${HANDLE_VOUCHER_OPERATION_ERROR} was moved to `@spartacus/cart-lib/core`.

Comment (BenjaminEmiliani) [reply projects/schematics/src/migrations/5_0/removed-public-api-deprecations/removed-public-api-deprecations.ts:24]: @WeizhengSap Hey Wei, just to clarify, the method named handleVoucherOperationError doesn't exist anymore. In the new file I do not handle voucher error in general, but instead two specific cases. Should I still use your recommended comment?

**Review by WeizhengSap — APPROVED** [review]
