### PR TITLE
fix: Show global message only when the payment method is clicked on

### LINKED ISSUE #13729: During checkout: missing successful global message when user selects different Payment Method
**Describe the bug**
- Screen reader users wouldn't be able to tell if they have switched/selected an additional Payment Method during checkout.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**

1. Log in as a registered user
2. Add items to the cart and start the checkout process.
3. Open any Screen Reader (VO, NVDA, JAWS).
4. Switch Payment Method from default to an additional one.
5. Listen to Screen Reader feedback
6. Hear the absence of confirmation a change has happened.

**Expected behavior**
- Screen reader users will hear a successful confirmation message saying they have changed/selected a different Payment Method. E.g _"Payment Method selection successfully changed"._
- For `MSG_TYPE_CONFIRMATION` use `aria-live="polite" aria-atomic="true"`

**Screenshots**

Message suggestion in the screenshot below, please validate phrasing with @Manurod2018 or @vekterdude

pm-change-2021-09-15_10-22-53

### PR DESCRIPTION
**Pull request by znikola**
fixes #13729

### CODE REVIEW

File: feature-libs/checkout/components/components/payment-method/payment-method.component.ts [hunk 1]
```diff
@@ -158,6 +158,12 @@ export class PaymentMethodComponent implements OnInit, OnDestroy {
   }
 
   selectPaymentMethod(paymentDetails: PaymentDetails): void {
+    this.globalMessageService.add(
+      {
+        key: 'paymentMethods.paymentMethodSelectedSuccess',
```
Comment (bgambocjaviniar) [inline feature-libs/checkout/components/components/payment-method/payment-method.component.ts]: let's remove success from the key since we're using it to display as 'info' to have it vocalized this way instead.

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
As discussed with Miguel,

we fixed the payment method global message bug, where it gets thrown first time when we didn't even select a payment method during the checkout flow with an already existing set payment method.


This PR fixes that problem of bug, however, for future references, we still need to fix things for error thrown and retries to display a proper message (for every other instances in our codebase)

**Review by bgambocjaviniar — APPROVED** [review]
