### PR TITLE
fix: use last added cart entry of given product code in added-to-cart modal

### LINKED ISSUE #9247: Added-to-cart modal shows previous entry when new one has same product code
Depending on the backend setup and settings for a specific product, the product may not be _merged_ to other cart entry with the same product code (i.e. it's the case for configurable products). 

For example if we add such a product twice to the cart (by clicking the "add to cart" button in PDP), then in our cart we will have 2 separate entries with the same product.

The UI problem is that currently our added-to-cart modal  wrongly assumes there can be only one product in the cart of given product code. So after adding a second cart entry with the same product code, it displays the details of the _first_ added cart item of given product code.

But instead we should show the _recently added (last)_ cart entry in the added-to-cart modal.

Note: ideally we shouldn't show the _last_ entry for the product code, but rather base the display on the unique cart entry ID (that we would learn on the success of the OCC to call add-to-cart endpoint). Unfortunately OCC doesn't expose any unique key for cart entries, only the entry number. So we can't implement the ideal solution now.

### PR DESCRIPTION
**Pull request by ChristophHi**
The bug was that currently our added-to-cart modal wrongly assumed there can be only one product in the cart of given product code. So after adding a second cart entry with the same product code, it displayed the details of the _first_ added cart item of given product code.

Now it's fixed - instead we display the _recently added (last)_ cart entry in the added-to-cart modal.

BREAKING CHANGE:
`AddToCartComponent` lost its 2 public members: `this.increment` (use new `this.numberOfEntriesBeforeAdd` instead) and `this.cartEntry$` (use `this.activeCartService.getLastEntry(productCode)` instead).

closes: GH-9247

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts [hunk 1]
```diff
@@ -35,8 +35,7 @@ export class AddToCartComponent implements OnInit, OnDestroy {
 
   hasStock = false;
   quantity = 1;
-  increment = false;
-  cartEntry$: Observable<OrderEntry>;
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts:39]: Removing public/protected members is a breaking change. We need to document it in the migration docs of 3.0. 
FYI I created a ticket for it https://github.com/SAP/spartacus/issues/9286 with milestone 3.0

File: projects/storefrontlib/src/cms-components/cart/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.ts [hunk 2]
```diff
@@ -23,7 +30,12 @@ export class AddedToCartDialogComponent implements OnInit {
   entry$: Observable<OrderEntry>;
   cart$: Observable<Cart>;
   loaded$: Observable<boolean>;
+  addedEntryWasMerged$: Observable<boolean>;
+  /**
+   * @deprecated since 3.0, set numberOfEntriesBeforeAdd instead
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/cart/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.ts:35]: FYI Created ticket to remove it in the next major. https://github.com/SAP/spartacus/issues/9288

**Comment by Platonn** [comment]
✅ e2e regressions passed on local
✅ QA passed, see https://github.com/SAP/spartacus/issues/9247#issuecomment-706216252

**Review by Platonn — APPROVED** [review]
