### PR TITLE
HTML tags in alt attribute of search suggestions image (GH-6279)

### LINKED ISSUE #6279: HTML tags in alt attribute of search suggestions image (cx-media component)
## Environment Details

- Spartacus:  1.4

## Steps to Reproduce
1. Open the spartacus and type in any search including a space, eg. "test a"
2. Inspect the search results HTML and look at the CX-Media component
3. The alt text is malformed

## Observed Results
The image alt text of search suggestions does include HTML tags
Screen Shot 2020-01-28 at 14 19 53

## Expected Results
The image alt text of search suggestions does not include HTML tags

### PR DESCRIPTION
**Pull request by qjimmy**
Closes GH-6279

removes the html from the alt text 
Screen Shot 2020-03-03 at 2 21 16 PM

### CODE REVIEW

File: projects/storefrontlib/src/shared/components/media/media.component.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ export class MediaComponent implements OnChanges {
     this.media = this.mediaService.getMedia(
       this.container,
       this.format,
-      this.alt
+      this.alt.replace(/<.*?>/g, '')
```
Comment (LTiger14) [inline projects/storefrontlib/src/shared/components/media/media.component.ts]: Please add a unit test for this.

I would also add a check that alt exists to avoid errors.

Also fix existing unit test.

**Review by LTiger14 — CHANGES_REQUESTED** [review]

File: projects/storefrontlib/src/shared/components/media/media.service.ts [hunk 2]
```diff
@@ -38,6 +38,7 @@ export class MediaService {
   }
 
   getMedia(container, format?: string, alt?: string): Media {
+    alt = alt ? alt.replace(/<.*?>/g, '') : null;
```
Comment (LTiger14) [inline projects/storefrontlib/src/shared/components/media/media.service.ts]: You can save the regex in a const since you are using it in multiple places.

File: projects/storefrontlib/src/shared/components/media/media.service.spec.ts [hunk 3]
```diff
@@ -87,6 +95,22 @@ describe('MediaService', () => {
     ).toBe('other alt');
   });
 
+  it('should strip the alt of any html tags while keeping the innerHTML text content', () => {
```
Comment (LTiger14) [inline projects/storefrontlib/src/shared/components/media/media.service.spec.ts:98]: Could you also provide another case when the text doesn't change

**Review by LTiger14 — CHANGES_REQUESTED** [review]

**Review by LTiger14 — APPROVED** [review]
