### PR TITLE
test: fix flaky import/export flaky e2e

### LINKED ISSUE #14327: Possible flakiness in Cart Import/Export e2e tests
https://dashboard.cypress.io/projects/k3nmep/analytics/top-failures?branches=%5B%7B%22label%22%3A%22develop%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22regression%2Fcart-import-export.e2e-spec.ts%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%220bcda4a3-023f-4a8a-739f-eefa57925cbc%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222021-10-16%22%2C%22endDate%22%3A%222021-11-15%22%7D&viewBy=TEST_CASE

### PR DESCRIPTION
**Pull request by RadhepS**
Closes: https://github.com/SAP/spartacus/issues/14327

I was experiencing other non-reproducable issues. It seemed to be due to my network as when I changed it I no longer experienced them.

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts [hunk 1]
```diff
@@ -209,19 +209,23 @@ export function verifyImportedData(config: ImportConfig, cart) {
...
-  cy.wait(['@refresh_cart', '@addToCart']);
+  cy.wait(['@refreshCart', '@addToCart']);
 }
 
 /**
  * Goes to the cart page and clicks the button to export cart.
  * @param expectedData will compare the data of the downloaded .csv to the parsed string.
  */
 export function exportCart(expectedData?: string) {
+  cy.intercept('GET', `**ContentPage&pageLabelOrId=%2Fcart**`).as('cart');
```
Comment (RadhepS) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts]: Unsure if this is the best string to use for the intercept

File: projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts [hunk 2]
```diff
@@ -209,19 +209,23 @@ export function verifyImportedData(config: ImportConfig, cart) {
  * @param productCode identifies the unique product to add.
  */
 export function addProductToCart(productCode: string = cart.products[1].code) {
-  cy.intercept('GET', `**/users/*/carts/*?fields=**`).as('refresh_cart');
+  cy.intercept('GET', `**/products/${productCode}**`).as('productPage');
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts]: any time there's a cy.visit page, you should use 

either the function for `waitForProductPage` for product details page or the generic `waitForPage` function, or either waitForSomethingPage specific function in the helper class.

Both functions can be pulled from the checkout helper in `projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts`

Comment (bgambocjaviniar) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts]: For this case, 

do something like

```
const productPage = waitForProductPage(productCode, 'getProductPage');
cy.visit(`/product/${productCode}`);
cy.wait(`@${productPage}`).its('response.statusCode').should('eq', 200);
```

P.S notice there's an extra assertion to make sure we do get a response back, where we check the status code because without it, it will just wait for the request to fire without having it resolved and get a proper response.

`.its('response.statusCode').should('eq', 200);`

File: projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts (hunk 1 above)
Comment (bgambocjaviniar) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts]: same case as above, you can use the generic function to wait for it like 

```
  const cartPage = waitForPage('/cart', 'getCartPage');
  cy.visit('/cart');
  cy.wait(`@${cartPage}`).its('response.statusCode').should('eq', 200);
```

P.S don't forget to have the visit with '/' to make sure it doesn't just relatively add it without putting it as a new path in the url.

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
There's many other instances where we visit the page without waiting for it to resolve like saved-carts listing page as shown in here https://github.com/SAP/spartacus/issues/14327#issuecomment-1012410539

example of things that needs to be updated
https://github.com/SAP/spartacus/blob/3f9ef4d37d7a7e7b531289fb2fb41ae2ed0eb5d7/projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts#L241

**Comment by RadhepS** [comment]
> There's many other instances where we visit the page without waiting for it to resolve like saved-carts listing page as shown in here [#14327 (comment)](https://github.com/SAP/spartacus/issues/14327#issuecomment-1012410539)
> 
> example of things that needs to be updated
> 
> https://github.com/SAP/spartacus/blob/3f9ef4d37d7a7e7b531289fb2fb41ae2ed0eb5d7/projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts#L241

Yeah very true, i'll go ahead and add it to all pages we visit

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
after you're done with above and checking, we'll get over in a quick call on how to improve things more since there are others to do to improve the stability of this test

**Comment by giancorderoortiz** [comment]
This test, prior to this pr,  is not repeatable in pipeline. Please make sure it passes at least 25 times in any dev server, in headless mode, before merging this pr.

**Comment by RadhepS** [comment]
Removed apparel test case as it would require us to create a variant. Modifying the environment base site within the same test is not great as the tests can fail if re-run and the base site is not set back to electronics-spa. I will send a message to the author (Mateusz) on whether I should create a variant for this test case.

File: projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts [hunk 3]
```diff
@@ -286,7 +302,6 @@ export function attemptUpload(csvPath: string) {
     'cx-import-entries-dialog textarea[formcontrolname="description"]'
   ).type('A test description.');
 
-  cy.intercept('GET', '**/users/current/carts/*?**').as('import');
```
Comment (RadhepS) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts:289]: I removed this and do not include a cy.wait() for after the import button is clicked because we have test cases where the import should fail. That means we will never get the saved cart and the cy.wait() would fail.

Comment (bgambocjaviniar) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts:289]: let's talk about this as we might want to check if the product that tried to be added failed and/or have the cart - refreshed after failing an upload

**Comment by bgambocjaviniar** [comment]
Other instances to solidify is to make sure some restore saved carts are restored properly, for example, the function `restoreCart` in the import-export helper class.

Anything that relates to requesting data from the backend, let's make sure to wait for the data

----
we can sync up in a call for this if you'd like again later on

File: projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts (hunk 3 above)
Comment (bgambocjaviniar) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/cart-import-export.ts:289]: nvm

**Comment by bgambocjaviniar** [comment]
@giancorderoortiz we're almost ready to merge it. Waiting on the decision for the variant part of the e2e test

**Review by bgambocjaviniar — APPROVED** [review]

File: projects/storefrontapp-e2e-cypress/cypress/support/utils/login.ts [hunk 4]
```diff
@@ -4,7 +4,9 @@ export const config = {
   revokeTokenUrl: `${Cypress.env('API_URL')}/authorizationserver/oauth/revoke`,
   newUserUrl: `${Cypress.env('API_URL')}/${Cypress.env(
     'OCC_PREFIX'
-  )}/${Cypress.env('BASE_SITE')}/users/?lang=en&curr=USD`,
+  )}/${Cypress.env('BASE_SITE')}/users/?lang=en&curr=${Cypress.env(
+    'BASE_CURRENCY'
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/support/utils/login.ts:8]: So your test passes, but it leaks and makes the others fail

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
added a commit to skip the currency change for now because it's leaking to other e2es, where the currency is now GBP instead of USD

**Review by bgambocjaviniar — APPROVED** [review]
