### PR TITLE
test: Payment methods e2e test failing (GH-6152) - develop

### LINKED ISSUE #6152: Payment methods e2e test failing
mobile/my-account/payment-methods-mobile.e2e-spec.ts
regression/my-account/payment-methods.e2e-spec.ts

This test has been consistently failing on dev-17 as well. Potentially use this opportunity to fix it for good. 

As usual, it cannot find the element with id #deliveryMode-standard-gross, but also has other issues. Console says it is unable to find the text with _**Set As Default**_ and _**Delete**_

Maybe duplicate issue with GH-5867?

### PR DESCRIPTION
**Pull request by bgambocjaviniar**
Closes: GH-6152

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts [hunk 1]
```diff
@@ -1,23 +1,71 @@
...
-    card: 'Mastercard',
-    number: '5400540054005400',
-    expires: {
-      month: '12',
-      year: '2025',
+  addProductToCartViaAutoComplete,
+  addProductToCartViaSearchPage,
+  loginRegisteredUser,
+} from './cart';
+import { addPaymentMethod } from './checkout-as-persistent-user';
```
Comment (LTiger14) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts]: `Import declaration conflicts with local declaration of 'addPaymentMethod'`

Basically there is a function with the same name in this test.

File: projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts [hunk 2]
```diff
@@ -174,20 +132,59 @@ export function deletePayment() {
...
+    addPaymentMethod(testPaymentDetail[0]);
+  });
+
+  it('should render page with only one payment methods', () => {
+    visitHomePage();
+    visitPaymentDetailsPage(isMobile);
+    verifyPaymentCard(1);
+  });
+
+  it('should add product a second product via search', () => {
```
Comment (LTiger14) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts]: This text is not the best

File: projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts [hunk 3]
```diff
@@ -199,23 +196,25 @@ export function paymentMethodsTest() {
...
-  const paymentPage = waitForPage(
-    '/checkout/payment-details',
-    'getPaymentPage'
-  );
-
-  const reviewPage = waitForPage('/checkout/review-order', 'getReviewPage');
-
-  return { shippingPage, deliveryPage, paymentPage, reviewPage };
+function addPaymentMethod(paymentDetail: PaymentDetail) {
+  cy.get('.cx-total')
```
Comment (LTiger14) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts:199]: Why do you add the payment with a request and not using the flow? I guess it's not a problem since the test is for my-account but I want to know why.

Comment (bgambocjaviniar) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts:199]: exactly what you said, the test is for my account and not testing exactly the flow of checkout

Previously, when we were still ducklings for cypress, we did all tests manually, such as navigating to the spot that we want to do. In this case, we were doing checkout to add a payment method in the checkout step since we had no other ways to do this. 

Adding a payment in checkout is being covered in important steps like checkout-flow

**Review by LTiger14 — APPROVED** [review]
