### PR TITLE
fix: While create item with existing ID in system, I dont get any error #10129

### LINKED ISSUE #10041: Creating a B2B user that already exists disables the form
To repro:

- in my company, create a new user
- try to create a new user again, and type the same email address as for the previously created user

Screen Shot 2020-11-27 at 13 20 34

The following happens when clicked on the "Save":

- The error message appears saying "Already Exists". It's not clear what does already exist. The email? (yes, it's the email, I checked in the network tab of the 409 request). Maybe the unit assigned to the new user already has the same user? Or maybe something else? I suggest to change the error message to say e.g. "The email address already exists". (see the screenshot below)
- The form is now disabled. I couldn't change the first / last name, nor the email.

Screen Shot 2020-11-27 at 13 20 41

- Clicking on the "Save" again, causes a bunch of empty error messages to appear in the UI:
Screen Shot 2020-11-27 at 13 20 48

### LINKED ISSUE #10129: While create item with existing ID in system, I dont get any error
- form is freezing if we have error #9351
- we dont have backend errors handling for forms - <s>architecture / some other problems, It looks so easy to do but Tobias would like to use local messages instead of global messages #9791</s>
TODO: handle that error in standard interceptor and display in global message
- we dont have frontend validation for already existing ID's - that is possible, needs to fetch list of all items (to get their ids) from backend <s>(decision required)</s>
Decision: Don't touch now
- other #9325

### PR DESCRIPTION
**Pull request by Pucek9**
Closes #10129 #10041

### CODE REVIEW

**Comment by Pucek9** [comment]
QA steps:
- [ ] Create duplicated budget (code)
- [ ] Update existing budget with other existing code *
- [ ] Create duplicated cost center (code)
- [ ] Update existing cost center with other existing code
- [ ] Create duplicated permission (code)
- [ ] Update existing permission with other existing code *
- [ ] Create duplicated unit (code)
- [ ] Update existing unit with other existing code
- [ ] Create duplicated user (email) -> redirect to user list
- [ ] Update existing user with other existing email 
- [ ] Create duplicated user group (code) 
- [ ] Update existing user group with other existing code

Expecting result: See personalized notification

\* We can't recognize that it's validation error or duplicated id, so displaying Used ID already exists or we met other validation error.
Another way for see this response is e.g. change mustBePositive validator to returns null, and try create budget with negative amount

File: projects/assets/src/translations/en/common.ts [hunk 1]
```diff
@@ -60,7 +60,7 @@ export const common = {
     badGateway: 'A server error occurred. Please try again later.',
     badRequestPleaseLoginAgain: '{{ errorMessage }}. Please login again.',
     badRequestOldPasswordIncorrect: 'Old password incorrect.',
-    conflict: 'Already exists',
+    conflict: 'Used ID already exists.',
```
Comment (mszczepaniak) [inline projects/assets/src/translations/en/common.ts]:
```suggestion
    conflict: 'This Id already exists.',
```

File: projects/core/src/global-message/http-interceptors/handlers/bad-request/bad-request.handler.ts [hunk 2]
```diff
@@ -108,6 +109,68 @@ export class BadRequestHandler extends HttpErrorHandler {
...
   }
 
+  protected handleDuplicated(
+    _request: HttpRequest<any>,
+    response: HttpErrorResponse
+  ): void {
+    this.getErrors(response)
+      .filter(
+        (error) =>
+          error.type === 'ModelSavingError' ||
```
Comment (mszczepaniak) [inline projects/core/src/global-message/http-interceptors/handlers/bad-request/bad-request.handler.ts]: let's move those hardcoded strings to const

**Comment by Pucek9** [comment]
Added only unit tests related to proper handler (Conflict - 409) as content added to Bad request is only workaround

File: projects/core/src/global-message/http-interceptors/handlers/bad-request/bad-request.handler.ts (hunk 2 above)
Comment (Pucek9) [reply projects/core/src/global-message/http-interceptors/handlers/bad-request/bad-request.handler.ts]: image
Unfortunately we haven't implemented this good practice here, I would like to keep consistency and allow to fix that in some kind of global refactor like #8228

File: feature-libs/organization/administration/assets/translations/en/organization.ts [hunk 3]
```diff
@@ -89,6 +89,18 @@ export const organization = {
...
+
+    httpHandlers: {
+      conflict: {
+        budget: 'Budget with code {{ code }} already exists.',
+        costCenter: 'Cost center with code {{ code }} already exists.',
+        unit: 'Organizational unit with uid {{ code }} already exists.',
+        user: 'User with email {{ code }} already exists',
+        userGroup: 'User Group with id {{ code }} already exists',
+        permission: 'Approval Permission with code {{ code }} already exists.',
+        unknown: 'Used ID already exists or we met other validation error.',
```
Comment (dunqan) [inline feature-libs/organization/administration/assets/translations/en/organization.ts]: I appreciate worrying for users here but think it might cause more confusion than it's worth.. 
I would suggest changing it to something more straightforward, and say what we know, not what we guess.

File: feature-libs/organization/administration/core/http-interceptors/bad-request/bad-request.handler.ts [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+  GlobalMessageType,
+  HttpErrorHandler,
+  HttpResponseStatus,
+  Priority,
+} from '@spartacus/core';
+
+@Injectable({
+  providedIn: 'root',
+})
+export class OrganizationBadRequestHandler extends HttpErrorHandler {
```
Comment (dunqan) [inline feature-libs/organization/administration/core/http-interceptors/bad-request/bad-request.handler.ts:14]: We should cover this class with some units tests.

File: feature-libs/organization/administration/core/http-interceptors/conflict/conflict.handler.ts [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+  responseStatus = HttpResponseStatus.CONFLICT;
+
+  hasMatch(errorResponse: HttpErrorResponse): boolean {
+    return (
+      super.hasMatch(errorResponse) && this.getErrors(errorResponse).length > 0
+    );
+  }
+
+  handleError(request: HttpRequest<any>, response: HttpErrorResponse) {
+    if (!this.handleDuplicated(request, response)) {
```
Comment (dunqan) [inline feature-libs/organization/administration/core/http-interceptors/conflict/conflict.handler.ts]: I think we should cover this case in `hasMatch`, if we are not able to handle the error, then `hasMatch` should return false, and leave fallback to the global mechanism.

File: feature-libs/organization/administration/core/http-interceptors/bad-request/bad-request.handler.ts (hunk 4 above)
Comment (Pucek9) [reply feature-libs/organization/administration/core/http-interceptors/bad-request/bad-request.handler.ts:14]: Even if it's something which will be removed soon? https://github.com/SAP/spartacus/pull/10254#issuecomment-741752096

Comment (dunqan) [reply feature-libs/organization/administration/core/http-interceptors/bad-request/bad-request.handler.ts:14]: I would say yes, if we want to merge it to develop (and especially if we plan to include it in the final release)

**Review by dunqan — DISMISSED** [review]

**Review by dunqan — DISMISSED** [review]

**Review by dunqan — APPROVED** [review]
