### PR TITLE
chore: fix the compilation error in BannerComponent when strict mode enabled

### LINKED ISSUE #15013: Problems with extend BannerComponent
**Describe the bug**
Observed here: https://stackoverflow.com/questions/71030337/not-able-to-use-cx-media-component-with-a-media-container
I can see TS compilation errors while try extends BannerComponent. It's related to used wrong types:
- Type 'string | undefined' is not assignable to type 'string | any[]'. `[url]="data.urlLink"`
- Type 'string | null' is not assignable to type 'string' `[target]="getTarget(data)"`
- Type 'CmsBannerComponentMedia | CmsResponsiveBannerComponentMedia | undefined' is not assignable to type 'MediaContainer'.
  Type 'undefined' is not assignable to type 'MediaContainer'.  ` [container]="data.media"`

**Tell us the version of Spartacus**
- Library version: 4.3

**To Reproduce**

1 Create a new Angular app, add Spartacus by schematics, set any possible backend
2 Add own MyBannerComponent extends BannerComponent, use copied template from BannerComponent
3 Try to compile
4 See error list:
```
Error: src/app/my-banner/my-banner.component.html:3:4 - error TS2322: Type 'string | undefined' is not assignable to type 'string | any[]'.
  Type 'undefined' is not assignable to type 'string | any[]'.

3   [url]="data.urlLink"
     ~~~

  src/app/my-banner/my-banner.component.ts:6:16
    6   templateUrl: './my-banner.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component MyBannerComponent.


Error: src/app/my-banner/my-banner.component.html:4:4 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

4   [target]="getTarget(data)"
     ~~~~~~

  src/app/my-banner/my-banner.component.ts:6:16
    6   templateUrl: './my-banner.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component MyBannerComponent.


Error: src/app/my-banner/my-banner.component.html:7:14 - error TS2322: Type 'CmsBannerComponentMedia | CmsResponsiveBannerComponentMedia | undefined' is not assignable to type 'MediaContainer'.
  Type 'undefined' is not assignable to type 'MediaContainer'.

7   <cx-media [container]="data.media"></cx-media>
               ~~~~~~~~~

  src/app/my-banner/my-banner.component.ts:6:16
    6   templateUrl: './my-banner.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component MyBannerComponent.

```

**Expected behavior**
The component should compile properly, without any input.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome

**Additional context**
- Analogical issue for the different component: https://github.com/SAP/spartacus/issues/13652

### PR DESCRIPTION
**Pull request by WeizhengSap**
close #15013

### CODE REVIEW

File: projects/storefrontlib/cms-components/content/banner/banner.component.ts [hunk 1]
```diff
@@ -25,4 +25,14 @@ export class BannerComponent {
   getTarget(data: CmsBannerComponent): string | null {
     return data.external === 'true' || data.external === true ? '_blank' : null;
   }
+
+  getImage(data: CmsBannerComponent): Image | ImageGroup | undefined {
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/cms-components/content/banner/banner.component.ts:29]: instead of doing this to make `type assert` into something else, maybe let's just include this use case to the typing of the container in `media.component.ts`.

I believe we should include `CmsBannerComponentMedia | CmsResponsiveBannerComponentMedia` in it as well. 
My reason for this is we are normalizing the media container and resolving it down the line in the data flow (from MediaService), so I think we shouldn't manipulate the type assertion like this since actual data that was passed is either `CmsBannerComponentMedia` or `CmsResponsiveBannerComponentMedia`. Only reason this is working is because those interfaces are optional and it contains the url property. 

what do you think?

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]

File: projects/storefrontlib/cms-components/content/banner/banner.component.ts (hunk 1 above)
Comment (bgambocjaviniar) [reply projects/storefrontlib/cms-components/content/banner/banner.component.ts:29]: forget what I said. Let's merge it but a reminder to fix all typings down the chain during the strict mode work phase

**Review by bgambocjaviniar — APPROVED** [review]
