### PR TITLE
fix: Extra job to run pwa schematics

### LINKED ISSUE #10386: Collection "@angular/pwa" cannot be resolved
**Describe the bug**
When adding Spartacus to a new project using schematics, it failed with and error `Collection "@angular/pwa" cannot be resolved`

**Tell us the version of Spartacus**
- Spartacus 3.0.0-rc.3

**To Reproduce**
1. Create a new project `ng new [projectname] --style=scss
2. `cd [projectname]`
2. Add latest RC (3 at the time of the creation of this bug) `ng add @spartacus/schematics@rc --pwa --ssr`
3. Observe the error `Collection "@angular/pwa`

Screen Shot 2020-12-11 at 2 31 27 PM

**Expected behavior**
Spartacus should be added without any errors 

**Desktop (please complete the following information):**
- Any terminal window

**Additional context**
This issue was discovered while trying to deploy the latest RC (Spartacus 3.0.0-rc.3) to CCV2. Due to this error, the deployment is blocked

### PR DESCRIPTION
**Pull request by marlass**
Closes #10386

### CODE REVIEW

File: projects/schematics/src/add-pwa/index.ts [hunk 1]
```diff
@@ -108,9 +90,37 @@ function updateAppModule(options: any): Rule {
 }
 
 export function addPWA(options: SpartacusOptions): Rule {
+  return (tree: Tree, context: SchematicContext) => {
+    const dependencies = [
+      {
+        type: NodeDependencyType.Dev,
+        version: '^0.1001.0',
+        name: '@angular/pwa',
```
Comment (LTiger14) [inline projects/schematics/src/add-pwa/index.ts:98]: Not necessarily a blocker could we add a const for this?

File: projects/schematics/src/add-pwa/index.ts [hunk 2]
```diff
@@ -108,9 +90,37 @@ function updateAppModule(options: any): Rule {
...
+      },
+    ];
+    return chain([
+      addPackageJsonDependencies(dependencies),
+      invokeAfterAddPWATask(options),
+    ])(tree, context);
+  };
+}
+
+function invokeAfterAddPWATask(options: SpartacusOptions): Rule {
```
Comment (LTiger14) [inline projects/schematics/src/add-pwa/index.ts:108]: For the future, there is a similar function in `lib-utils` could we change the shared functions so it can be used for this and future changes of the kind?

**Review by LTiger14 — APPROVED** [review]
