### PR TITLE
fix: add global message on sign out (#13700)

### LINKED ISSUE #13700: Missing successful global message when users Sign Out
**Describe the bug**

- Screen reader users wouldn't be able to tell if they have in fact signed out.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Open any Screen Reader (VO, NVDA, JAWS).
2. Sign in as a user.
3. Got My Account > Sign Out
4. Hear the absence of a confirmation message the user has signed out.

**Expected behavior**
- Screen reader users will hear a successful confirmation message as they sign out. E.g _"You have successfully signed out"._
- For `MSG_TYPE_CONFIRMATION` use `aria-live="polite" aria-atomic="true"`

**Screenshots**
Screen Shot 2021-09-13 at 7 50 25 PM

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #13700

### CODE REVIEW

File: projects/assets/src/translations/en/user.ts [hunk 1]
```diff
@@ -29,4 +29,7 @@ export const user = {
     emailIsRequired: 'Invalid email format',
     emailsMustMatch: 'Email does not match',
   },
+  messages: {
```
Comment (marlass) [inline projects/assets/src/translations/en/user.ts]: I would rename this translation chunk to `logout`. `messages` are to generic

File: projects/core/src/auth/user-auth/facade/auth.service.ts [hunk 2]
```diff
@@ -92,6 +94,10 @@ export class AuthService {
     return new Promise((resolve) => {
       this.oAuthLibWrapperService.revokeAndLogout().finally(() => {
         this.store.dispatch(new AuthActions.Logout());
+        this.globalMessageService?.add(
+          { key: 'messages.signedOutSuccessfully' },
+          GlobalMessageType.MSG_TYPE_CONFIRMATION
+        );
```
Comment (marlass) [inline projects/core/src/auth/user-auth/facade/auth.service.ts]: I would add a parameter to the `coreLogout` method, so with each call, we can decide if we want to show this message or not.

For example. I would not like to show this message if we logout user, because his access token expired.

**Review by marlass — CHANGES_REQUESTED** [review]

File: projects/assets/src/translations/en/user.ts (hunk 1 above)
Comment (BenjaminEmiliani) [reply projects/assets/src/translations/en/user.ts]: @marlass  I see what you mean, but in the future I was thinking of adding the successful login message to that chunk as well. So maybe something else like `sessionStatus` or `sessionMessage`?

Comment (marlass) [reply projects/assets/src/translations/en/user.ts]: `authMessages` could work for me

Comment (BenjaminEmiliani) [reply projects/assets/src/translations/en/user.ts]: Changed to authMessages

File: projects/core/src/auth/user-auth/facade/auth.service.ts (hunk 2 above)
Comment (BenjaminEmiliani) [reply projects/core/src/auth/user-auth/facade/auth.service.ts]: Added optional parameter.

File: projects/core/src/auth/user-auth/facade/auth.service.ts [hunk 3]
```diff
@@ -10,6 +10,7 @@ import { AuthStorageService } from '../services/auth-storage.service';
 import { OAuthLibWrapperService } from '../services/oauth-lib-wrapper.service';
 import { AuthActions } from '../store/actions/index';
 import { UserIdService } from './user-id.service';
+import { GlobalMessageService, GlobalMessageType } from '@spartacus/core';
```
Comment (marlass) [inline projects/core/src/auth/user-auth/facade/auth.service.ts]: These import paths should be relative

File: projects/core/src/auth/user-auth/facade/auth.service.ts [hunk 4]
```diff
@@ -85,13 +87,20 @@ export class AuthService {
   /**
    * Revokes tokens and clears state for logged user (tokens, userId).
    * To perform logout it is best to use `logout` method. Use this method with caution.
+   * @param showGlobalMsg show a successful global message upon sign out.
    */
-  coreLogout(): Promise<void> {
+  coreLogout(showGlobalMsg?: boolean): Promise<void> {
```
Comment (marlass) [inline projects/core/src/auth/user-auth/facade/auth.service.ts]:
```suggestion
  coreLogout(showGlobalMsg = true): Promise<void> {
```

Can we provide `true` as a default?

And in this case can you pass `false` value where we call it in `AuthHttpHeaderService` and in `UpdateEmailComponentService`.

For these 2 cases, it doesn't make sense to show this message.

**Review by marlass — CHANGES_REQUESTED** [review]

**Review by marlass — DISMISSED** [review]

**Review by dydome — CHANGES_REQUESTED** [review]
please provide migration doc

File: docs/migration/5_0.md [hunk 5]
```diff
@@ -40,3 +40,12 @@ under the section `headerDisplayOnly`.
...
 
 - `configurator.addToCart.buttonDisplayOnly` was added to `configurator-common.ts`
+
+### AsmAuthService
+
+- `coreLogout()` method was modified to trigger a global message by default. `showGlobalMsg: false` parameter can be passed to opt-out of the default global message.
+
+### AuthService
+
+- One new required constructor parameter `globalMessageService: GlobalMessageService`
```
Comment (psmul) [inline docs/migration/5_0.md]:
```suggestion
- Added `GlobalMessageService` to constructor.
```

Comment (BenjaminEmiliani) [reply docs/migration/5_0.md:50]: @psmul Is this okay:

`GlobalMessageService` is a new, required constructor dependency.

**Review by psmul — DISMISSED** [review]

**Review by dydome — DISMISSED** [review]

**Review by hackergil — APPROVED** [review]
