### PR TITLE
fix: fix store hours mapping (GH-11366)

### LINKED ISSUE #11366: Store Finder Opening Hours do not Work in SSR Context
**Describe the bug**
With ticket #10302, the storefinder opening hours where fixed to work for languages other than english. In the fix, the code `this.winRef?.sessionStorage?.getItem('language')` was used to get the current language. The problem with this line is, that sessionStorage is not available in SSR context. Therefore, for the initial page reload on the storefinder store page, the opening Hours are again being displayed with "-".

**Tell us the version of Spartacus**
- Library version: 3.1.0

**To Reproduce**
1. Use a fresh instance of Spartacus
2. Start it in SSR Mode
3. Open the Store Finder Detail page in an ingcognito window (where you have never selected a language via Language Dropdown)
4. See the opening hours not being displayed, but just "-"

**Expected behavior**
The Opening Hours are also displayed for the initial Request in SSR mode

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

Please also see ticket #11367, which is kinda related..

### PR DESCRIPTION
**Pull request by Parthlakhani**
closes #11366 and #11367 

Used store hours coming from backed directly rather than mapping in frontend
Deprecate unused functions

### CODE REVIEW

File: feature-libs/storefinder/components/schedule-component/schedule.component.ts [hunk 1]
```diff
@@ -28,14 +32,19 @@ export class ScheduleComponent implements OnChanges {
   }
 
   /**
+   * @deprecated since 3.1
```
Comment (LTiger14) [inline feature-libs/storefinder/components/schedule-component/schedule.component.ts]: One small note for all the deprecated functions you could add a little text that explains what people should use instead.

File: feature-libs/storefinder/core/facade/store-data.service.ts [hunk 2]
```diff
@@ -40,10 +40,13 @@ export class StoreDataService {
   }
```
Comment (LTiger14) [inline feature-libs/storefinder/core/facade/store-data.service.ts:41]: Could this whole service be removed for 4.0? The few methods that still have some use could be moved to the `StoreFinderService`

File: feature-libs/storefinder/components/schedule-component/schedule.component.ts [hunk 3]
```diff
@@ -9,13 +10,16 @@ const WEEK_DAYS_NUMBER = 7;
 })
 export class ScheduleComponent implements OnChanges {
   @Input()
-  location: any;
+  location: PointOfService;
   displayDays: Date[] = null;
```
Comment (LTiger14) [inline feature-libs/storefinder/components/schedule-component/schedule.component.ts:18]: You can probably also deprecate `displayDays` and mark some of the login in the `ngOnChanges` for deprecation with a simple TODO and your ticket number.

File: feature-libs/storefinder/components/schedule-component/schedule.component.html [hunk 4]
```diff
@@ -1,16 +1,15 @@
...
-      {{ getStoreClosingTime(day) }}
-    </div>
-    <div
-      *ngIf="getStoreOpeningTime(day) === 'closed'"
-      class="cx-hours col-8 closed"
-    >
+  <div *ngFor="let day of weekDays" class="row">
+    <div class="cx-days col-4">{{ day.weekDay }}</div>
+
+    <div *ngIf="day.closed === true" class="cx-hours col-8 closed">
```
Comment (LTiger14) [inline feature-libs/storefinder/components/schedule-component/schedule.component.html]: Since it's a boolean you can just use `day.closed` or `!day.close`.

**Review by LTiger14 — CHANGES_REQUESTED** [review]

File: feature-libs/storefinder/core/facade/store-data.service.ts (hunk 2 above)
Comment (Parthlakhani) [reply feature-libs/storefinder/core/facade/store-data.service.ts:41]: yes, that would be a good choice

**Review by LTiger14 — APPROVED** [review]
