### PR TITLE
fix: update-schematics - add migration data for ProductFacetNavigationComponent

### LINKED ISSUE #7647: Component schematics missing for ProductFacetNavigationComponent
The `ProductFacetNavigationComponent` was heavily refactored in 2.0.

The component is missing component schematics for the public methods in properties that were removed. In case these are used in custom html it would cause errors.

Example of the properties/methods:

- searchResult$
- toggleValue(‘’)
- visibleFacets$
- isFacetCollapsed([…])
- getVisibleFacetValues([…])
- showMore()
- minPerFacet
- showAllPerFacetMap

### PR DESCRIPTION
**Pull request by znikola**
closes #7647

### CODE REVIEW

File: projects/schematics/src/migrations/2_0/component-deprecations/data/product-facet-navigation-component.migration.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+      name: 'visibleFacets$',
+      comment: `'visibleFacets$' property has been removed. Please refer to the migration guide on how to handle this change.`,
+    },
+    {
+      name: 'toggleValue',
+      comment: `'toggleValue' method has been removed. Please refer to the migration guide on how to handle this change.`,
+    },
+    {
+      name: 'minPerFacet',
+      comment: `'minPerFacet' method has been removed. Please refer to the migration guide on how to handle this change.`,
```
Comment (marlass) [inline projects/schematics/src/migrations/2_0/component-deprecations/data/product-facet-navigation-component.migration.ts]:
```suggestion
      comment: `'minPerFacet' property has been removed. Please refer to the migration guide on how to handle this change.`,
```

File: projects/schematics/src/migrations/2_0/component-deprecations/data/product-facet-navigation-component.migration.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    },
+    {
+      name: 'showAllPerFacetMap',
+      comment: `'showAllPerFacetMap' method has been removed. Please refer to the migration guide on how to handle this change.`,
```
Comment (marlass) [inline projects/schematics/src/migrations/2_0/component-deprecations/data/product-facet-navigation-component.migration.ts]: property instead of method

**Review by marlass — CHANGES_REQUESTED** [review]
What about these property: `activeFacetValueCode`?

File: projects/schematics/package.json [hunk 3]
```diff
@@ -22,13 +22,15 @@
     "@nguniversal/express-engine": "^9.1.0",
     "@schematics/angular": "^9.1.0",
     "@schematics/update": "^0.901.0",
-    "@types/jasmine": "^3.5.0",
-    "@types/node": "^12.11.1",
-    "@types/shelljs": "^0.8.7",
     "jasmine": "^3.5.0",
```
Comment (marlass) [inline projects/schematics/package.json]: Do you think we should also move jasmine and typscript?

**Review by marlass — APPROVED** [review]
