### PR TITLE
Fixing flaky applied promotions e2e test

### LINKED ISSUE #7523: Flaky applied-promotions e2e test
This test is currently part of flaky group. Check if it is still flaky, check if it is not to slow and if everything is fine introduce it into regression group (change flaky-e2e-spec extenstion to e2e-spec)

### PR DESCRIPTION
**Pull request by hackergil**
Fixes #7523

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts [hunk 1]
```diff
@@ -67,9 +78,9 @@ export function selectPaymentMethod() {
     .should('not.be.empty');
   cy.get('.cx-card-title').should('contain', '✓ DEFAULT');
   cy.get('.card-header').should('contain', 'Selected');
+  waitForPage('/checkout/review-order', 'reviewOrder');
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts]: I'd like this to store the alias in a variable to be used in line 83

For example: https://github.com/SAP/spartacus/pull/12440/files#diff-091683f038132765619a1bc2f98b544dc6c2ecc944246c89595ef1db3c5010afR19

**Review by bgambocjaviniar — CHANGES_REQUESTED** [review]
LGTM, ran it multiple times (15 times to be exact)

Screen Shot 2021-05-17 at 1 13 38 PM

but I'd like one change before approving, which can be found below/above

File: projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts (hunk 1 above)
Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts]: Done

**Review by bgambocjaviniar — DISMISSED** [review]

**Review by bgambocjaviniar — APPROVED** [review]
