### PR TITLE
fix: Utilize automatic Multi-Site Configuration in the install script

### LINKED ISSUE #8051: Check whether installation script can handle setup without baseSite given
Currently installation script use `baseSite=electronics-spa` param to set up the app as given. However it's a bit tricky to set up multisite app on the same machine (language/currency clash problem appears) so let's check can we utilize autoconfig feature (context not present in the URL) with the script.

### PR DESCRIPTION
**Pull request by mirkosoft**
In order to be able to install multi-site setup `baseSite` param has been removed from the script's schematics command (which implies using CMS to fetch site context config based on url/host).

closes #8051

### CODE REVIEW

File: scripts/install/run.sh [hunk 1]
```diff
@@ -96,15 +96,15 @@ function create_ssr_pwa {
 }
 
 function add_spartacus_csr {
-    ( cd ${INSTALLATION_DIR} && cd csr && ng add @spartacus/schematics@${SPARTACUS_VERSION} --overwriteAppComponent true --baseSite ${BASE_SITE} --baseUrl ${BACKEND_URL} --currency ${CURRENCY} --occPrefix ${OCC_PREFIX} )
```
Comment (marlass) [inline scripts/install/run.sh:99]: I think we can also remove these 2 variables from the `config.default.sh`

**Review by marlass — CHANGES_REQUESTED** [review]
Tested and everything seems to work correctly :)

Just address this one note about removing this variables from the default config before merging this one to develop ;)

File: scripts/install/run.sh (hunk 1 above)
Comment (marlass) [reply scripts/install/run.sh:99]: `BASE_SITE` and `CURRENCY`

**Review by marlass — APPROVED** [review]
