### PR TITLE
fix: reference items by entry number (GH-9134)

### LINKED ISSUE #9134: [quantity counter issue] Cart with multiple entries with the same product working wrong
**Describe the bug**
If there is situation that in cart there are different entries but with the same product. Counter is working wrong, it is getting from first entry product quantity. Once you are inceasing or decreasing product count it is also updating another entry.

**To Reproduce**
(It is not possible to reproduce without Hybris/BE setup)
1. Create promotion that if you add for example 10 the same products to cart you will get 1 exactly the same product as bonus
2. You should see new entry in cart with the same product
3. Item counter will show for both entries value 10
4. If you increase main product quantity by 1 you will see the same quantity value for second entry.

**Expected behavior**
There should be no reference between same products in different entries in cart. If you update quantity for one product it should update only this entry.

**Desktop (please complete the following information):**
OS: Windows 10 Pro
Browser Google Chrome 5.0.4183.121 version
Spartacus Version 2.0.5

**Additional context**
In ``CartItemListComponent`` there is ``createForm`` method with is creating FormControl with key as product code. Which in described scenario above will create multiple FormControl with the same key as productCode. As right now there is no other uniqe parameter for product or for entry. FormControl should be generated with entryNumber as key. THan method ``getControl`` will not broke the cart.

### PR DESCRIPTION
**Pull request by ChristophHi**
Items have been referenced by product code before, this caused issues when multiple items with the same product code were present in the cart. Now items are referenced by their (unique) entry number.

BREAKING CHANGE:
The cart item list component has a new public method getControlName. It is used to determine the control name for the control groups representing the items, previously the control name was the item's product code

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts [hunk 1]
```diff
@@ -94,17 +94,21 @@ export class CartItemListComponent {
     });
   }
 
+  getControlName(item: Item): string {
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts]: Since it's not used in the html, can we make it `protected`?

File: projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts [hunk 2]
```diff
@@ -82,9 +82,9 @@ export class CartItemListComponent {
   private createForm(): void {
     this.form = new FormGroup({});
     this._items.forEach((item) => {
-      const { code } = item.product;
+      const code = this.getControlName(item);
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts]: Nitpick: for consistency, we may rename the variable to `controlName`

**Review by Platonn — APPROVED** [review]

**Comment by ChristophHi** [comment]
Closes GH-9134
