### PR TITLE
Flaky anonymous consent e2e test

### LINKED ISSUE #12265: [MASTER] Flaky e2e tests list
List of e2e tests marked as `flaky`. Please add your name next to the test you are fixing

### Pending

- [ ] #9153 accessibility/tabbing-order.flaky-e2e-spec.ts **need to be worked once all other e2es are done. Each tabbing order test needs to be part of its own feature. This spec needs to be redistributed.***

### In progress

- [x] #12269 regression/anonymous-consents/anonymous-consents-flow.flaky-e2e-spec.ts (@hackergil)
- [x] #7523 regression/applied-promotions.flaky-e2e-spec.ts (@hackergil)
- [x] #12270 regression/site-context/language/language-checkout-page.flaky-e2e-spec.ts (@WeizhengSap )
- [x] #8215 regression/site-context/language/language-my-account-pages.flaky-e2e-spec.ts (@WeizhengSap )
- [x] #12271 regression/site-context/language/language-cart-page.flaky-e2e-spec.ts (@WeizhengSap )
- [x] #12272 regression/site-context/currency/currency-product-search.flaky-e2e-spec.ts (@bgambocjaviniar)
- [x] #12266 b2b/regression/replenishment/b2b-replenishment-checkout-flow (@bgambocjaviniar)
- [x] #7519 regression/coupon/coupon.flaky-e2e-spec.ts (@hackergil)
- [x] #7520 regression/my-coupons/my-coupons.flaky-e2e-spec.ts (@hackergil)
- [x] #12267 b2b/regression/my-company/units.flaky-e2e-spec.ts (@Pucek9) 
- [x] #11107 b2b/regression/my-company/users.flaky-e2e-spec.ts (@Pucek9) 
- [x] #11042 b2b/regression/my-company/user-groups.flaky-e2e-spec.ts (@Pucek9)

### LINKED ISSUE #12269: Flaky test regression/anonymous-consents/anonymous-consents-flow.flaky-e2e-spec.ts

### PR DESCRIPTION
**Pull request by hackergil**
Fixes #12269

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/anonymous-consents.ts [hunk 1]
```diff
@@ -227,81 +213,63 @@ export function giveRegistrationConsentTest() {
 }
 
 export function movingFromAnonymousToRegisteredUser() {
-  it('should transfer anonoymous consents when registered', () => {
-    openDialogUsingFooterLink();
+  it('should transfer anonymous consents and load the previously given registered consents when registered', () => {
+    openAnonymousConsentsDialog();
+    cy.log('Giving second consent as anonymous user');
```
Comment (plabadie) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/anonymous-consents.ts:218]: There is a `cy.log` here, in case it was not left there on purpose.

**Review by plabadie — APPROVED** [review]
