### PR TITLE
fix: i18n when using JSON in SSR - set `reloadInterval: false`

### LINKED ISSUE #14372: JSON translations don't work in SSR Spartacus 4.x
Hello,

I am opening a bug after creating a topic [here](https://stackoverflow.com/questions/69977308/backend-translations-dont-work-in-ssr-spartacus).

I have implemented the Lazy Loading of the translations as in this [guide](https://sap.github.io/spartacus-docs/i18n/#lazy-loading). If I run the application in SSR mode it always falls back in CSR, even if I increase the timeout to over 1 minute.
If I remove the backend configuration and restore the static files, the SSR works fine.
This issue occurs on both version 4.1 and 4.2 of Spartacus.

Steps to reproduce:
```
ng new electronics-spa --style=scss --package-manager yarn
cd electronics-spa/
ng add @spartacus/schematics@latest --baseUrl https://spartacus-demo.eastus.cloudapp.azure.com:8443 --baseSite=electronics-spa --currency=USD --language=en --ssr --skip-confirmation
cp ./node_modules/@spartacus/assets/i18n-assets ./src/assets -r
```

(I am using of course mine SAP Cloud baseUrl)

Change the file `src/app/spartacus/spartacus-configuration.module.ts` in this way (as per the documentation):

```
providers: [
  provideConfig({
    i18n: {
      backend: {
        loadPath: 'assets/i18n-assets/{{lng}}/{{ns}}.json',
      },
      chunks: translationChunksConfig,
    },
  }),
];
```

Then finally run
```
yarn build:ssr
yarn serve:ssr
```

And when you open the application in the browser it will fall back in the CSR mode without any error on server side.
If you revert the spartacus-configuration.module.ts and re-build and re-run the application, SSR works fine.

I have created a simple repo that reproduces the error: https://github.com/fgrecchi-aswatson/spartacus-ssr-issue

Thanks
Filippo Grecchi

### PR DESCRIPTION
**Pull request by Platonn**
Previously, the periodical reloading of JSON translations in SSR was enabled by default by `i18next-http-backend`. The never-ending async task `setInterval()` invoked inside `i18next-http-backend` caused the SSR to hang.

To prevent it, we're setting explicitly `reloadInterval: false` in the options of `i18next`.

fixes #14372

### CODE REVIEW

File: projects/core/src/i18n/i18next/i18next-init.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export function i18nextInit(
   configInit: ConfigInitializerService,
   languageService: LanguageService,
   httpClient: HttpClient,
-  serverRequestOrigin: string,
+  serverRequestOrigin: string | null,
```
Comment (Platonn) [inline projects/core/src/i18n/i18next/i18next-init.ts:19]: just fixed typing by the way. SERER_REQUEST_ORIGIN is `@Optional`

**Review by znikola — APPROVED** [review]
