### PR TITLE
test: fix flaky results for wish-list (#14131)

### LINKED ISSUE #14131: Fix flaky wishlist e2e test

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #14131

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts [hunk 1]
```diff
@@ -31,39 +31,47 @@ export function fillShippingAddress(
...
-      cy.get('.region-select[formcontrolname="isocode"]').ngSelect(
-        shippingAddress.address.state
-      );
-    }
-    cy.get('[formcontrolname="postalCode"]')
-      .clear()
-      .type(shippingAddress.address.postal);
-    cy.get('[formcontrolname="phone"]').clear().type(shippingAddress.phone);
-    if (submitForm) {
+  cy.wait(1000);
```
Comment (dydome) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts]: is there any way to avoid the static wait? Maybe use wait for page here? I was warned to not use wait with static time :(

File: projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts [hunk 2]
```diff
@@ -31,39 +31,47 @@ export function fillShippingAddress(
...
+            shippingAddress.address.state
+          );
+        }
+        cy.get('[formcontrolname="postalCode"]')
+          .clear()
+          .type(shippingAddress.address.postal);
+        cy.get('[formcontrolname="phone"]').clear().type(shippingAddress.phone);
+        if (submitForm) {
+          cy.get('button.btn-primary').click({ force: true });
+          cy.wait(1000);
```
Comment (dydome) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts]: the same a s above

File: projects/storefrontapp-e2e-cypress/cypress/helpers/wish-list.ts [hunk 3]
```diff
@@ -191,10 +193,14 @@ export function checkWishListPersisted(product: TestProduct) {
 
 export function goToProductPage(product: TestProduct) {
   const productPage = waitForProductPage(product.code, 'productPage');
-  getWishListItem(product.name).within(() => {
-    cy.get('.cx-name>.cx-link').click({ force: true });
-  });
-  cy.wait(`@${productPage}`);
+  waitForGetWishList();
+  cy.wait(1000);
```
Comment (dydome) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/wish-list.ts]: the same a s above

**Review by dydome — CHANGES_REQUESTED** [review]

File: projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts (hunk 1 above)
Comment (BenjaminEmiliani) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts]: I will look into it

**Review by dydome — APPROVED** [review]
