### PR TITLE
feat: fix visual focus for mouse users

### LINKED ISSUE #8366: Unexpected visible focus for mouse users
In general, mouse users should not see the visible focus indicator that is added for keyboard-only users. We've introduced this feature with #6879, but there are a few occassions where mouse users still see the visual focus: 
- in case a OS command is used (i.e. CMD+TAB to navigate to another application)
- in case the user enters a form input

With the new b2b my account, where multiple forms are used, this becomes more and more visible, hence we like to get this out of he way soon.

### PR DESCRIPTION
**Pull request by tobi-or-not-tobi**
Fixing a few glitches where mouse users would still see visual focus on elements: 
- In case a OS command is used (i.e. CMD+TAB to navigate to another application)
- in cases wheree the user fills in a form

fixes #8366

### CODE REVIEW

File: projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts [hunk 1]
```diff
@@ -23,13 +23,29 @@ export class VisibleFocusDirective extends BaseFocusDirective {
...
     return this.config?.disableMouseFocus;
   }
+
+  /**
+   * Indicates whether the current event is driven by the mouse or the keyboard.
+   *
+   * If the keyboard is used to navigate the OS or the browser, or used ot fill in a form,
+   * we consider the event to be a mouse event.
+   */
+  protected isMouseEvent(event: KeyboardEvent): boolean {
```
Comment (Platonn) [inline projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts]: IMO it can be a bit misleading to treat and name a 'mouse event' the subset of the exceptional keyboard events.

You know the family of the focus directives best. What do you think about adding another host binding and CSS class just for exceptional keyboard events? For example `.keyboard-focus-hidden`. 
As an alternative, we could deprecate `mouse`-related nomenclature in favour of `visible-focus`, i.e. `.no-visible-focus` CSS class and `disableVisibleFocus` config property instead of `disableMouseFocus`?

File: projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts [hunk 2]
```diff
@@ -23,13 +23,29 @@ export class VisibleFocusDirective extends BaseFocusDirective {
...
+    return (
+      event.code === 'Tab' ||
+      !(
+        event.metaKey ||
+        (this.mouseFocus && (event.target as HTMLElement).tagName === 'INPUT')
```
Comment (Platonn) [inline projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts]: I'm not sure I understand why setting the new value for `this.mouseFocus` depends on the previous value of the `this.mouseFocus`

Comment (tobi-or-not-tobi) [reply projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts]: This is needed to distinquish the keyboard user from mouse user. The keyboard user will keep the focus styling, where as the keyboard user won't.

File: projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts (hunk 1 above)
Comment (tobi-or-not-tobi) [reply projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts]: Agreed. I'm not fond of yet another binding, but like the name improvement. I'll deprecate as you suggest and introduce a better name.

File: projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts [hunk 3]
```diff
@@ -15,21 +15,50 @@ export class VisibleFocusDirective extends BaseFocusDirective {
...
-    if (this.shouldFocusVisible) {
-      this.mouseFocus = false;
+  @HostListener('keydown', ['$event']) handleKeydown(event: KeyboardEvent) {
+    if (this.shouldDisableVisibleFocus) {
+      this.hideVisibleFocus = !this.isMouseEvent(event);
+      this.mouseFocus = !this.isMouseEvent(event);
     }
   }
 
-  protected get shouldFocusVisible(): boolean {
```
Comment (Platonn) [inline projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts:32]: Renaming the already existing protected method is a breaking change

**Review by Platonn — APPROVED** [review]
