### PR TITLE
fix: update schematics - fix angular localize migration script 

### LINKED ISSUE #7542: Fix angular/localize update schematic
The update schematic that installs `@angular/localize` stopped working recently.

### PR DESCRIPTION
**Pull request by znikola**
closes #7542

### CODE REVIEW

File: projects/schematics/src/migrations/2_0/ng-add-localize/ng-add-localize.ts [hunk 1]
```diff
@@ -45,12 +46,34 @@ function installPackageJsonDependencies(): Rule {
...
 
+function isAngularLocalizeInstalled(tree: Tree): boolean {
+  const pkgPath = '/package.json';
+  const buffer = tree.read(pkgPath);
+  if (!buffer) {
+    throw new SchematicsException('Could not find package.json');
+  }
+
+  return buffer.toString().includes(ANGULAR_LOCALIZE);
+}
```
Comment (psmul) [inline projects/schematics/src/migrations/2_0/ng-add-localize/ng-add-localize.ts]: Can we move it to `package-utils.ts`?

File: projects/schematics/src/migrations/2_0/ng-add-localize/ng-add-localize.ts [hunk 2]
```diff
@@ -45,12 +46,34 @@ function installPackageJsonDependencies(): Rule {
...
 }
 
+function isAngularLocalizeInstalled(tree: Tree): boolean {
+  const pkgPath = '/package.json';
+  const buffer = tree.read(pkgPath);
+  if (!buffer) {
+    throw new SchematicsException('Could not find package.json');
+  }
+
+  return buffer.toString().includes(ANGULAR_LOCALIZE);
```
Comment (psmul) [inline projects/schematics/src/migrations/2_0/ng-add-localize/ng-add-localize.ts]: I would feel safer if we check strictly into (dev)dependencies, instead of overall inclusion

**Review by psmul — CHANGES_REQUESTED** [review]

File: projects/schematics/src/migrations/2_0/ng-add-localize/ng-add-localize.ts [hunk 3]
```diff
@@ -46,11 +49,23 @@ function installPackageJsonDependencies(): Rule {
...
+        `Please run the following: ng add ${ANGULAR_LOCALIZE}`
+      );
+    }
+
+    return angularLocalizeInstalled
+      ? noop()
+      : chain([addPackageJsonDependencies(), installPackageJsonDependencies()])(
+          tree,
+          context
+        );
```
Comment (psmul) [inline projects/schematics/src/migrations/2_0/ng-add-localize/ng-add-localize.ts]: Not sure if we need to provide `(tree, context)`. From my experience, it works just fine without providing those.

**Review by psmul — APPROVED** [review]
