### PR TITLE
[GH-10647] input fields should emit value shortly after stopping to type

### LINKED ISSUE #10847: Issues with input field
There are some issues with attributes with input field:

1) Next button does not work after entering sth in input field

Product: CONF_LAPTOP
-> Click on Next button
  => works
-> In group CONF_LAPTOP_ACC go to attribute "Choose Engraving"
-> Enter something in the input field and immediately click on next button
  => Does not work. Group is not changed.
(If you wait for some seconds after entering sth in the input field it works)

Remark: in variant config UI there is also an issue with clicking next directly from an input field but the behavior is different (there the UI jumps to the top).

2) Value change of input field lost

Product: CONF_LAPTOP
-> go to group CONF_LAPTOP_ACC
-> enter a value for attribute "Choose Engraving"
-> click on checkbox "display port" of attribute "Laptop Connections"
-> change value for attribute "Choose Engraving" and immediately increase qty for value "Display port"
=> Value of "Choose Engraving" is changed back to old value

(Maybe same issue as with clicking on next group)

### PR DESCRIPTION
**Pull request by Uli-Tiger**
- rename QuantityConfig -> ConfiguratorUIConfig
- add config props to object 'rulebasedConfigurator' instead of to root. Config at runtime is a merge of all configs, so we should add all our module props to a common root.
- tests.ts move zone imports to the top in order to use fakeAsync
-  add debounce behaviour to input and numeric input component

### CODE REVIEW

File: feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+export abstract class ConfiguratorUIConfig {
+  rulebasedConfigurator: {
```
Comment (steinsebastian) [inline feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts]: As we are dealing with a configurator wouldn't it be better to use the term "settings" so that there are no confusions with "Configurator" <-> "Config". Suggestion: ConfiguratorUiSettings

File: feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+    quantityDebounceTime?: number;
+    inputDebounceTime?: number;
+  };
+}
+
+export const DefaultConfiguratorUIConfig: ConfiguratorUIConfig = {
+  rulebasedConfigurator: {
```
Comment (steinsebastian) [inline feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts]: Naming (see above).

File: feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+    quantityDebounceTime: 750,
```
Comment (steinsebastian) [inline feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts]: Is there a reason why the debounce time was increased for the quantity from 500 to 750?

**Review by steinsebastian — CHANGES_REQUESTED** [review]

File: feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts (hunk 3 above)
Comment (Uli-Tiger) [reply feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts]: I tested a lot and had the impression that 500ms are to short. Especially when clicking the plus or minus sign with the mouse.
The input field is only about typing no mouse interaction. 500ms seems to be sufficient.

Comment (steinsebastian) [reply feature-libs/product-configurator/rulebased/components/config/configurator-ui-config.ts]: ok
