### PR TITLE
fix: add assistive tech. message for card action cancelled (#15057)

### LINKED ISSUE #15057: Improve screen reader vocalization for cancelling a Card action
When users cancel the action on a Card component, visual users are able to recognize the result of the cancellation via UI. Users that rely on assistive technology should be informed of such result as well.

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #15057

### CODE REVIEW

**Review by developpeurweb — DISMISSED** [review]
Works well with JAWS/NVDA/VO

**Review by bit172 — DISMISSED** [review]

File: projects/assets/src/translations/en/common.ts [hunk 1]
```diff
@@ -192,4 +192,7 @@ export const common = {
     scriptFailedToLoad: 'Failed to load the script.',
     refreshThePage: 'Please refresh the page.',
   },
+  assistiveMessage: {
+    actionCancelled: 'Action cancelled nothing changed',
```
Comment (Pucek9) [inline projects/assets/src/translations/en/common.ts]:
```suggestion
    actionCancelled: 'Action cancelled, nothing changed',
```

**Review by Pucek9 — APPROVED** [review]
