### PR TITLE
fix: export in public api of CDC lib missing members

### LINKED ISSUE #18020: CdcAuthService Class not exported
**Describe the bug**
The Service CdcAuthService is currently not exported by spartacus via public api. We need to enhance this service to write additional properties to the local storage entry `spartacus⚿⚿auth`.

**Tell us the version of Spartacus**
- Library version: 6.5.0

**To Reproduce**
1. Try to extend the service `CdcAuthService`

**Expected behavior**
The Service `CdcAuthService` is exported via public api

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

### PR DESCRIPTION
**Pull request by Platonn**
Exported:
```
CdcAuthService
CdcAuthModule
CdcEventModule
CdcEventBuilder
```

closes https://jira.tools.sap/browse/CXSPA-5210
closes https://github.com/SAP/spartacus/issues/18020

### CODE REVIEW

File: integration-libs/cdc/core/auth/index.ts
Comment (Platonn) [inline integration-libs/cdc/core/auth/index.ts:1]: Git misunderstood it's a move of a file.
- I've removed `integration-libs/cdc/core/index.ts` as it was unused, confusing and redundant to `public_api.ts` in this same lib's root folder
- I've added file `integration-libs/cdc/core/auth/index.ts` - to cover the `/auth` folder which was not exported in public api bfore

File: integration-libs/cdc/core/public_api.ts [hunk 1]
```diff
@@ -4,5 +4,7 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+export * from './auth/index';
```
Comment (Platonn) [inline integration-libs/cdc/core/public_api.ts:7]: Added missing export of `/auth` folder.

**Review by pawelfras — APPROVED** [review]
